"use client";
import GameFrame from "@/components/GameFrame";
import Link from "next/link";
import {useState} from "react";
const NOTES=["C","D","E","F","G","A","B"];
const TONES:{[key:string]:number}={C:261.63,D:293.66,E:329.63,F:349.23,G:392,A:440,B:493.88};
const MELODIES=[
{label:"C E G",notes:["C","E","G"]},
{label:"G E C",notes:["G","E","C"]},
{label:"C D E F",notes:["C","D","E","F"]},
{label:"E E F G",notes:["E","E","F","G"]},
{label:"G F E D C",notes:["G","F","E","D","C"]}
];
function playTone(note:string){const Ctx=(window.AudioContext||(window as any).webkitAudioContext);const ctx=new Ctx();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=TONES[note];osc.type="sine";osc.connect(gain);gain.connect(ctx.destination);gain.gain.setValueAtTime(.18,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);osc.start();osc.stop(ctx.currentTime+.45);}
export default function Page(){const[i,setI]=useState(0),[made,setMade]=useState<string[]>([]),[msg,setMsg]=useState("Copy the melody."),[done,setDone]=useState(false);const cur=MELODIES[i];function add(n:string){playTone(n);setMade(m=>[...m,n]);}function check(){const ok=made.length===cur.notes.length&&made.every((n,j)=>n===cur.notes[j]);if(!ok){setMsg("Not quite. Reset and try again.");return;}if(i===MELODIES.length-1){setDone(true);return;}setMsg("Great melody!");setTimeout(()=>{setI(x=>x+1);setMade([]);setMsg("Copy the melody.");},600);}if(done)return <GameFrame title="Music Maker"><section style={finish}><div style={{fontSize:64}}>🎵</div><h1>Music Maker Complete</h1><p>You copied every melody.</p><Link href="/" style={home}>Go Home</Link></section></GameFrame>;return <GameFrame title="Music Maker"><main style={{width:"min(820px,100%)",margin:"0 auto"}}><section style={card}><small style={eyebrow}>MELODY {i+1} OF {MELODIES.length}</small><h1 style={{fontSize:"clamp(2.2rem,6vw,4rem)",margin:"14px 0"}}>Copy: {cur.label}</h1><div style={{display:"flex",justifyContent:"center",flexWrap:"wrap",gap:10,margin:"22px 0"}}>{NOTES.map((n,k)=><button key={n} onClick={()=>add(n)} style={{width:64,height:64,borderRadius:18,border:"1px solid rgba(255,255,255,.15)",background:["#d9ff5b","#c6b8ff","#e392ff","#8fe3cf","#ffcf70","#8ec5ff","#ff9b85"][k],color:"#10131b",fontSize:24,fontWeight:950}}>{n}</button>)}</div><div style={{minHeight:60,padding:14,borderRadius:18,background:"#222936",display:"flex",justifyContent:"center",alignItems:"center",gap:8,flexWrap:"wrap"}}>{made.length?made.map((n,j)=><span key={j} style={{padding:"8px 11px",borderRadius:999,background:"#fff",color:"#10131b",fontWeight:900}}>{n}</span>):<span style={{color:"#7f8898"}}>Your notes appear here</span>}</div><div style={{display:"flex",justifyContent:"center",gap:10,marginTop:22,flexWrap:"wrap"}}><button onClick={()=>setMade(m=>m.slice(0,-1))} style={secondary}>Undo</button><button onClick={()=>{setMade([]);setMsg("Copy the melody.");}} style={secondary}>Reset</button><button onClick={check} style={primary}>Check</button></div><p style={{color:"#c6b8ff",fontWeight:850}}>{msg}</p></section></main></GameFrame>}
const card:React.CSSProperties={padding:"clamp(24px,5vw,50px)",borderRadius:30,background:"#181d28",border:"1px solid rgba(255,255,255,.11)",textAlign:"center"};const eyebrow:React.CSSProperties={color:"#d9ff5b",fontWeight:950,letterSpacing:".18em"};const secondary:React.CSSProperties={minWidth:110,padding:"12px 18px",borderRadius:999,border:"2px solid #fff",background:"#fff",color:"#10131b",fontWeight:950};const primary:React.CSSProperties={...secondary,background:"#d9ff5b",border:"2px solid #d9ff5b"};const finish:React.CSSProperties={width:"min(700px,100%)",margin:"0 auto",padding:"clamp(30px,7vw,70px)",borderRadius:30,background:"#181d28",textAlign:"center"};const home:React.CSSProperties={display:"inline-block",padding:"13px 20px",borderRadius:999,background:"#d9ff5b",color:"#10131b",fontWeight:950,textDecoration:"none"};