"use client";

import GameFrame from "@/components/GameFrame";
import { recordLearningAttempt } from "@/lib/adrian-learning";
import { useFamilyProfiles } from "@/lib/adrian-profiles";
import { useGameSession } from "@/lib/game-session";
import Link from "next/link";
import { useState } from "react";

const GAME_SLUG = "cyber-city-five";
type Stage = "intro" | "play" | "upgrade" | "core" | "finish";
type Feedback = "question" | "hint" | "explanation";
type Program = "sentinel" | "cipher" | "overclock";
type Upgrade = "firewall" | "cache" | "turbo";
type Mission = { district: string; emoji: string; subject: "Math" | "Reading" | "Science"; standard: string; skillId: string; skillLabel: string; story: string; prompt: string; choices: string[]; answer: string; hint: string; explanation: string; fragment: string };

const PROGRAMS = {
  sentinel: { name: "Sentinel", emoji: "🛡️", power: "Double firewall", text: "Starts with two breach shields." },
  cipher: { name: "Cipher", emoji: "🔐", power: "Safe decrypt", text: "Starts with two clues that preserve a combo." },
  overclock: { name: "Overclock", emoji: "⚡", power: "Data surge", text: "First-try solves earn an extra data chip." },
};

const UPGRADES = {
  firewall: { name: "Firewall Patch", emoji: "🧱", text: "+1 breach shield" },
  cache: { name: "Hint Cache", emoji: "💡", text: "+1 safe decrypt" },
  turbo: { name: "Turbo Packet", emoji: "🚀", text: "+3 data chips" },
};

const MISSIONS: Mission[] = [
  { district: "Decimal Docks", emoji: "🔢", subject: "Math", standard: "5.NBT.A.3", skillId: "math-decimals", skillLabel: "Compare decimals", story: "Two security keys are labeled 8.47 and 8.407.", prompt: "Which key has the greater value?", choices: ["8.47", "8.407", "They are equal", "Not enough information"], answer: "8.47", hint: "Write 8.47 as 8.470, then compare thousandths.", explanation: "8.470 is greater than 8.407, so 8.47 is greater.", fragment: "01" },
  { district: "Evidence Exchange", emoji: "📜", subject: "Reading", standard: "RL.5.1", skillId: "reading-comprehension-detail", skillLabel: "Quote accurate evidence", story: "The log says, ‘Mina checked every lock before leaving, then returned to test the alarm.’", prompt: "Which detail best supports that Mina was careful?", choices: ["She checked every lock and tested the alarm", "She left the building", "Her name was Mina", "The log used quotation marks"], answer: "She checked every lock and tested the alarm", hint: "Choose the exact actions that prove careful behavior.", explanation: "Checking every lock and returning to test the alarm directly support the inference.", fragment: "10" },
  { district: "Fraction Firewall", emoji: "🧮", subject: "Math", standard: "5.NF.A.1", skillId: "math-fractions", skillLabel: "Add unlike fractions", story: "The firewall is 1/3 repaired in one sector and 1/4 repaired in another.", prompt: "How much is repaired altogether?", choices: ["7/12", "2/7", "1/7", "2/12"], answer: "7/12", hint: "Use twelfths: 1/3 = 4/12 and 1/4 = 3/12.", explanation: "4/12 + 3/12 = 7/12.", fragment: "11" },
  { district: "Matter Matrix", emoji: "🧊", subject: "Science", standard: "5-PS1-1", skillId: "engineering-materials", skillLabel: "Model matter as particles", story: "A sealed ice cube melts into liquid water but no material leaves the container.", prompt: "Which model best explains what changed?", choices: ["The same particles moved more freely", "The particles vanished", "New matter appeared", "The particles became light"], answer: "The same particles moved more freely", hint: "A change of state rearranges particles without creating or destroying matter.", explanation: "The water particles remain present but move differently in the liquid state.", fragment: "00" },
  { district: "Claim Circuit", emoji: "⚖️", subject: "Reading", standard: "RI.5.8", skillId: "reading-inference", skillLabel: "Evaluate claims and evidence", story: "A designer claims Shield B is stronger because it blocked 18 of 20 test signals. Shield A blocked 9 of 20.", prompt: "Which statement evaluates the claim best?", choices: ["The test evidence supports the claim", "The claim has no evidence", "Shield A performed better", "The results are identical"], answer: "The test evidence supports the claim", hint: "Compare the measured results for both shields.", explanation: "Shield B blocked twice as many signals, so the evidence supports the claim.", fragment: "01" },
  { district: "Volume Vault", emoji: "📦", subject: "Math", standard: "5.MD.C.3", skillId: "math-measurement", skillLabel: "Understand volume", story: "A data vault is 5 units long, 4 units wide, and 3 units high.", prompt: "What is its volume?", choices: ["60 cubic units", "12 cubic units", "20 cubic units", "47 cubic units"], answer: "60 cubic units", hint: "Multiply length × width × height.", explanation: "5 × 4 × 3 = 60 cubic units.", fragment: "10" },
  { district: "Gravity Grid", emoji: "🌍", subject: "Science", standard: "5-PS2-1", skillId: "science-space", skillLabel: "Use evidence about gravity", story: "A dropped tool falls toward the ground in every repeated test.", prompt: "Which claim is best supported?", choices: ["Earth pulls objects toward its center", "Air pushes every object upward", "Gravity only works at night", "The tool chooses a direction"], answer: "Earth pulls objects toward its center", hint: "Use the repeated direction of motion as evidence.", explanation: "Repeated downward motion supports the claim that Earth’s gravity pulls objects toward its center.", fragment: "11" },
  { district: "Star Signal Core", emoji: "⭐", subject: "Science", standard: "5-ESS1-1", skillId: "science-space", skillLabel: "Explain apparent brightness", story: "Two identical stars produce the same light, but one is much farther from Earth.", prompt: "Why does the farther star appear dimmer?", choices: ["Its light spreads over a greater distance", "It contains no matter", "Gravity turns off its light", "Distance makes it physically smaller"], answer: "Its light spreads over a greater distance", hint: "Think about how the same amount of light reaches us from different distances.", explanation: "Light from a more distant star spreads out more before reaching Earth, so it appears dimmer.", fragment: "CORE" },
];

function tone(on: boolean, correct: boolean) { if (!on || typeof window === "undefined" || !("AudioContext" in window)) return; const c = new AudioContext(); const o = c.createOscillator(); const g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = correct ? "square" : "sawtooth"; o.frequency.value = correct ? 880 : 145; g.gain.setValueAtTime(.05, c.currentTime); g.gain.exponentialRampToValueAtTime(.001, c.currentTime + .16); o.start(); o.stop(c.currentTime + .17); o.addEventListener("ended", () => void c.close()); }

export default function CyberCityFivePage() {
  const { activeProfile } = useFamilyProfiles();
  const { completeGame, restartGame } = useGameSession(GAME_SLUG);
  const [stage, setStage] = useState<Stage>("intro"); const [program, setProgram] = useState<Program>("sentinel"); const [index, setIndex] = useState(0); const [feedback, setFeedback] = useState<Feedback>("question"); const [selected, setSelected] = useState<string | null>(null); const [wrong, setWrong] = useState(0); const [threat, setThreat] = useState(0); const [shields, setShields] = useState(2); const [clues, setClues] = useState(2); const [chips, setChips] = useState(0); const [combo, setCombo] = useState(0); const [bestCombo, setBestCombo] = useState(0); const [fragments, setFragments] = useState<string[]>([]); const [upgrades, setUpgrades] = useState<Upgrade[]>([]); const [sound, setSound] = useState(true);
  const mission = MISSIONS[index];

  function begin() { setShields(program === "sentinel" ? 2 : 1); setClues(program === "cipher" ? 2 : 0); setStage("play"); }
  function save(correct: boolean) { recordLearningAttempt({ gameSlug: GAME_SLUG, subject: mission.subject, skillId: mission.skillId, skillLabel: mission.skillLabel, prompt: `${mission.story} ${mission.prompt}`, correctAnswer: mission.answer, correct, data: { standardCode: mission.standard, district: mission.district, adaptiveSupport: wrong > 0, program, upgrades: upgrades.join(",") } }, activeProfile.id); }
  function choose(choice: string) { if (feedback === "explanation") return; setSelected(choice); const correct = choice === mission.answer; if (!correct && wrong === 0) { save(false); setWrong(1); setFeedback("hint"); setCombo(0); if (shields) setShields((v) => v - 1); else setThreat((v) => Math.min(5, v + 1)); tone(sound, false); return; } if (!correct) { setWrong((v) => v + 1); setFeedback("explanation"); setCombo(0); setThreat((v) => Math.min(5, v + 1)); tone(sound, false); return; } save(true); const first = wrong === 0; const nextCombo = first ? combo + 1 : 0; setCombo(nextCombo); setBestCombo((v) => Math.max(v, nextCombo)); setChips((v) => v + (first ? 2 + (program === "overclock" ? 1 : 0) : 1)); setThreat((v) => Math.max(0, v - 1)); setFragments((v) => [...v, mission.fragment]); setFeedback("explanation"); tone(sound, true); }
  function clue() { if (feedback !== "question") return; setFeedback("hint"); if (clues) setClues((v) => v - 1); else { setCombo(0); setThreat((v) => Math.min(5, v + 1)); } }
  function resetQuestion() { setFeedback("question"); setSelected(null); setWrong(0); }
  function advance() { if (index === MISSIONS.length - 1) { setStage("core"); return; } if ((index + 1) % 2 === 0) { setStage("upgrade"); return; } setIndex((v) => v + 1); resetQuestion(); }
  function install(id: Upgrade) { setUpgrades((v) => [...v, id]); if (id === "firewall") setShields((v) => v + 1); if (id === "cache") setClues((v) => v + 1); if (id === "turbo") setChips((v) => v + 3); setIndex((v) => v + 1); resetQuestion(); setStage("play"); }
  function sealCore() { completeGame({ xp: 55 + chips + bestCombo * 3 - threat * 2, coins: 14 + chips, score: chips * 120 + bestCombo * 45 + (5 - threat) * 30 }); setStage("finish"); }
  function replay() { restartGame(); setStage("intro"); setIndex(0); resetQuestion(); setThreat(0); setShields(2); setClues(2); setChips(0); setCombo(0); setBestCombo(0); setFragments([]); setUpgrades([]); }

  if (stage === "intro") return <GameFrame title="Cyber City Five"><style>{css}</style><main style={page}><section style={hero}><div className="pulse" style={big}>🌐🛡️</div><span style={eyebrow}>GRADE 5 STRATEGY ADVENTURE</span><h1 style={title}>Cyber City is under attack.</h1><p style={lead}>Choose a program, defend eight districts, build a custom upgrade stack, manage the threat meter, and restore the city core with Grade 5 math, reading, and science.</p><div style={grid}>{Object.entries(PROGRAMS).map(([id, item]) => <button key={id} onClick={() => setProgram(id as Program)} aria-pressed={program === id} style={{...optionCard,...(program === id ? activeOption : {})}}><span style={{fontSize:42}}>{item.emoji}</span><strong>{item.name}</strong><small>{item.power}</small><span>{item.text}</span></button>)}</div><button onClick={begin} style={primary}>Enter the network →</button><button onClick={() => setSound((v) => !v)} style={secondary}>{sound ? "🔊 Sound on" : "🔇 Sound off"}</button></section></main></GameFrame>;
  if (stage === "upgrade") return <GameFrame title="Cyber City Five"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>🧬⚙️</div><span style={eyebrow}>UPGRADE FORK</span><h1 style={sectionTitle}>Choose how your program evolves.</h1><p style={lead}>Your choice changes the resources available in the next network wave.</p><div style={grid}>{Object.entries(UPGRADES).map(([id, item]) => <button key={id} onClick={() => install(id as Upgrade)} style={optionCard}><span style={{fontSize:42}}>{item.emoji}</span><strong>{item.name}</strong><span>{item.text}</span></button>)}</div></section></main></GameFrame>;
  if (stage === "core") return <GameFrame title="Cyber City Five"><style>{css}</style><main style={page}><section style={hero}><div className="pulse" style={big}>🔐🌐</div><span style={eyebrow}>CITY CORE RESTORED</span><h1 style={sectionTitle}>The eight code fragments align.</h1><p style={lead}>Your loadout, evidence, calculations, and science models rebuilt the defense network.</p><div style={stats}><strong>💾 {chips}</strong><strong>🔥 {bestCombo}×</strong><strong>⚠️ {threat}/5</strong><strong>🧬 {upgrades.length}</strong></div><button onClick={sealCore} style={primary}>Seal the city core →</button></section></main></GameFrame>;
  if (stage === "finish") return <GameFrame title="Cyber City Five"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>🏆🌐🛡️</div><span style={eyebrow}>NETWORK SECURE</span><h1 style={sectionTitle}>{activeProfile.name} saved Cyber City Five!</h1><p style={lead}>You defended eight Grade 5 standards and built a unique three-upgrade strategy.</p><div style={stats}><strong>💾 {chips} chips</strong><strong>🔥 {bestCombo}× combo</strong><strong>⚠️ {threat}/5 threat</strong></div><button onClick={replay} style={primary}>Build a new defense</button><Link href="/school" style={link}>Return to School Mode</Link></section></main></GameFrame>;

  return <GameFrame title="Cyber City Five"><style>{css}</style><main style={page}><header style={hud}><strong>{PROGRAMS[program].emoji} {PROGRAMS[program].name}</strong><div>🛡️ {shields} · 💡 {clues} · 💾 {chips} · 🔥 {combo}× <button onClick={() => setSound((v) => !v)} style={soundButton}>{sound ? "🔊" : "🔇"}</button></div></header><div style={threatBar}><span>NETWORK THREAT</span><div style={track}><div style={{...threatFill,width:`${threat * 20}%`}} /></div><strong>{threat}/5</strong></div><div style={progress}><div style={{...progressFill,width:`${((index + 1) / MISSIONS.length) * 100}%`}} /></div><section style={card}><div style={top}><span style={chip}>{mission.subject}</span><span>District {index + 1}/8 · {mission.standard}</span></div><div className="float" style={missionEmoji}>{mission.emoji}</div><span style={district}>{mission.district}</span><p style={story}>{mission.story}</p><h1 style={question}>{mission.prompt}</h1><div style={choices}>{mission.choices.map((choice) => { const right = choice === mission.answer; const wrongChoice = selected === choice && !right; const reveal = feedback === "explanation" && right; return <button key={choice} data-correct={right ? "true" : "false"} disabled={feedback === "explanation" || wrongChoice} onClick={() => choose(choice)} style={{...choiceButton,...(reveal ? correctStyle : wrongChoice ? wrongStyle : {})}}>{choice}</button>; })}</div><section role="status" style={teaching}><strong>{feedback === "question" ? "DEFENSE CONSOLE" : feedback === "hint" ? "DECRYPT CLUE" : "SYSTEM LOG"}</strong><p>{feedback === "question" ? "Choose the strongest defense command." : feedback === "hint" ? mission.hint : selected === mission.answer ? mission.explanation : `Correct command: ${mission.answer}. ${mission.explanation}`}</p>{feedback === "question" ? <button onClick={clue} style={secondary}>{clues ? `Use safe decrypt (${clues})` : "Decrypt a clue"}</button> : feedback === "hint" ? <span>Recalculate and try again. The district is still online.</span> : <button onClick={advance} style={primary}>{index === 7 ? "Restore the city core →" : "Capture the code fragment →"}</button>}</section><div style={fragmentRow}>{fragments.map((f, i) => <span key={`${f}-${i}`} style={fragment}>{f}</span>)}</div></section></main></GameFrame>;
}

const css = `@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}@keyframes pulse{0%,100%{filter:drop-shadow(0 0 10px #5ce1ff66)}50%{filter:drop-shadow(0 0 28px #d9ff5baa)}}@keyframes pop{0%{transform:scale(.7);opacity:0}80%{transform:scale(1.08)}100%{transform:scale(1);opacity:1}}.float{animation:float 2s ease-in-out infinite}.pulse{animation:pulse 1.8s ease-in-out infinite}.pop{animation:pop .5s ease-out both}@media(prefers-reduced-motion:reduce){.float,.pulse,.pop{animation:none}}`;
const page: React.CSSProperties = { minHeight:"100vh", padding:"20px 14px 80px", background:"radial-gradient(circle at top,#17364a,#09131d 55%,#05080c)", color:"#fff" };
const hero: React.CSSProperties = { maxWidth:920, margin:"0 auto", padding:"clamp(28px,6vw,58px)", borderRadius:34, textAlign:"center", background:"linear-gradient(145deg,rgba(92,225,255,.13),rgba(217,255,91,.08),#101b25)", border:"1px solid rgba(92,225,255,.3)" };
const big: React.CSSProperties = { fontSize:"clamp(5rem,16vw,9rem)" }; const eyebrow: React.CSSProperties = { color:"#d9ff5b", fontSize:11, fontWeight:950, letterSpacing:".15em" }; const title: React.CSSProperties = { margin:"10px auto", fontSize:"clamp(2.8rem,8vw,5.8rem)", lineHeight:.9, letterSpacing:"-.06em" }; const sectionTitle: React.CSSProperties = { ...title, fontSize:"clamp(2.5rem,7vw,5rem)" }; const lead: React.CSSProperties = { maxWidth:750, margin:"0 auto 22px", color:"#c6d1db", lineHeight:1.55, fontWeight:700 };
const grid: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,210px),1fr))", gap:12, margin:"22px 0" }; const optionCard: React.CSSProperties = { display:"grid", gap:7, padding:18, borderRadius:22, border:"1px solid #29465b", background:"#0b151e", color:"#fff", cursor:"pointer" }; const activeOption: React.CSSProperties = { borderColor:"#d9ff5b", boxShadow:"0 0 0 3px rgba(217,255,91,.12)" };
const primary: React.CSSProperties = { border:0, borderRadius:999, padding:"14px 20px", background:"#d9ff5b", color:"#071018", fontWeight:950, cursor:"pointer", margin:5 }; const secondary: React.CSSProperties = { border:"1px solid #35566d", borderRadius:999, padding:"11px 17px", background:"#101d28", color:"#fff", fontWeight:900, cursor:"pointer", margin:5 }; const link: React.CSSProperties = { display:"block", marginTop:16, color:"#5ce1ff", fontWeight:900 };
const hud: React.CSSProperties = { maxWidth:920, margin:"0 auto 10px", display:"flex", justifyContent:"space-between", gap:12, flexWrap:"wrap", padding:"12px 16px", borderRadius:18, background:"rgba(7,16,24,.94)", border:"1px solid #29465b" }; const soundButton: React.CSSProperties = { border:0, background:"transparent", cursor:"pointer" }; const threatBar: React.CSSProperties = { maxWidth:920, margin:"0 auto 10px", display:"grid", gridTemplateColumns:"auto 1fr auto", gap:10, alignItems:"center", fontSize:11, fontWeight:950, color:"#ffb5bf" }; const track: React.CSSProperties = { height:8, borderRadius:999, overflow:"hidden", background:"#24313b" }; const threatFill: React.CSSProperties = { height:"100%", background:"linear-gradient(90deg,#ffd166,#ff8e9e)", transition:"width .3s" }; const progress: React.CSSProperties = { maxWidth:920, height:8, margin:"0 auto 14px", borderRadius:999, overflow:"hidden", background:"#24313b" }; const progressFill: React.CSSProperties = { height:"100%", background:"linear-gradient(90deg,#5ce1ff,#d9ff5b)" };
const card: React.CSSProperties = { maxWidth:920, margin:"0 auto", padding:"clamp(22px,5vw,42px)", borderRadius:30, background:"linear-gradient(145deg,#101b25,#081119)", border:"1px solid #29465b" }; const top: React.CSSProperties = { display:"flex", justifyContent:"space-between", gap:10, flexWrap:"wrap", color:"#9fb3c2", fontSize:12, fontWeight:850 }; const chip: React.CSSProperties = { padding:"5px 9px", borderRadius:999, background:"#5ce1ff", color:"#071018" }; const missionEmoji: React.CSSProperties = { fontSize:"clamp(4rem,12vw,7rem)", textAlign:"center", marginTop:12 }; const district: React.CSSProperties = { display:"block", textAlign:"center", color:"#d9ff5b", fontWeight:950, letterSpacing:".1em" }; const story: React.CSSProperties = { color:"#c7d3dc", lineHeight:1.55, fontWeight:700, textAlign:"center" }; const question: React.CSSProperties = { textAlign:"center", fontSize:"clamp(1.8rem,5vw,3rem)" }; const choices: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,220px),1fr))", gap:10 }; const choiceButton: React.CSSProperties = { minHeight:66, padding:"15px 13px", borderRadius:18, border:"1px solid #35566d", background:"#101d28", color:"#fff", fontWeight:900, cursor:"pointer" }; const correctStyle: React.CSSProperties = { background:"#173b2c", borderColor:"#d9ff5b" }; const wrongStyle: React.CSSProperties = { background:"#451c29", borderColor:"#ff8e9e" }; const teaching: React.CSSProperties = { marginTop:18, padding:18, borderRadius:20, background:"#060d13", border:"1px solid #29465b", textAlign:"center" }; const fragmentRow: React.CSSProperties = { display:"flex", flexWrap:"wrap", justifyContent:"center", gap:7, marginTop:15 }; const fragment: React.CSSProperties = { padding:"6px 9px", borderRadius:8, background:"#102d3b", color:"#5ce1ff", fontFamily:"monospace", fontWeight:950 }; const stats: React.CSSProperties = { display:"flex", justifyContent:"center", gap:12, flexWrap:"wrap", margin:"22px 0", fontSize:"1.2rem" };
