"use client";
import { useMemo, useState } from "react";
import GameFrame from "@/components/GameFrame";
const WORDS=[
 {word:"PLANET",hint:"A world that travels around a star."},{word:"ROCKET",hint:"It blasts into space."},{word:"JUNGLE",hint:"A thick, wild forest."},{word:"PUZZLE",hint:"Something you solve."},{word:"THUNDER",hint:"The sound that follows lightning."},{word:"VOLCANO",hint:"A mountain that can erupt."},{word:"OCEAN",hint:"A giant body of salt water."},{word:"ROBOT",hint:"A machine that follows instructions."}
];
const shuffle=(w:string)=>w.split("").sort(()=>Math.random()-.5);
export default function WordBuilderPage(){
 const [index,setIndex]=useState(0),[picked,setPicked]=useState<number[]>([]),[score,setScore]=useState(0),[message,setMessage]=useState("Tap letters to build the word.");
 const current=WORDS[index],letters=useMemo(()=>shuffle(current.word),[current.word]),built=picked.map(i=>letters[i]).join("");
 function check(){if(built===current.word){setScore(score+1);setMessage("Correct! New word unlocked.");setTimeout(()=>{setIndex((index+1)%WORDS.length);setPicked([]);setMessage("Tap letters to build the word.");},700);}else setMessage("Almost. Try moving the letters around.");}
 return <GameFrame title="Word Builder"><main style={{width:"min(820px,100%)",margin:"0 auto"}}><section style={{padding:"clamp(24px,5vw,50px)",border:"1px solid rgba(255,255,255,.11)",borderRadius:30,background:"#181d28",textAlign:"center"}}><div style={{display:"flex",justifyContent:"space-between",color:"#aab1bf"}}><span>Word {index+1} of {WORDS.length}</span><span>Score {score}</span></div><small style={{display:"block",marginTop:22,color:"#d9ff5b",fontWeight:900,letterSpacing:2}}>WORD BUILDER</small><h1 style={{fontSize:"clamp(1.8rem,5vw,3.4rem)",lineHeight:1.05}}>{current.hint}</h1><div style={{display:"flex",justifyContent:"center",flexWrap:"wrap",gap:8,margin:"25px 0"}}>{current.word.split("").map((_,i)=><div key={i} style={{width:46,height:56,borderBottom:"4px solid #c6b8ff",fontSize:32,fontWeight:900}}>{built[i]||""}</div>)}</div><div style={{display:"flex",justifyContent:"center",flexWrap:"wrap",gap:10}}>{letters.map((l,i)=><button key={i} disabled={picked.includes(i)} onClick={()=>setPicked([...picked,i])} style={{width:58,height:58,border:"1px solid rgba(255,255,255,.11)",borderRadius:16,color:"white",background:"#222936",fontSize:26,fontWeight:900,opacity:picked.includes(i)?.2:1}}>{l}</button>)}</div><div style={{display:"flex",justifyContent:"center",gap:9,marginTop:24,flexWrap:"wrap"}}><button onClick={()=>setPicked(picked.slice(0,-1))}>Undo</button><button onClick={()=>setPicked([])}>Reset</button><button onClick={check} style={{background:"#d9ff5b",color:"#10131b",fontWeight:900}}>Check</button></div><p style={{minHeight:25,color:"#c6b8ff",fontWeight:800}}>{message}</p></section></main></GameFrame>;
}
