"use client";
import { useState } from "react";
import GameFrame from "@/components/GameFrame";
const Q=[
 ["Why does lightning happen?",["Electric charge builds up in clouds","The moon shakes the sky","Clouds are made of fire"],0,"Positive and negative charges separate inside storm clouds. Electricity jumps when the difference becomes large enough."],
 ["Why do people sweat?",["To make skin shiny","To cool the body","To store extra water"],1,"Sweat carries heat away when it evaporates from the skin."],
 ["Why can snow become a snowball?",["Snow is magnetic","Pressure helps snow crystals stick together","Snow contains glue"],1,"Pressing snow can melt a tiny layer of water. It refreezes and helps the crystals lock together."],
 ["Why do computers need time to load?",["They gather instructions and data","They get tired","They ask another computer for permission"],0,"A computer must find, process, and arrange information before it can show the next screen."],
 ["What does the heart do?",["It pumps blood around the body","It stores memories","It makes bones grow"],0,"The heart is a muscular pump that moves blood, oxygen, and nutrients through the body."]
] as const;
export default function ScienceQuestPage(){const [i,setI]=useState(0),[choice,setChoice]=useState<number|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false);const cur=Q[i];function answer(x:number){if(choice!==null)return;setChoice(x);if(x===cur[2])setScore(score+1);}function next(){if(i===Q.length-1)setDone(true);else{setI(i+1);setChoice(null);}}function restart(){setI(0);setChoice(null);setScore(0);setDone(false);}return <GameFrame title="Science Quest"><main style={{width:"min(820px,100%)",margin:"0 auto"}}><section style={{padding:"clamp(24px,5vw,50px)",border:"1px solid rgba(255,255,255,.11)",borderRadius:30,background:"#181d28"}}>{done?<div style={{textAlign:"center"}}><small style={{color:"#d9ff5b",fontWeight:900}}>QUEST COMPLETE</small><h1 style={{fontSize:70}}>{score} / {Q.length}</h1><p>You unlocked five new pieces of science knowledge.</p><button onClick={restart} style={{background:"#d9ff5b",color:"#10131b",fontWeight:900}}>Play again</button></div>:<><div style={{display:"flex",justifyContent:"space-between",color:"#aab1bf"}}><span>Question {i+1} of {Q.length}</span><span>Score {score}</span></div><small style={{display:"block",marginTop:25,color:"#d9ff5b",fontWeight:900,letterSpacing:2}}>SCIENCE QUEST</small><h1 style={{fontSize:"clamp(2.1rem,6vw,4rem)",lineHeight:1}}>{cur[0]}</h1><div style={{display:"grid",gap:10}}>{cur[1].map((a,x)=>{const bg=choice!==null&&x===cur[2]?"rgba(217,255,91,.12)":choice===x&&x!==cur[2]?"rgba(255,154,167,.12)":"#222936";return <button key={a} onClick={()=>answer(x)} style={{minHeight:64,padding:13,border:"1px solid rgba(255,255,255,.11)",borderRadius:18,color:"white",background:bg,textAlign:"left",fontWeight:800}}>{String.fromCharCode(65+x)}. {a}</button>})}</div>{choice!==null&&<div style={{marginTop:20,paddingTop:20,borderTop:"1px solid rgba(255,255,255,.11)"}}><strong style={{color:"#d9ff5b"}}>{choice===cur[2]?"Correct.":"Good try."}</strong><p style={{color:"#aab1bf",lineHeight:1.55}}>{cur[3]}</p><button onClick={next} style={{background:"#d9ff5b",color:"#10131b",fontWeight:900}}>{i===Q.length-1?"See results":"Next question"}</button></div>}</>}</section></main></GameFrame>}
