"use client";

import GameFrame from "@/components/GameFrame";
import { recordLearningAttempt } from "@/lib/adrian-learning";
import { useFamilyProfiles } from "@/lib/adrian-profiles";
import { useGameSession } from "@/lib/game-session";
import Link from "next/link";
import { useState } from "react";

const GAME_SLUG = "space-station-sigma";
type Stage = "intro" | "play" | "checkpoint" | "finish";
type Feedback = "question" | "hint" | "explanation";
type Role = "engineer" | "navigator" | "scientist";
type Mission = { sector: string; emoji: string; subject: "Math" | "Reading" | "Science"; standard: string; skillId: string; skillLabel: string; story: string; prompt: string; choices: string[]; answer: string; hint: string; explanation: string; badge: string };

const ROLES = {
  engineer: { name: "Reactor Engineer", emoji: "🛠️", power: "Shield", text: "Blocks the first energy loss." },
  navigator: { name: "Star Navigator", emoji: "🧭", power: "Combo boost", text: "First-try solves earn extra stardust." },
  scientist: { name: "Mission Scientist", emoji: "🔬", power: "Free clues", text: "Starts with two clues that preserve your combo." },
};

const MISSIONS: Mission[] = [
  { sector: "Reactor Bay", emoji: "⚡", subject: "Math", standard: "3.OA.A.1", skillId: "math-multiplication", skillLabel: "Interpret multiplication", story: "Four reactor rings each need six energy cells.", prompt: "How many cells are needed?", choices: ["10", "18", "24", "30"], answer: "24", hint: "Think 4 groups of 6.", explanation: "4 × 6 = 24 energy cells.", badge: "⚡ Reactor badge" },
  { sector: "Signal Deck", emoji: "📡", subject: "Reading", standard: "RI.3.1", skillId: "reading-key-details", skillLabel: "Use text evidence", story: "The station lost contact because a meteor bent the main antenna.", prompt: "What caused the signal loss?", choices: ["A meteor bent the antenna", "The crew slept", "The moon disappeared", "The engine was cold"], answer: "A meteor bent the antenna", hint: "Look for the stated cause.", explanation: "The text directly says the meteor bent the antenna.", badge: "📡 Signal badge" },
  { sector: "Cargo Lab", emoji: "📦", subject: "Math", standard: "3.OA.B.6", skillId: "math-division", skillLabel: "Understand division", story: "Thirty-six samples must be split equally into six lockers.", prompt: "How many samples go in each locker?", choices: ["5", "6", "7", "8"], answer: "6", hint: "Ask 6 times what equals 36.", explanation: "36 ÷ 6 = 6 because 6 × 6 = 36.", badge: "📦 Cargo badge" },
  { sector: "Moon Greenhouse", emoji: "🌱", subject: "Science", standard: "3-LS1-1", skillId: "science-life-cycles", skillLabel: "Plant life cycles", story: "A seed has sprouted, grown leaves, and formed a flower.", prompt: "What usually comes next?", choices: ["The plant makes seeds", "The plant becomes a rock", "The leaves become metal", "The roots fly away"], answer: "The plant makes seeds", hint: "Think about how flowering plants begin a new cycle.", explanation: "Flowers help plants produce seeds for the next generation.", badge: "🌱 Biology badge" },
  { sector: "Orbit Map", emoji: "🪐", subject: "Reading", standard: "RL.3.3", skillId: "reading-character-motivation", skillLabel: "Character motivation", story: "Maya checked the orbit map twice because she wanted the crew to arrive safely.", prompt: "Why did Maya check twice?", choices: ["She wanted a safe arrival", "She disliked maps", "She forgot the mission", "She wanted to miss the planet"], answer: "She wanted a safe arrival", hint: "Find what Maya wanted.", explanation: "Her goal was to help the crew arrive safely.", badge: "🪐 Navigation badge" },
  { sector: "Meteor Shield", emoji: "☄️", subject: "Science", standard: "3-5-ETS1-2", skillId: "engineering-design", skillLabel: "Compare design solutions", story: "Shield A stops 3 of 10 meteors. Shield B stops 9 of 10.", prompt: "Which design should the crew improve?", choices: ["Shield B", "Shield A", "Neither test matters", "Pick randomly"], answer: "Shield B", hint: "Use the test evidence.", explanation: "Shield B performed better, stopping 9 of 10 meteors.", badge: "🛡️ Engineering badge" },
  { sector: "Final Core", emoji: "🌌", subject: "Math", standard: "3.OA.D.8", skillId: "math-word-problems", skillLabel: "Two-step word problems", story: "The crew finds 5 crates with 8 crystals each, then uses 13 crystals.", prompt: "How many crystals remain?", choices: ["27", "35", "40", "53"], answer: "27", hint: "Multiply first, then subtract.", explanation: "5 × 8 = 40, and 40 − 13 = 27.", badge: "🌌 Core badge" },
];

function tone(on: boolean, correct: boolean) { if (!on || typeof window === "undefined" || !("AudioContext" in window)) return; const c = new AudioContext(); const o = c.createOscillator(); const g = c.createGain(); o.connect(g); g.connect(c.destination); o.frequency.value = correct ? 820 : 180; g.gain.setValueAtTime(.06, c.currentTime); g.gain.exponentialRampToValueAtTime(.001, c.currentTime + .16); o.start(); o.stop(c.currentTime + .17); o.addEventListener("ended", () => void c.close()); }

export default function SpaceStationSigmaPage() {
  const { activeProfile } = useFamilyProfiles();
  const { completeGame, restartGame } = useGameSession(GAME_SLUG);
  const [stage, setStage] = useState<Stage>("intro"); const [role, setRole] = useState<Role>("engineer"); const [index, setIndex] = useState(0); const [feedback, setFeedback] = useState<Feedback>("question"); const [selected, setSelected] = useState<string | null>(null); const [wrong, setWrong] = useState(0); const [energy, setEnergy] = useState(3); const [shield, setShield] = useState(1); const [clues, setClues] = useState(2); const [stardust, setStardust] = useState(0); const [combo, setCombo] = useState(0); const [bestCombo, setBestCombo] = useState(0); const [badges, setBadges] = useState<string[]>([]); const [sound, setSound] = useState(true);
  const mission = MISSIONS[index]; const roleInfo = ROLES[role];

  function begin() { setShield(role === "engineer" ? 1 : 0); setClues(role === "scientist" ? 2 : 0); setStage("play"); }
  function save(correct: boolean) { recordLearningAttempt({ gameSlug: GAME_SLUG, subject: mission.subject, skillId: mission.skillId, skillLabel: mission.skillLabel, prompt: `${mission.story} ${mission.prompt}`, correctAnswer: mission.answer, correct, data: { standardCode: mission.standard, sector: mission.sector, adaptiveSupport: wrong > 0 } }, activeProfile.id); }
  function choose(choice: string) { if (feedback === "explanation") return; setSelected(choice); const correct = choice === mission.answer; if (!correct && wrong === 0) { save(false); setWrong(1); setFeedback("hint"); setCombo(0); if (shield) setShield(0); else setEnergy((v) => Math.max(0, v - 1)); tone(sound, false); return; } if (!correct) { setWrong((v) => v + 1); setFeedback("explanation"); setCombo(0); tone(sound, false); return; } save(true); const first = wrong === 0; const nextCombo = first ? combo + 1 : 0; setCombo(nextCombo); setBestCombo((v) => Math.max(v, nextCombo)); setStardust((v) => v + (first ? 2 + (role === "navigator" ? 1 : 0) : 1)); setBadges((v) => [...v, mission.badge]); setFeedback("explanation"); tone(sound, true); }
  function clue() { if (feedback !== "question") return; setFeedback("hint"); if (clues) setClues((v) => v - 1); else setCombo(0); }
  function advance() { if (index === MISSIONS.length - 1) { completeGame({ xp: 42 + stardust + bestCombo * 3, coins: 10 + stardust, score: stardust * 100 + bestCombo * 30 + energy * 20 }); setStage("finish"); return; } if ((index + 1) % 2 === 0) { setStage("checkpoint"); return; } setIndex((v) => v + 1); reset(); }
  function reset() { setFeedback("question"); setSelected(null); setWrong(0); }
  function continueCheckpoint() { setEnergy((v) => Math.max(v, 2)); setIndex((v) => v + 1); reset(); setStage("play"); }
  function replay() { restartGame(); setStage("intro"); setIndex(0); reset(); setEnergy(3); setStardust(0); setCombo(0); setBestCombo(0); setBadges([]); }

  if (stage === "intro") return <GameFrame title="Space Station Sigma"><style>{css}</style><main style={page}><section style={hero}><div className="float" style={big}>🪐🚀</div><span style={eyebrow}>GRADE 3 SYSTEMS ADVENTURE</span><h1 style={title}>Space Station Sigma is going dark.</h1><p style={lead}>Choose a crew role, repair seven station systems, earn research badges, and restore the final core with Grade 3 math, reading, science, and engineering.</p><div style={roleGrid}>{Object.entries(ROLES).map(([id, item]) => <button key={id} onClick={() => setRole(id as Role)} aria-pressed={role === id} style={{...roleCard,...(role === id ? selectedRole : {})}}><span style={{fontSize:42}}>{item.emoji}</span><strong>{item.name}</strong><small>{item.power}</small><span>{item.text}</span></button>)}</div><button onClick={begin} style={primary}>Board the station →</button><button onClick={() => setSound((v) => !v)} style={secondary}>{sound ? "🔊 Sound on" : "🔇 Sound off"}</button></section></main></GameFrame>;
  if (stage === "checkpoint") return <GameFrame title="Space Station Sigma"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>🛰️✨</div><span style={eyebrow}>SYSTEM CHECKPOINT</span><h1 style={title}>Two station systems restored.</h1><p style={lead}>Energy recharges to at least two. Your research badges stay aboard.</p><div style={badgesRow}>{badges.map((b) => <span key={b} style={badge}>{b}</span>)}</div><button onClick={continueCheckpoint} style={primary}>Enter the next sector →</button></section></main></GameFrame>;
  if (stage === "finish") return <GameFrame title="Space Station Sigma"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>🌌🚀🏆</div><span style={eyebrow}>STATION RESTORED</span><h1 style={title}>{activeProfile.name} saved Space Station Sigma!</h1><p style={lead}>You repaired seven systems using evidence, multiplication, division, life cycles, character motivation, engineering, and two-step problem solving.</p><div style={stats}><strong>✨ {stardust}</strong><strong>🔥 {bestCombo}×</strong><strong>🏅 {badges.length}/7</strong></div><button onClick={replay} style={primary}>Run another mission</button><Link href="/school" style={link}>Return to School Mode</Link></section></main></GameFrame>;

  return <GameFrame title="Space Station Sigma"><style>{css}</style><main style={page}><header style={hud}><strong>{roleInfo.emoji} {roleInfo.name}</strong><div>🔋 {energy} · ✨ {stardust} · 🔥 {combo}× <button onClick={() => setSound((v) => !v)} style={soundButton}>{sound ? "🔊" : "🔇"}</button></div></header><div style={track}><div style={{...fill,width:`${((index + 1) / MISSIONS.length) * 100}%`}} /></div><section style={card}><div style={top}><span style={chip}>{mission.subject}</span><span>{index + 1}/{MISSIONS.length} · {mission.standard}</span></div><div className="float" style={missionEmoji}>{mission.emoji}</div><span style={sector}>{mission.sector}</span><p style={story}>{mission.story}</p><h1 style={question}>{mission.prompt}</h1><div style={choices}>{mission.choices.map((choice) => { const right = choice === mission.answer; const wrongChoice = selected === choice && !right; const reveal = feedback === "explanation" && right; return <button key={choice} data-correct={right ? "true" : "false"} disabled={feedback === "explanation" || wrongChoice} onClick={() => choose(choice)} style={{...choiceButton,...(reveal ? correctStyle : wrongChoice ? wrongStyle : {})}}>{choice}</button>; })}</div><section role="status" style={teaching}><strong>{feedback === "question" ? "MISSION CONTROL" : feedback === "hint" ? "CREW CLUE" : "SYSTEM REPORT"}</strong><p>{feedback === "question" ? "Choose the best repair command." : feedback === "hint" ? mission.hint : selected === mission.answer ? mission.explanation : `The answer is ${mission.answer}. ${mission.explanation}`}</p>{feedback === "question" ? <button onClick={clue} style={secondary}>{clues ? `Use free clue (${clues})` : "Show a clue"}</button> : feedback === "hint" ? <span>Try again. Mission control is standing by.</span> : <button onClick={advance} style={primary}>{index === MISSIONS.length - 1 ? "Restore the final core →" : "Install the repair →"}</button>}</section></section></main></GameFrame>;
}

const css = `@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-9px)}}@keyframes pop{0%{transform:scale(.7);opacity:0}80%{transform:scale(1.08)}100%{transform:scale(1);opacity:1}}.float{animation:float 2s ease-in-out infinite}.pop{animation:pop .5s ease-out both}@media(prefers-reduced-motion:reduce){.float,.pop{animation:none}}`;
const page: React.CSSProperties = { minHeight:"100vh", padding:"20px 14px 70px", background:"radial-gradient(circle at top,#182d56,#0c1323 58%,#080b12)", color:"#fff" };
const hero: React.CSSProperties = { maxWidth:900, margin:"0 auto", padding:"clamp(28px,6vw,58px)", borderRadius:34, textAlign:"center", background:"linear-gradient(145deg,rgba(127,220,255,.14),rgba(198,184,255,.1),#151b2c)", border:"1px solid rgba(127,220,255,.25)" };
const big: React.CSSProperties = { fontSize:"clamp(5rem,16vw,9rem)" }; const eyebrow: React.CSSProperties = { color:"#7fdcff", fontSize:11, fontWeight:950, letterSpacing:".14em" }; const title: React.CSSProperties = { margin:"10px auto", fontSize:"clamp(2.8rem,8vw,5.7rem)", lineHeight:.9 }; const lead: React.CSSProperties = { maxWidth:740, margin:"12px auto 22px", color:"#c9d1df", lineHeight:1.55, fontWeight:700 };
const roleGrid: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))", gap:12, margin:"22px 0" }; const roleCard: React.CSSProperties = { padding:18, borderRadius:22, border:"1px solid #34445f", background:"#101827", color:"#fff", display:"grid", gap:6, cursor:"pointer" }; const selectedRole: React.CSSProperties = { borderColor:"#7fdcff", boxShadow:"0 0 0 3px rgba(127,220,255,.13)" };
const primary: React.CSSProperties = { margin:6, padding:"13px 18px", border:0, borderRadius:999, background:"#d9ff5b", color:"#10131b", fontWeight:950, cursor:"pointer" }; const secondary: React.CSSProperties = { ...primary, background:"#202b43", color:"#fff", border:"1px solid #394966" }; const link: React.CSSProperties = { ...secondary, display:"inline-block", textDecoration:"none" };
const hud: React.CSSProperties = { maxWidth:900, margin:"0 auto 12px", padding:14, borderRadius:20, display:"flex", justifyContent:"space-between", gap:12, flexWrap:"wrap", background:"rgba(16,24,39,.95)", border:"1px solid #2c3b55" }; const soundButton: React.CSSProperties = { border:0, background:"transparent", cursor:"pointer" }; const track: React.CSSProperties = { maxWidth:900, height:10, margin:"0 auto 12px", borderRadius:999, overflow:"hidden", background:"#26344d" }; const fill: React.CSSProperties = { height:"100%", background:"linear-gradient(90deg,#7fdcff,#c6b8ff,#d9ff5b)" };
const card: React.CSSProperties = { maxWidth:900, margin:"0 auto", padding:"clamp(20px,5vw,42px)", borderRadius:30, background:"#151b2c", border:"1px solid rgba(127,220,255,.28)", textAlign:"center" }; const top: React.CSSProperties = { display:"flex", justifyContent:"space-between", gap:10, fontWeight:900 }; const chip: React.CSSProperties = { padding:"6px 9px", borderRadius:999, background:"#7fdcff", color:"#10131b" }; const missionEmoji: React.CSSProperties = { fontSize:"clamp(4rem,14vw,8rem)", marginTop:12 }; const sector: React.CSSProperties = { color:"#d9ff5b", fontSize:11, fontWeight:950, letterSpacing:".14em" }; const story: React.CSSProperties = { color:"#bcc7d8", lineHeight:1.5, fontWeight:700 }; const question: React.CSSProperties = { fontSize:"clamp(2rem,6vw,3.8rem)", lineHeight:.98 };
const choices: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(2,minmax(0,1fr))", gap:10 }; const choiceButton: React.CSSProperties = { minHeight:70, padding:14, borderRadius:18, border:"1px solid #394966", background:"#202b43", color:"#fff", fontWeight:900, cursor:"pointer" }; const correctStyle: React.CSSProperties = { background:"rgba(217,255,91,.14)", borderColor:"#d9ff5b" }; const wrongStyle: React.CSSProperties = { background:"rgba(255,181,191,.12)", borderColor:"#ffb5bf" }; const teaching: React.CSSProperties = { marginTop:16, padding:16, borderRadius:20, background:"#0d1422", border:"1px solid #293853", textAlign:"left" }; const badgesRow: React.CSSProperties = { display:"flex", flexWrap:"wrap", justifyContent:"center", gap:8, margin:18 }; const badge: React.CSSProperties = { padding:"7px 10px", borderRadius:999, background:"#202b43", color:"#d9ff5b", fontWeight:850 }; const stats: React.CSSProperties = { display:"flex", justifyContent:"center", gap:12, flexWrap:"wrap", margin:18 };
