export type EngineeringLevel = "Builder" | "Inventor" | "Systems Thinker";
export type EngineeringSkill = "structures" | "forces" | "materials" | "mechanisms" | "iteration";

export type EngineeringMission = {
  id: string;
  level: EngineeringLevel;
  skill: EngineeringSkill;
  title: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const ENGINEERING_SKILLS: Record<EngineeringSkill, { id: string; label: string }> = {
  structures: { id: "engineering-structures", label: "Structures and stability" },
  forces: { id: "engineering-forces", label: "Forces and motion" },
  materials: { id: "engineering-materials", label: "Materials and properties" },
  mechanisms: { id: "engineering-mechanisms", label: "Mechanisms and simple machines" },
  iteration: { id: "engineering-iteration", label: "Testing and iteration" },
};

export const ENGINEERING_MISSIONS: EngineeringMission[] = [
  { id:"b-wide-base", level:"Builder", skill:"structures", title:"The Wobbly Tower", emoji:"🗼", scene:"A block tower keeps tipping because its bottom is narrower than its top.", prompt:"Which change will most likely make it steadier?", options:["Make the base wider","Add more blocks to the top","Put it on a soft pillow"], answer:"Make the base wider", hint:"Stable structures usually spread their weight over a larger bottom area.", explanation:"A wider base lowers the chance of tipping by supporting the tower over a broader area.", toolId:"wide-base", toolLabel:"Wide Base Builder" },
  { id:"b-triangle", level:"Builder", skill:"structures", title:"The Bendy Bridge", emoji:"🌉", scene:"A bridge made from straight craft sticks bends sideways when pushed.", prompt:"Which shape could brace the sides?", options:["Triangles","Loose circles","One long string"], answer:"Triangles", hint:"Look for a shape that keeps its angles unless its sides change length.", explanation:"Triangles are rigid and help prevent a frame from changing shape.", toolId:"triangle-brace", toolLabel:"Triangle Brace" },
  { id:"b-push-pull", level:"Builder", skill:"forces", title:"Move the Wagon", emoji:"🛒", scene:"A wagon is still. Kai pulls its handle forward.", prompt:"What force starts the wagon moving?", options:["A pull","A shadow","A color"], answer:"A pull", hint:"The handle moves toward Kai.", explanation:"A pull is a force that can change an object's motion.", toolId:"force-finder", toolLabel:"Push-Pull Finder" },
  { id:"b-ramp", level:"Builder", skill:"forces", title:"The Heavy Box", emoji:"📦", scene:"A heavy box must reach a low platform. Lifting it straight up is difficult.", prompt:"What could make the job easier?", options:["Use a ramp","Make the box taller","Turn off the lights"], answer:"Use a ramp", hint:"A longer path can reduce the force needed at one moment.", explanation:"A ramp trades a longer travel distance for less lifting force.", toolId:"ramp-planner", toolLabel:"Ramp Planner" },
  { id:"b-raincoat", level:"Builder", skill:"materials", title:"A Coat for Rain", emoji:"🌧️", scene:"A paper coat tears and becomes soggy in rain.", prompt:"Which material would work better?", options:["Waterproof fabric","Dry tissue paper","Powdered chalk"], answer:"Waterproof fabric", hint:"Choose a material that resists water and can bend.", explanation:"Waterproof fabric combines flexibility with resistance to water.", toolId:"property-picker", toolLabel:"Material Property Picker" },
  { id:"b-window", level:"Builder", skill:"materials", title:"A Window for the Fort", emoji:"🏠", scene:"A fort needs a window that lets light in while blocking wind.", prompt:"Which material best fits both needs?", options:["Clear plastic sheet","Cardboard","Cotton ball"], answer:"Clear plastic sheet", hint:"The window must be transparent and form a barrier.", explanation:"Clear plastic lets light pass while blocking moving air.", toolId:"need-match", toolLabel:"Need-to-Material Matcher" },
  { id:"b-wheel", level:"Builder", skill:"mechanisms", title:"Rolling the Crate", emoji:"⚙️", scene:"A crate is hard to drag across the floor because it rubs against the ground.", prompt:"What should be added underneath?", options:["Wheels","Glue","A blanket on top"], answer:"Wheels", hint:"Rolling usually creates less resistance than sliding.", explanation:"Wheels reduce sliding friction and make the crate easier to move.", toolId:"wheel-helper", toolLabel:"Wheel Helper" },
  { id:"b-lever", level:"Builder", skill:"mechanisms", title:"Lift the Lid", emoji:"🥄", scene:"A tight lid needs to be lifted slightly. A spoon can rest on a small block under its middle.", prompt:"How is the spoon being used?", options:["As a lever","As a wheel","As a battery"], answer:"As a lever", hint:"One point supports the spoon while force on one end moves the other.", explanation:"The spoon pivots on the block, acting as a lever.", toolId:"lever-spotter", toolLabel:"Lever Spotter" },
  { id:"b-test-one", level:"Builder", skill:"iteration", title:"The Paper Airplane", emoji:"✈️", scene:"A paper airplane dives quickly. Mina changes both the wings and the nose before testing again.", prompt:"Why is it hard to know which change helped?", options:["She changed two things at once","The airplane is made of paper","She tested it indoors"], answer:"She changed two things at once", hint:"A fair test changes one important variable at a time.", explanation:"Changing one feature at a time makes cause and effect easier to identify.", toolId:"one-change", toolLabel:"One-Change Tester" },
  { id:"b-failure-clue", level:"Builder", skill:"iteration", title:"The Leaky Boat", emoji:"⛵", scene:"A foil boat sinks because water enters through a small tear.", prompt:"What should the next design address first?", options:["Seal the tear","Add a flag","Paint the outside"], answer:"Seal the tear", hint:"Use the failure as evidence about the most urgent problem.", explanation:"The leak directly caused the sinking, so sealing it is the best first revision.", toolId:"failure-clue", toolLabel:"Failure Clue Finder" },

  { id:"i-load-path", level:"Inventor", skill:"structures", title:"Roof Load Path", emoji:"🏗️", scene:"A model roof rests only on a thin wall in the middle, leaving both edges unsupported.", prompt:"What improvement gives the load a clearer path to the ground?", options:["Add supports beneath the roof edges","Make the roof heavier","Remove the foundation"], answer:"Add supports beneath the roof edges", hint:"Trace where the roof's weight travels.", explanation:"Supports beneath the edges transfer the roof load through columns or walls to the foundation.", toolId:"load-path", toolLabel:"Load Path Tracer" },
  { id:"i-compression", level:"Inventor", skill:"forces", title:"Arch Under Load", emoji:"🧱", scene:"Blocks in an arch press against neighboring blocks when weight is added from above.", prompt:"Which force mainly travels through the arch blocks?", options:["Compression","Magnetism","Buoyancy"], answer:"Compression", hint:"The blocks are being squeezed together.", explanation:"Arches carry much of their load through compression into the supports.", toolId:"force-map", toolLabel:"Force Map" },
  { id:"i-helmet", level:"Inventor", skill:"materials", title:"Safer Helmet Liner", emoji:"⛑️", scene:"A helmet needs an inner layer that absorbs impact by compressing instead of passing all the force to the head.", prompt:"Which property matters most?", options:["Energy absorption","Transparency","Electrical conductivity"], answer:"Energy absorption", hint:"The material should deform and reduce the peak impact force.", explanation:"An energy-absorbing liner spreads stopping over more time and reduces peak force.", toolId:"impact-material", toolLabel:"Impact Material Selector" },
  { id:"i-gears", level:"Inventor", skill:"mechanisms", title:"Two Gears", emoji:"⚙️", scene:"A small gear turns clockwise and meshes directly with a larger gear.", prompt:"Which way does the larger gear turn?", options:["Counterclockwise","Clockwise","It cannot move"], answer:"Counterclockwise", hint:"Meshed gears rotate in opposite directions.", explanation:"Directly meshed gears reverse rotational direction.", toolId:"gear-reader", toolLabel:"Gear Direction Reader" },
  { id:"i-redesign", level:"Inventor", skill:"iteration", title:"The Slow Marble Run", emoji:"🔵", scene:"A marble stops at a nearly flat section. The goal is to keep it moving without changing the marble.", prompt:"What is the most focused redesign?", options:["Increase that section's slope slightly","Rebuild everything","Use a different colored marble"], answer:"Increase that section's slope slightly", hint:"Change the feature most directly connected to the observed failure.", explanation:"A slightly steeper slope increases the component of gravity pulling the marble forward.", toolId:"targeted-redesign", toolLabel:"Targeted Redesign" },

  { id:"s-redundancy", level:"Systems Thinker", skill:"structures", title:"Backup Support", emoji:"🌉", scene:"A walkway relies on one critical cable. If it fails, the entire span collapses.", prompt:"Which redesign improves resilience?", options:["Add independent backup load paths","Use a brighter paint","Make the sign larger"], answer:"Add independent backup load paths", hint:"Resilient systems do not depend on only one critical element.", explanation:"Redundant load paths allow another element to carry load after one component fails.", toolId:"redundancy", toolLabel:"Redundancy Planner" },
  { id:"s-friction-tradeoff", level:"Systems Thinker", skill:"forces", title:"Tire Trade-Off", emoji:"🚲", scene:"A bicycle tire with more grip improves braking but also increases rolling resistance.", prompt:"What kind of engineering decision is this?", options:["A trade-off","A measurement error","A color choice only"], answer:"A trade-off", hint:"One improvement creates a cost somewhere else.", explanation:"Engineering often balances competing performance goals rather than maximizing one property alone.", toolId:"tradeoff-map", toolLabel:"Trade-Off Mapper" },
  { id:"s-composite", level:"Systems Thinker", skill:"materials", title:"Composite Panel", emoji:"🧩", scene:"A panel combines stiff fibers with a lighter material that holds them together.", prompt:"Why combine the materials?", options:["To use complementary properties","To make every property identical","To remove all interfaces"], answer:"To use complementary properties", hint:"One material can provide strength while another provides shape or low mass.", explanation:"Composite materials combine different strengths to create useful overall performance.", toolId:"composite-thinker", toolLabel:"Composite Thinker" },
  { id:"s-feedback", level:"Systems Thinker", skill:"mechanisms", title:"Automatic Greenhouse", emoji:"🌡️", scene:"A temperature sensor turns a fan on when the greenhouse becomes too warm and off after it cools.", prompt:"What system idea is being used?", options:["Feedback control","A fixed decoration","Random motion"], answer:"Feedback control", hint:"The system measures its result and adjusts its action.", explanation:"Feedback control uses sensor information to change the system's behavior.", toolId:"feedback-loop", toolLabel:"Feedback Loop Reader" },
  { id:"s-constraints", level:"Systems Thinker", skill:"iteration", title:"Design Under Constraints", emoji:"📐", scene:"A shelter must be strong, inexpensive, quick to assemble, and made from limited materials.", prompt:"What should the team do first?", options:["Define and rank the constraints","Build the fanciest idea immediately","Ignore cost until the end"], answer:"Define and rank the constraints", hint:"A design cannot be judged well until success and limits are clear.", explanation:"Clear criteria and constraints guide testing and make trade-offs explicit.", toolId:"constraint-map", toolLabel:"Constraint Mapper" },
];

export function engineeringMissionById(id: string): EngineeringMission | null {
  return ENGINEERING_MISSIONS.find((mission) => mission.id === id) ?? null;
}
