import type { ElementaryGrade } from "@/lib/adrian-elementary-scope";

export type StoryChoice = {
  label: string;
  emoji: string;
  outcome: string;
};

export type StoryAnswer = {
  label: string;
  emoji: string;
};

export type StoryChapter = {
  id: string;
  title: string;
  emoji: string;
  standardCode: string;
  standardGoal: string;
  skillId: string;
  skillLabel: string;
  sentences: string[];
  focusWord: { word: string; meaning: string };
  question: string;
  answers: StoryAnswer[];
  answer: string;
  hint: string;
  evidence: string;
  explanation: string;
  routePrompt: string;
  routes: [StoryChoice, StoryChoice];
};

export type StoryPack = {
  grade: ElementaryGrade;
  title: string;
  emoji: string;
  eyebrow: string;
  description: string;
  heroName: string;
  accent: string;
  backdrop: string;
  chapters: StoryChapter[];
};

function answer(label: string, emoji: string): StoryAnswer {
  return { label, emoji };
}

function route(label: string, emoji: string, outcome: string): StoryChoice {
  return { label, emoji, outcome };
}

export const STORY_EXPEDITION_PACKS: Record<ElementaryGrade, StoryPack> = {
  [-1]: {
    grade: -1,
    title: "Critter Story Trail",
    emoji: "🐾📖",
    eyebrow: "TK LISTENING ADVENTURE",
    description: "Listen, notice sounds, remember what happened, and help the critters reach their picnic.",
    heroName: "Pip the Fox",
    accent: "#ffd66b",
    backdrop: "linear-gradient(145deg,#28351f,#18241c 58%,#11151d)",
    chapters: [
      {
        id: "tk-frog-log",
        title: "Frog on a Log",
        emoji: "🐸",
        standardCode: "TK.ELA.2",
        standardGoal: "Notice rhymes and beginning sounds.",
        skillId: "reading-spelling-easy",
        skillLabel: "Letters, sounds, and rhymes",
        sentences: ["A green frog sat on a log.", "The frog saw a dog and gave one happy hop."],
        focusWord: { word: "hop", meaning: "a small jump" },
        question: "Which word rhymes with frog?",
        answers: [answer("Dog", "🐶"), answer("Sun", "☀️"), answer("Bee", "🐝")],
        answer: "Dog",
        hint: "Frog and the answer end with the same sound.",
        evidence: "The story says, “The frog saw a dog.”",
        explanation: "Frog and dog rhyme because they end with the same sound.",
        routePrompt: "How should Pip cross the pond?",
        routes: [route("Hop on lily pads", "🪷", "Pip bounced across the lily pads beside the frog."), route("Ride the log", "🪵", "Pip floated gently across on the frog's log.")],
      },
      {
        id: "tk-acorn-order",
        title: "The Rolling Acorn",
        emoji: "🌰",
        standardCode: "TK.ELA.1",
        standardGoal: "Tell what happened first and next.",
        skillId: "reading-sequencing",
        skillLabel: "Listening and retelling",
        sentences: ["Squirrel found an acorn under a tree.", "She rolled it down a hill, then tucked it into her basket."],
        focusWord: { word: "tucked", meaning: "put something safely into a small place" },
        question: "What did Squirrel do first?",
        answers: [answer("Found an acorn", "🌰"), answer("Used her basket", "🧺"), answer("Ate lunch", "🥪")],
        answer: "Found an acorn",
        hint: "Listen for the first action in the story.",
        evidence: "The first sentence says Squirrel found an acorn.",
        explanation: "Finding the acorn happened before rolling or tucking it away.",
        routePrompt: "Where should the acorn basket go?",
        routes: [route("Under the oak tree", "🌳", "The basket waited in cool shade under the oak."), route("Beside the picnic blanket", "🧺", "The basket became the first treat at the picnic spot.")],
      },
      {
        id: "tk-cloud-detail",
        title: "Cloud Hat",
        emoji: "☁️",
        standardCode: "TK.ELA.1",
        standardGoal: "Remember a useful story detail.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Remembering story details",
        sentences: ["A small cloud covered Bear's blue hat.", "Wind pushed the cloud away, and Bear found his hat again."],
        focusWord: { word: "covered", meaning: "rested over something so it could not be seen" },
        question: "What color was Bear's hat?",
        answers: [answer("Blue", "🔵"), answer("Red", "🔴"), answer("Green", "🟢")],
        answer: "Blue",
        hint: "The color is in the first sentence.",
        evidence: "The story calls it Bear's blue hat.",
        explanation: "Bear's hat was blue.",
        routePrompt: "What should Bear add to the picnic?",
        routes: [route("Blueberry muffins", "🫐", "Bear carried muffins that matched his blue hat."), route("A windy pinwheel", "🎡", "The pinwheel spun whenever the helpful wind returned.")],
      },
      {
        id: "tk-picnic-inference",
        title: "One Empty Seat",
        emoji: "🧺",
        standardCode: "TK.ELA.1",
        standardGoal: "Use story clues to understand what comes next.",
        skillId: "reading-inference",
        skillLabel: "Using story clues",
        sentences: ["The critters put four cups on the blanket, but only three friends had arrived.", "They left one cup beside an empty seat and watched the trail."],
        focusWord: { word: "arrived", meaning: "came to a place" },
        question: "Why did the critters leave one cup by the empty seat?",
        answers: [answer("Another friend was coming", "🐰"), answer("The cup was broken", "💥"), answer("They forgot how to count", "🔢")],
        answer: "Another friend was coming",
        hint: "They watched the trail after setting out the extra cup.",
        evidence: "There were four cups but only three friends, and everyone watched the trail.",
        explanation: "The extra cup and empty seat show that another friend was expected.",
        routePrompt: "Who reaches the picnic last?",
        routes: [route("Bunny with carrots", "🐰", "Bunny hurried in with a crunchy carrot bundle."), route("Duck with berries", "🦆", "Duck waddled in carrying a bowl of bright berries.")],
      },
    ],
  },
  0: {
    grade: 0,
    title: "Moon Garden Readers",
    emoji: "🌙🌱",
    eyebrow: "KINDERGARTEN STORY ADVENTURE",
    description: "Grow a moon garden by listening, reading simple lines, noticing sounds, and putting events in order.",
    heroName: "Milo the Moon Mouse",
    accent: "#8fe8ff",
    backdrop: "linear-gradient(145deg,#172b46,#201d44 58%,#11151d)",
    chapters: [
      {
        id: "k-seed-sound",
        title: "Seed in the Sand",
        emoji: "🌱",
        standardCode: "RF.K.2",
        standardGoal: "Notice beginning sounds in spoken words.",
        skillId: "reading-spelling-easy",
        skillLabel: "Beginning sounds",
        sentences: ["Milo found a silver seed in soft moon sand.", "He set the seed beside a small stone."],
        focusWord: { word: "silver", meaning: "a shiny gray color" },
        question: "Which word begins with the same sound as seed?",
        answers: [answer("Sun", "☀️"), answer("Moon", "🌙"), answer("Rock", "🪨")],
        answer: "Sun",
        hint: "Seed starts with the /s/ sound.",
        evidence: "Seed and sun both begin with the letter sound /s/.",
        explanation: "Seed and sun begin with the same sound.",
        routePrompt: "Where should Milo plant the seed?",
        routes: [route("Near the moon pond", "💧", "Milo planted it where silver water could reach the soil."), route("Beside the star stones", "⭐", "Milo planted it where the star stones glowed at night.")],
      },
      {
        id: "k-water-detail",
        title: "A Cup of Light",
        emoji: "💧",
        standardCode: "RL.K.1",
        standardGoal: "Answer a question using a story detail.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Story details",
        sentences: ["Milo filled a blue cup at the moon pond.", "He poured two small splashes onto the seed."],
        focusWord: { word: "poured", meaning: "made liquid flow from one container to another" },
        question: "What color was Milo's cup?",
        answers: [answer("Blue", "🔵"), answer("Yellow", "🟡"), answer("Pink", "🩷")],
        answer: "Blue",
        hint: "The cup's color appears in the first sentence.",
        evidence: "The passage says Milo filled a blue cup.",
        explanation: "Milo used a blue cup.",
        routePrompt: "What should Milo use next?",
        routes: [route("A tiny watering can", "🪴", "The watering can made a soft silver rain."), route("A spoon for careful drops", "🥄", "Milo counted each bright drop from the spoon.")],
      },
      {
        id: "k-sprout-sequence",
        title: "First, Next, Bloom",
        emoji: "🌼",
        standardCode: "W.K.3",
        standardGoal: "Tell events in the order they happened.",
        skillId: "reading-sequencing",
        skillLabel: "Story order",
        sentences: ["First, a green sprout pushed through the sand.", "Next, two leaves opened.", "Last, a round white flower faced the stars."],
        focusWord: { word: "sprout", meaning: "a new plant beginning to grow" },
        question: "What happened after the sprout appeared?",
        answers: [answer("Two leaves opened", "🍃"), answer("Milo found the seed", "🌱"), answer("The flower closed", "🌑")],
        answer: "Two leaves opened",
        hint: "Look for the sentence beginning with “Next.”",
        evidence: "Next, two leaves opened.",
        explanation: "The leaves opened after the sprout came through the sand.",
        routePrompt: "What should the flower face?",
        routes: [route("The bright Earth", "🌍", "The flower leaned toward the blue-green Earth."), route("The twinkling stars", "✨", "The flower turned toward a field of tiny stars.")],
      },
      {
        id: "k-garden-inference",
        title: "The Sleepy Petals",
        emoji: "🌙",
        standardCode: "RL.K.1",
        standardGoal: "Use a story clue to explain what is happening.",
        skillId: "reading-inference",
        skillLabel: "Using story clues",
        sentences: ["When the sun rose over the Moon's edge, the flower closed its petals.", "When stars returned, the petals opened again."],
        focusWord: { word: "petals", meaning: "the colorful leaf-like parts of a flower" },
        question: "When does the moon flower open?",
        answers: [answer("When stars return", "⭐"), answer("At sunny noon", "☀️"), answer("When Milo leaves", "🐭")],
        answer: "When stars return",
        hint: "The second sentence tells when the petals open.",
        evidence: "When stars returned, the petals opened again.",
        explanation: "The moon flower opens at night when the stars appear.",
        routePrompt: "How should Milo celebrate the garden?",
        routes: [route("Invite the moon moths", "🦋", "Moon moths fluttered around the glowing petals."), route("Hang a star lantern", "🏮", "A small lantern made the garden sparkle even more.")],
      },
    ],
  },
  1: {
    grade: 1,
    title: "Robot Story Builders",
    emoji: "🤖📚",
    eyebrow: "GRADE 1 READING ADVENTURE",
    description: "Read short robot missions, decode useful word patterns, and rebuild the city's story machine.",
    heroName: "Bolt the Book Bot",
    accent: "#9cff88",
    backdrop: "linear-gradient(145deg,#17382d,#173044 58%,#11151d)",
    chapters: [
      {
        id: "g1-map-phonics",
        title: "The Map Chip",
        emoji: "🗺️",
        standardCode: "RF.1.3",
        standardGoal: "Use letter patterns and sounds to read unfamiliar words.",
        skillId: "reading-spelling-medium",
        skillLabel: "Phonics and word patterns",
        sentences: ["Bolt found a map chip beside the repair shop.", "A note on the chip said, “Take the train to the rain tower.”"],
        focusWord: { word: "train", meaning: "a vehicle that travels on tracks" },
        question: "Which word has the same long-a pattern as train?",
        answers: [answer("Rain", "🌧️"), answer("Run", "🏃"), answer("Rock", "🪨")],
        answer: "Rain",
        hint: "Look for another word ending in -ain.",
        evidence: "Train and rain both use the -ain spelling pattern.",
        explanation: "The letters -ain make the long-a sound in train and rain.",
        routePrompt: "How should Bolt reach the tower?",
        routes: [route("Ride the city train", "🚆", "Bolt followed the map while the train zipped through the city."), route("Follow the rail path", "🛤️", "Bolt rolled beside the tracks and checked every sign.")],
      },
      {
        id: "g1-sign-detail",
        title: "The Bent Sign",
        emoji: "🪧",
        standardCode: "RL.1.1",
        standardGoal: "Answer a question with a story detail.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Finding story details",
        sentences: ["A strong wind had bent the tower sign toward the river.", "Bolt used a silver wrench to turn it back toward the station."],
        focusWord: { word: "bent", meaning: "curved or pushed out of its usual shape" },
        question: "What tool did Bolt use?",
        answers: [answer("A silver wrench", "🔧"), answer("A blue brush", "🖌️"), answer("A red rope", "🪢")],
        answer: "A silver wrench",
        hint: "The tool is named in the second sentence.",
        evidence: "Bolt used a silver wrench.",
        explanation: "Bolt repaired the sign with a silver wrench.",
        routePrompt: "Which sign should Bolt repair next?",
        routes: [route("Library arrow", "📚", "Bolt turned the library arrow toward the book plaza."), route("Park arrow", "🌳", "Bolt turned the park arrow toward the green playground.")],
      },
      {
        id: "g1-pages-sequence",
        title: "Pages Out of Order",
        emoji: "📄",
        standardCode: "W.1.3",
        standardGoal: "Put story events in a clear order.",
        skillId: "reading-sequencing",
        skillLabel: "Story sequencing",
        sentences: ["First, Bolt gathered three loose pages.", "Next, he matched their page numbers.", "Then he slid the pages into the story machine."],
        focusWord: { word: "matched", meaning: "put together things that belong together" },
        question: "What did Bolt do before he used the story machine?",
        answers: [answer("Matched the page numbers", "🔢"), answer("Bent the tower sign", "🪧"), answer("Charged his battery", "🔋")],
        answer: "Matched the page numbers",
        hint: "Find the action after “Next” and before “Then.”",
        evidence: "Next, he matched their page numbers. Then he slid the pages into the machine.",
        explanation: "Bolt matched the page numbers before placing the pages into the machine.",
        routePrompt: "Which page should the machine read first?",
        routes: [route("The page with sunrise", "🌅", "The machine began with a bright morning scene."), route("The page with a robot bell", "🔔", "The machine began when a robot bell rang across the city.")],
      },
      {
        id: "g1-machine-inference",
        title: "The Missing Ending",
        emoji: "⚙️",
        standardCode: "RL.1.1",
        standardGoal: "Use story details to explain what probably happened.",
        skillId: "reading-inference",
        skillLabel: "Reading inference",
        sentences: ["The story machine hummed, flashed green, and printed every page except the last one.", "Bolt noticed an empty paper tray and reached for a fresh stack."],
        focusWord: { word: "empty", meaning: "having nothing inside" },
        question: "Why did the machine fail to print the last page?",
        answers: [answer("It ran out of paper", "📄"), answer("Bolt forgot the story", "🤔"), answer("The tower moved", "🏙️")],
        answer: "It ran out of paper",
        hint: "Think about the empty tray and the fresh stack.",
        evidence: "Bolt noticed an empty paper tray and reached for more paper.",
        explanation: "The empty tray shows that the machine had no paper left.",
        routePrompt: "What ending should Bolt print?",
        routes: [route("The city reads together", "👨‍👩‍👧‍👦", "The final page showed every robot sharing one giant book."), route("The machine earns a gold gear", "🏅", "The final page showed a gold gear shining above the repaired machine.")],
      },
    ],
  },
  2: {
    grade: 2,
    title: "Dino Library Detectives",
    emoji: "🦖🔎",
    eyebrow: "GRADE 2 READING ADVENTURE",
    description: "Help a dinosaur detective recover four missing library clues using details, sequence, vocabulary, and inference.",
    heroName: "Dash the Raptor Reader",
    accent: "#ff9bd2",
    backdrop: "linear-gradient(145deg,#3a2439,#243245 58%,#11151d)",
    chapters: [
      {
        id: "g2-footprint-detail",
        title: "Footprints by the Bookshelf",
        emoji: "🐾",
        standardCode: "RL.2.1",
        standardGoal: "Use exact story details to answer a question.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Finding story details",
        sentences: ["Dash arrived before the library opened and found three muddy footprints beside the history shelf.", "A fourth print stopped near a rolling ladder.", "On the floor lay a blue bookmark shaped like a fern."],
        focusWord: { word: "arrived", meaning: "reached a place" },
        question: "What shape was the blue bookmark?",
        answers: [answer("A fern", "🌿"), answer("A moon", "🌙"), answer("A shell", "🐚")],
        answer: "A fern",
        hint: "The bookmark is described in the final sentence.",
        evidence: "The passage says the bookmark was shaped like a fern.",
        explanation: "The blue bookmark had the shape of a fern.",
        routePrompt: "Which clue should Dash inspect first?",
        routes: [route("The muddy footprints", "🐾", "Dash measured each footprint and noticed one tiny claw mark."), route("The fern bookmark", "🌿", "Dash held the bookmark to the light and spotted a faint shelf number.")],
      },
      {
        id: "g2-cart-sequence",
        title: "The Runaway Book Cart",
        emoji: "🛒",
        standardCode: "RL.2.5",
        standardGoal: "Explain how events move from beginning to ending.",
        skillId: "reading-sequencing",
        skillLabel: "Story sequencing",
        sentences: ["First, Dash followed the shelf number to the map room.", "Next, a book cart rolled past him with no one pushing it.", "He chased the cart around two tables and stopped it beside a cracked window.", "Last, he found a strand of red yarn caught on one wheel."],
        focusWord: { word: "strand", meaning: "one thin piece of thread, hair, or fiber" },
        question: "What happened immediately before Dash found the red yarn?",
        answers: [answer("He stopped the cart", "🛒"), answer("He entered the library", "🚪"), answer("He opened a history book", "📘")],
        answer: "He stopped the cart",
        hint: "Look at the action right before the word “Last.”",
        evidence: "Dash stopped the cart beside the window. Last, he found the yarn.",
        explanation: "Stopping the cart happened directly before finding the red yarn.",
        routePrompt: "Where should Dash follow the yarn?",
        routes: [route("Through the cracked window", "🪟", "The yarn continued through the window toward the garden."), route("Back between the map shelves", "🗺️", "A second strand curled between two giant atlas books.")],
      },
      {
        id: "g2-ancient-vocabulary",
        title: "The Ancient Atlas",
        emoji: "🗺️",
        standardCode: "L.2.4",
        standardGoal: "Use the sentence and word parts to figure out a new word.",
        skillId: "reading-vocabulary",
        skillLabel: "Vocabulary in context",
        sentences: ["Dash opened an ancient atlas whose pages were yellow and fragile.", "The cover showed a volcano that had vanished long before the library was built.", "A note inside warned, “Handle this old map with care.”"],
        focusWord: { word: "ancient", meaning: "very old" },
        question: "What does ancient mean in this passage?",
        answers: [answer("Very old", "⌛"), answer("Brightly colored", "🌈"), answer("Hard to carry", "🏋️")],
        answer: "Very old",
        hint: "The pages are yellow, and the note calls the map old.",
        evidence: "The note says “this old map,” which explains ancient.",
        explanation: "Ancient means very old.",
        routePrompt: "How should Dash protect the atlas?",
        routes: [route("Use soft museum gloves", "🧤", "Dash slipped on soft gloves before turning the fragile page."), route("Place it under a clear shield", "🛡️", "A clear shield held the atlas flat without touching it.")],
      },
      {
        id: "g2-culprit-inference",
        title: "The Reader Behind the Curtain",
        emoji: "🎭",
        standardCode: "RL.2.1",
        standardGoal: "Combine clues to explain what the story implies.",
        skillId: "reading-inference",
        skillLabel: "Reading inference",
        sentences: ["Behind the story curtain, Dash heard a quiet sneeze.", "A young triceratops stepped out wearing a red yarn scarf and muddy rain boots.", "She held the missing atlas and explained that she had borrowed it to finish a school project before sunrise."],
        focusWord: { word: "borrowed", meaning: "took something for a while and planned to return it" },
        question: "Who left the muddy footprints and red yarn?",
        answers: [answer("The young triceratops", "🦕"), answer("The librarian", "🧑‍🏫"), answer("Dash", "🦖")],
        answer: "The young triceratops",
        hint: "Match her boots and scarf to the clues from earlier chapters.",
        evidence: "She wore muddy boots and a red yarn scarf, matching both clues.",
        explanation: "The boots explain the footprints, and the scarf explains the yarn.",
        routePrompt: "How should the mystery end?",
        routes: [route("Help finish the project", "✏️", "Dash and the triceratops returned the atlas after completing one final diagram."), route("Create an early-borrowing box", "📦", "The librarian made a safe box for students who needed books before opening time.")],
      },
    ],
  },
  3: {
    grade: 3,
    title: "Orbit Newsroom",
    emoji: "🛰️📰",
    eyebrow: "GRADE 3 READING ADVENTURE",
    description: "Report from a space station by tracing events, checking evidence, and explaining how ideas connect.",
    heroName: "Nova the Junior Reporter",
    accent: "#8dd7ff",
    backdrop: "linear-gradient(145deg,#17253f,#231f4a 58%,#11151d)",
    chapters: [
      {
        id: "g3-signal-detail",
        title: "The Broken Signal",
        emoji: "📡",
        standardCode: "RL.3.1",
        standardGoal: "Refer to a specific part of the text when answering.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Text evidence",
        sentences: ["At 06:10 station time, Nova's news screen went dark during a live weather report.", "The backup screen still showed temperature data, but the camera signal had disappeared.", "Engineer Sol wrote that a loose cable had been found behind Studio Two."],
        focusWord: { word: "backup", meaning: "something kept ready to use if the main one fails" },
        question: "Where was the loose cable found?",
        answers: [answer("Behind Studio Two", "🎥"), answer("Inside the weather dome", "🌦️"), answer("Under the station garden", "🌱")],
        answer: "Behind Studio Two",
        hint: "Use the engineer's written note in the final sentence.",
        evidence: "Engineer Sol wrote that the cable was behind Studio Two.",
        explanation: "The final sentence directly identifies the location.",
        routePrompt: "What should Nova investigate next?",
        routes: [route("Interview Engineer Sol", "🧑‍🔧", "Nova opened her recorder and asked how the cable came loose."), route("Inspect the camera route", "🎥", "Nova followed the camera cable through the station wall panels.")],
      },
      {
        id: "g3-storm-cause",
        title: "Dust Against the Dome",
        emoji: "🌪️",
        standardCode: "RI.3.3",
        standardGoal: "Explain how events and ideas connect.",
        skillId: "reading-sequencing",
        skillLabel: "Cause and sequence",
        sentences: ["Hours before the signal failed, a supply ship had fired its side thrusters near the station.", "The thrusters pushed a cloud of fine moon dust toward the communications dome.", "Dust coated one cooling vent, the camera unit grew hot, and a safety switch shut it down."],
        focusWord: { word: "coated", meaning: "covered something with a thin layer" },
        question: "Which event directly caused the camera to shut down?",
        answers: [answer("The unit grew hot", "🌡️"), answer("Nova began a report", "🎙️"), answer("The supply ship arrived", "🚀")],
        answer: "The unit grew hot",
        hint: "Find the event immediately before the safety switch acted.",
        evidence: "The camera unit grew hot, and a safety switch shut it down.",
        explanation: "Heat triggered the safety switch, which shut down the camera.",
        routePrompt: "Which visual should Nova add to the report?",
        routes: [route("A cause-and-effect chain", "🔗", "Nova drew arrows from thrusters to dust, heat, and shutdown."), route("A station timeline", "⏱️", "Nova arranged each event by the time it happened.")],
      },
      {
        id: "g3-orbit-vocabulary",
        title: "A Precise Headline",
        emoji: "✍️",
        standardCode: "RL.3.1",
        standardGoal: "Use context to understand precise words in a report.",
        skillId: "reading-vocabulary",
        skillLabel: "Vocabulary in context",
        sentences: ["Nova first wrote, “Space Storm Breaks Everything,” but the headline was inaccurate.", "Only one camera had stopped, and the station itself remained safe.", "She revised the headline to say, “Moon Dust Temporarily Disrupts Studio Camera.”"],
        focusWord: { word: "disrupts", meaning: "interrupts the normal way something works" },
        question: "What does disrupts mean in the revised headline?",
        answers: [answer("Interrupts", "⏸️"), answer("Improves", "⬆️"), answer("Copies", "📋")],
        answer: "Interrupts",
        hint: "The camera stopped working for a short time.",
        evidence: "The passage explains that one camera had temporarily stopped.",
        explanation: "Disrupts means interrupts normal operation.",
        routePrompt: "How should Nova publish the correction?",
        routes: [route("Add an editor's note", "📝", "Nova explained why the first headline was too dramatic."), route("Record a short update", "🎙️", "Nova calmly read the accurate headline on air.")],
      },
      {
        id: "g3-conclusion-inference",
        title: "The Responsible Report",
        emoji: "✅",
        standardCode: "RL.3.1",
        standardGoal: "Use several clues to make a supported inference.",
        skillId: "reading-inference",
        skillLabel: "Supported inference",
        sentences: ["Before publishing, Nova checked the engineer's note, the vent sensor log, and the supply ship schedule.", "All three sources matched the same chain of events.", "She removed one exciting sentence because no source could prove it."],
        focusWord: { word: "source", meaning: "a person, record, or text that provides information" },
        question: "What does Nova's final action show about her?",
        answers: [answer("She values accurate evidence", "🔎"), answer("She dislikes space travel", "🚫"), answer("She wants the report to be longer", "📏")],
        answer: "She values accurate evidence",
        hint: "She removed a sentence that no source could prove.",
        evidence: "Nova checked three sources and deleted an unsupported sentence.",
        explanation: "Those actions show that accuracy matters more to her than excitement.",
        routePrompt: "What should Nova earn?",
        routes: [route("Evidence Reporter badge", "🏅", "The newsroom awarded Nova a silver evidence badge."), route("Lead the next investigation", "🧭", "Nova received the map for the station's next mystery.")],
      },
    ],
  },
  4: {
    grade: 4,
    title: "Temple of Two Viewpoints",
    emoji: "🗿📜",
    eyebrow: "GRADE 4 READING ADVENTURE",
    description: "Compare accounts, recognize text structure, and use exact evidence to unlock an ancient reading chamber.",
    heroName: "Kira the Archive Explorer",
    accent: "#ffcb66",
    backdrop: "linear-gradient(145deg,#49311d,#34241e 58%,#11151d)",
    chapters: [
      {
        id: "g4-journal-evidence",
        title: "The Explorer's Journal",
        emoji: "📔",
        standardCode: "RL.4.1",
        standardGoal: "Use details and examples as evidence.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Citing text evidence",
        sentences: ["Kira opened a journal written by explorer Ana Velez in 1912.", "Velez described a stone doorway hidden behind a curtain of vines on the temple's eastern wall.", "She noted that a carved sun above the doorway glowed at dawn but faded by midday.", "Kira copied the date, location, and sun carving into her field notes."],
        focusWord: { word: "eastern", meaning: "located toward the direction where the sun rises" },
        question: "Which detail identifies where the doorway was located?",
        answers: [answer("On the eastern wall", "🧭"), answer("Under the temple floor", "⬇️"), answer("Beside a river dock", "🛶")],
        answer: "On the eastern wall",
        hint: "Look for the sentence describing the vines and wall.",
        evidence: "Velez wrote that the doorway was on the temple's eastern wall.",
        explanation: "The journal gives the exact wall where the doorway was hidden.",
        routePrompt: "Which clue should Kira mark on her map?",
        routes: [route("The eastern wall", "🧭", "Kira drew a bright arrow toward the sunrise side of the temple."), route("The carved sun", "☀️", "Kira sketched the glowing sun symbol beside the doorway mark.")],
      },
      {
        id: "g4-guard-account",
        title: "The Guardian's Account",
        emoji: "🗣️",
        standardCode: "RL.4.1",
        standardGoal: "Compare details from two accounts.",
        skillId: "reading-inference",
        skillLabel: "Comparing viewpoints",
        sentences: ["A village guardian told Kira that the doorway was not hidden by vines when he was young.", "According to him, a storm thirty years earlier had loosened stones and allowed fast-growing vines to spread across the wall.", "He believed the glowing carving was polished crystal, not magic.", "His account added information that did not appear in Velez's older journal."],
        focusWord: { word: "account", meaning: "a description of an event from one person's point of view" },
        question: "How does the guardian's account differ from the journal?",
        answers: [answer("It explains how the vines covered the doorway", "🌿"), answer("It says the doorway is on the west wall", "🌇"), answer("It claims Velez built the temple", "🏗️")],
        answer: "It explains how the vines covered the doorway",
        hint: "The guardian describes a storm that happened after the journal was written.",
        evidence: "He says a later storm loosened stones and helped vines spread across the wall.",
        explanation: "The guardian adds a cause for the vines that the older journal could not include.",
        routePrompt: "Which explanation should Kira test?",
        routes: [route("Storm damage and plant growth", "⛈️", "Kira inspected cracks where rainwater could feed the vines."), route("The polished crystal carving", "💎", "Kira planned to observe how dawn light struck the crystal.")],
      },
      {
        id: "g4-structure",
        title: "The Chamber Instructions",
        emoji: "🧩",
        standardCode: "RI.4.5",
        standardGoal: "Recognize a sequence and problem-solution structure.",
        skillId: "reading-sequencing",
        skillLabel: "Informational text structure",
        sentences: ["The doorway instructions presented a problem: four stone mirrors no longer directed light toward the lock.", "First, an explorer had to clear dust from each mirror.", "Next, the mirrors had to be turned toward the dawn beam.", "Finally, the reflected light would meet at the center seal and release the door."],
        focusWord: { word: "reflected", meaning: "bounced back from a surface" },
        question: "What text structure organizes most of the instructions?",
        answers: [answer("Sequence of steps", "1️⃣"), answer("Compare and contrast", "⚖️"), answer("Question and answer", "❓")],
        answer: "Sequence of steps",
        hint: "Notice the words First, Next, and Finally.",
        evidence: "The instructions use First, Next, and Finally to order actions.",
        explanation: "Those signal words organize the solution as a sequence.",
        routePrompt: "Which mirror should Kira adjust first?",
        routes: [route("The mirror nearest dawn", "🌅", "Kira aligned the eastern mirror with the first ray of sunlight."), route("The dustiest mirror", "🪞", "Kira cleaned the clouded mirror before testing its angle.")],
      },
      {
        id: "g4-theme",
        title: "The Open Archive",
        emoji: "🏛️",
        standardCode: "RL.4.1",
        standardGoal: "Use events and details to explain a theme.",
        skillId: "reading-vocabulary",
        skillLabel: "Theme and precise language",
        sentences: ["When the chamber opened, Kira found shelves of records rather than piles of gold.", "She invited the guardian and village students to examine the archive with her.", "Together they labeled each item, compared old accounts, and stored digital copies for future readers.", "Kira realized the temple protected knowledge so it could be shared, questioned, and preserved."],
        focusWord: { word: "preserved", meaning: "protected so something lasts into the future" },
        question: "Which theme is best supported by the ending?",
        answers: [answer("Knowledge grows when people study and share it", "📚"), answer("Treasure should always remain hidden", "🔒"), answer("Old records are never useful", "🗑️")],
        answer: "Knowledge grows when people study and share it",
        hint: "Think about why Kira invited others and made copies.",
        evidence: "The group studied, labeled, copied, and shared the archive.",
        explanation: "The ending shows that shared investigation helps knowledge survive and grow.",
        routePrompt: "What should the new archive be called?",
        routes: [route("The Dawn Evidence Hall", "🌅", "The hall opened each morning when sunlight reached the crystal seal."), route("The Many Voices Archive", "🗣️", "The name honored the journal, guardian, and future readers.")],
      },
    ],
  },
  5: {
    grade: 5,
    title: "Cipher Chronicle",
    emoji: "🕵️‍♀️📰",
    eyebrow: "GRADE 5 READING ADVENTURE",
    description: "Investigate claims, quotations, evidence quality, and viewpoint inside a futuristic city newsroom.",
    heroName: "Zed the Evidence Analyst",
    accent: "#77f1d0",
    backdrop: "linear-gradient(145deg,#142f32,#17223f 58%,#11151d)",
    chapters: [
      {
        id: "g5-claim",
        title: "The Viral Claim",
        emoji: "📱",
        standardCode: "RI.5.8",
        standardGoal: "Identify a claim and examine the evidence offered for it.",
        skillId: "reading-comprehension-detail",
        skillLabel: "Claims and evidence",
        sentences: ["A popular post claimed that the city's new rooftop gardens had lowered the temperature of every neighborhood by five degrees.", "The post included one photograph of a thermometer beside a single garden.", "It did not identify the date, time, comparison location, or person who recorded the measurement.", "Editor Zed marked the claim as interesting but unverified."],
        focusWord: { word: "unverified", meaning: "not yet checked and confirmed with reliable evidence" },
        question: "What claim did the post make?",
        answers: [answer("Every neighborhood became five degrees cooler", "🌡️"), answer("The gardens produced five kinds of food", "🥬"), answer("Every roof needed a thermometer", "🏠")],
        answer: "Every neighborhood became five degrees cooler",
        hint: "The claim appears in the first sentence.",
        evidence: "The first sentence says every neighborhood was five degrees cooler.",
        explanation: "That broad temperature statement is the post's main claim.",
        routePrompt: "What should Zed examine first?",
        routes: [route("The thermometer photograph", "📷", "Zed enlarged the image and checked what information was visible."), route("The original account", "👤", "Zed searched for the person who first published the measurement.")],
      },
      {
        id: "g5-source",
        title: "Two Sets of Data",
        emoji: "📊",
        standardCode: "RI.5.8",
        standardGoal: "Explain whether reasons and evidence support a claim.",
        skillId: "reading-inference",
        skillLabel: "Evaluating evidence",
        sentences: ["City scientists had measured twelve garden roofs and twelve nearby roofs without gardens over six summer weeks.", "Garden roofs averaged two degrees cooler in the afternoon, but the difference varied with shade, wind, and watering.", "The data supported a smaller, more limited claim than the viral post.", "It did not prove that every neighborhood cooled by exactly five degrees."],
        focusWord: { word: "averaged", meaning: "had a typical value found by combining several measurements" },
        question: "Which conclusion is best supported by the scientists' data?",
        answers: [answer("Garden roofs were usually somewhat cooler", "🌿"), answer("Every neighborhood cooled exactly five degrees", "5️⃣"), answer("Wind never changed roof temperature", "💨")],
        answer: "Garden roofs were usually somewhat cooler",
        hint: "Use the average and the sentence about variation.",
        evidence: "Garden roofs averaged two degrees cooler, with differences caused by several conditions.",
        explanation: "The data supports a modest average effect, not the post's exact universal claim.",
        routePrompt: "How should Zed display the data?",
        routes: [route("A comparison chart", "📊", "Zed placed garden and plain-roof temperatures side by side."), route("A map with conditions", "🗺️", "Zed marked shade, wind, and watering beside each roof.")],
      },
      {
        id: "g5-quote",
        title: "Quote It Accurately",
        emoji: "💬",
        standardCode: "RL.5.1",
        standardGoal: "Quote accurately when explaining a text.",
        skillId: "reading-sequencing",
        skillLabel: "Accurate quotation",
        sentences: ["Lead scientist Dr. Imani wrote, “Rooftop gardens can reduce afternoon surface temperatures, but the size of the effect depends on local conditions.”", "A draft article shortened her words to, “Rooftop gardens reduce temperatures.”", "Zed worried that the shorter sentence removed the important limit about local conditions.", "He restored the complete quotation."],
        focusWord: { word: "conditions", meaning: "the surrounding facts or circumstances that affect what happens" },
        question: "Why did Zed restore the complete quotation?",
        answers: [answer("The full quote included an important limit", "⚖️"), answer("The full quote used fewer words", "✂️"), answer("The scientist asked for a new garden", "🌱")],
        answer: "The full quote included an important limit",
        hint: "Compare the complete quote with the shortened version.",
        evidence: "The full quote says the effect depends on local conditions.",
        explanation: "Removing that limit would make the scientist's conclusion sound broader than it was.",
        routePrompt: "What should accompany the quote?",
        routes: [route("A link to the full study", "🔗", "Readers could inspect the methods and measurements themselves."), route("A plain-language explanation", "🧾", "Zed translated the limit into a short sentence for younger readers.")],
      },
      {
        id: "g5-headline",
        title: "The Honest Headline",
        emoji: "📰",
        standardCode: "RI.5.8",
        standardGoal: "Write a conclusion that matches the strength of the evidence.",
        skillId: "reading-vocabulary",
        skillLabel: "Precise academic language",
        sentences: ["Zed rejected the headline “Gardens Cool the Entire City by Five Degrees.”", "He chose “Study Finds Rooftop Gardens Often Lower Afternoon Roof Temperatures.”", "The new headline described what the study actually measured, used the cautious word often, and avoided claiming that every neighborhood changed.", "The corrected story still celebrated the gardens without exaggerating the evidence."],
        focusWord: { word: "exaggerating", meaning: "making something sound larger, stronger, or more certain than it really is" },
        question: "Why is the second headline more accurate?",
        answers: [answer("It matches the study's limited evidence", "✅"), answer("It promises a larger temperature change", "🔥"), answer("It leaves out the rooftop gardens", "🏢")],
        answer: "It matches the study's limited evidence",
        hint: "Notice the words often and roof temperatures.",
        evidence: "The headline uses “often” and describes the roofs that were actually measured.",
        explanation: "Its wording stays within the data instead of making a universal claim.",
        routePrompt: "How should the Chronicle end the investigation?",
        routes: [route("Publish an evidence checklist", "☑️", "Zed gave readers five questions for checking future viral claims."), route("Invite a student fact-check team", "🧑‍💻", "Young analysts joined the Chronicle's next evidence investigation.")],
      },
    ],
  },
};

export function storyPackForGrade(grade: ElementaryGrade): StoryPack {
  return STORY_EXPEDITION_PACKS[grade];
}
