export type StudyLevel = "Learning Starter" | "Study Builder" | "Learning Strategist";
export type StudySkill = "planning" | "notes" | "retrieval" | "questions" | "feedback";

export type StudyMission = {
  id: string;
  level: StudyLevel;
  skill: StudySkill;
  emoji: string;
  title: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const STUDY_SKILLS: Record<StudySkill, { id: string; label: string }> = {
  planning: { id: "study-planning", label: "Planning and starting work" },
  notes: { id: "study-notes", label: "Useful notes and organization" },
  retrieval: { id: "study-retrieval", label: "Remembering through retrieval" },
  questions: { id: "study-questions", label: "Questions and checking understanding" },
  feedback: { id: "study-feedback", label: "Using feedback and revising" },
};

export const STUDY_MISSIONS: StudyMission[] = [
  { id:"starter-tiny-start", level:"Learning Starter", skill:"planning", emoji:"🚀", title:"The Two-Minute Start", scene:"Maya has a worksheet but keeps sharpening pencils instead of beginning.", prompt:"What is the best first move?", options:["Do the first two minutes of the worksheet","Wait until she feels perfectly ready","Organize every drawer first"], answer:"Do the first two minutes of the worksheet", hint:"Choose the action that makes the task smaller and begins real work.", explanation:"A tiny start lowers the barrier to beginning and often creates momentum.", toolId:"tiny-start", toolLabel:"Tiny Start" },
  { id:"starter-backpack-plan", level:"Learning Starter", skill:"planning", emoji:"🎒", title:"Pack Backward", scene:"Noah needs a library book, lunch, and homework ready before school tomorrow.", prompt:"Which plan is strongest?", options:["List what must be ready and pack it tonight","Hope he remembers in the morning","Put everything somewhere different"], answer:"List what must be ready and pack it tonight", hint:"Plan from the deadline backward.", explanation:"Working backward from morning creates a clear preparation plan.", toolId:"backward-plan", toolLabel:"Backward Planner" },
  { id:"starter-note-keywords", level:"Learning Starter", skill:"notes", emoji:"📝", title:"Catch the Key Ideas", scene:"A teacher explains that plants need light, water, and air. Eli tries to write every spoken word.", prompt:"What should Eli write?", options:["Plants need light, water, air","Every sentence exactly","Nothing because notes are impossible"], answer:"Plants need light, water, air", hint:"Useful notes capture key ideas, not every sound.", explanation:"Short keywords preserve the important information without overloading attention.", toolId:"keyword-notes", toolLabel:"Keyword Catcher" },
  { id:"starter-sort-page", level:"Learning Starter", skill:"notes", emoji:"🗂️", title:"One Page, One Topic", scene:"Lina mixes math steps, spelling words, and science facts on one crowded page.", prompt:"What would help most?", options:["Give each topic its own labeled section","Use smaller handwriting everywhere","Erase all the notes"], answer:"Give each topic its own labeled section", hint:"Organization should make information easier to find later.", explanation:"Clear labels and sections reduce search time and confusion.", toolId:"topic-sections", toolLabel:"Topic Sorter" },
  { id:"starter-close-book", level:"Learning Starter", skill:"retrieval", emoji:"🧠", title:"Close the Book Check", scene:"Sam rereads three animal facts many times but is unsure what he remembers.", prompt:"What should Sam do next?", options:["Close the book and say the facts from memory","Read the same line faster","Highlight every word"], answer:"Close the book and say the facts from memory", hint:"Memory grows when the brain has to retrieve information.", explanation:"Trying to recall without looking reveals what is truly remembered.", toolId:"close-book-check", toolLabel:"Close-Book Check" },
  { id:"starter-explain-it", level:"Learning Starter", skill:"retrieval", emoji:"🗣️", title:"Teach the Toy", scene:"Ava wants to know whether she understands how clouds form.", prompt:"Which test is best?", options:["Explain it to a toy in her own words","Copy the paragraph again","Stare at the diagram"], answer:"Explain it to a toy in her own words", hint:"Choose the method that forces her to build the idea herself.", explanation:"Explaining from memory reveals missing steps and strengthens understanding.", toolId:"teach-back", toolLabel:"Teach-Back" },
  { id:"starter-specific-question", level:"Learning Starter", skill:"questions", emoji:"❓", title:"Ask the Useful Question", scene:"Leo says, 'I do not get math.' The teacher asks what part is confusing.", prompt:"Which question is most useful?", options:["Why do we regroup in this subtraction step?","Can you do everything for me?","Is math always hard?"], answer:"Why do we regroup in this subtraction step?", hint:"A strong question points to one exact place of confusion.", explanation:"Specific questions help a teacher give targeted help.", toolId:"specific-question", toolLabel:"Specific Question" },
  { id:"starter-check-understanding", level:"Learning Starter", skill:"questions", emoji:"🔎", title:"Do I Really Know It?", scene:"Mila finishes reading a page and immediately says she understands it.", prompt:"What is a better check?", options:["Summarize the page without looking","Count how many words were on it","Read only the title again"], answer:"Summarize the page without looking", hint:"Understanding should be demonstrated, not merely felt.", explanation:"A brief summary shows whether the main idea can be reconstructed.", toolId:"understanding-check", toolLabel:"Understanding Check" },
  { id:"starter-one-fix", level:"Learning Starter", skill:"feedback", emoji:"🛠️", title:"Use One Piece of Feedback", scene:"A teacher circles missing punctuation in Jay's paragraph.", prompt:"What should Jay do?", options:["Fix the punctuation and reread the paragraph","Throw the paragraph away","Ignore the circles"], answer:"Fix the punctuation and reread the paragraph", hint:"Feedback becomes useful only when it changes the work.", explanation:"Applying one clear correction is a practical revision step.", toolId:"one-fix", toolLabel:"One-Fix Revision" },
  { id:"starter-mistake-clue", level:"Learning Starter", skill:"feedback", emoji:"🧩", title:"Mistakes Are Clues", scene:"Nora misses three problems that all involve borrowing.", prompt:"What does the pattern suggest?", options:["She should practice the borrowing step","She is bad at all math","She should repeat only easy problems"], answer:"She should practice the borrowing step", hint:"Look for the shared feature across the mistakes.", explanation:"A cluster of similar errors identifies the exact skill needing practice.", toolId:"mistake-pattern", toolLabel:"Mistake Pattern Finder" },
  { id:"builder-spaced-plan", level:"Study Builder", skill:"planning", emoji:"📅", title:"Spread the Practice", scene:"A quiz is Friday. Ben can study forty minutes Thursday or ten minutes on four different days.", prompt:"Which plan is usually stronger?", options:["Ten minutes on four days","All forty minutes Thursday","No practice until the quiz"], answer:"Ten minutes on four days", hint:"Memory benefits when practice is separated by time.", explanation:"Spaced practice creates repeated retrieval opportunities and better long-term retention.", toolId:"spaced-plan", toolLabel:"Spaced Practice Planner" },
  { id:"builder-two-column", level:"Study Builder", skill:"notes", emoji:"📓", title:"Question-and-Answer Notes", scene:"Iris is learning vocabulary and wants notes she can quiz herself with later.", prompt:"Which format is best?", options:["Word or question on one side, meaning on the other","A decorative title only","One long paragraph with no labels"], answer:"Word or question on one side, meaning on the other", hint:"Choose notes that can become a self-test.", explanation:"Two-column notes hide one side and turn review into retrieval practice.", toolId:"two-column-notes", toolLabel:"Two-Column Notes" },
  { id:"builder-interleave", level:"Study Builder", skill:"retrieval", emoji:"🔀", title:"Mix the Problem Types", scene:"Owen can solve addition when every problem looks alike, but gets confused on a mixed quiz.", prompt:"What practice would prepare him better?", options:["Mix addition, subtraction, and word problems","Practice one identical problem repeatedly","Look only at answer keys"], answer:"Mix addition, subtraction, and word problems", hint:"The quiz requires choosing a method, not only repeating one.", explanation:"Interleaving helps learners recognize which strategy fits each problem.", toolId:"mixed-practice", toolLabel:"Mixed Practice" },
  { id:"builder-confidence-check", level:"Study Builder", skill:"questions", emoji:"🎯", title:"Confidence With Evidence", scene:"Priya feels certain about ten answers but has not checked them.", prompt:"What is the best next step?", options:["Mark confidence, then test the answers and compare","Assume confidence proves correctness","Change every answer randomly"], answer:"Mark confidence, then test the answers and compare", hint:"Good learners compare what they feel with what evidence shows.", explanation:"Calibration improves when confidence is checked against actual performance.", toolId:"calibration", toolLabel:"Confidence Calibrator" },
  { id:"strategist-feedback-loop", level:"Learning Strategist", skill:"feedback", emoji:"🔁", title:"Build a Feedback Loop", scene:"A student receives the comment 'Your explanation needs evidence' on several assignments.", prompt:"Which response creates the strongest learning loop?", options:["Add evidence, resubmit or compare, and use a checklist next time","Correct only the grade number","Wait for the same comment again"], answer:"Add evidence, resubmit or compare, and use a checklist next time", hint:"A loop includes action now and a prevention strategy later.", explanation:"Applying feedback, checking the revision, and carrying the lesson forward turns feedback into durable improvement.", toolId:"feedback-loop", toolLabel:"Feedback Loop" }
];

export function studyMissionById(id: string): StudyMission | null {
  return STUDY_MISSIONS.find((mission) => mission.id === id) ?? null;
}
