export type MovementLevel = "Mover" | "Coordinator" | "Movement Strategist";
export type MovementSkill = "balance" | "coordination" | "mobility" | "strength" | "spatial";

export type MovementMission = {
  id: string;
  level: MovementLevel;
  skill: MovementSkill;
  title: string;
  emoji: string;
  seconds: number;
  instruction: string;
  safety: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const MOVEMENT_SKILLS: Record<MovementSkill, { id: string; label: string }> = {
  balance: { id: "movement-balance", label: "Balance and body control" },
  coordination: { id: "movement-coordination", label: "Coordination and rhythm" },
  mobility: { id: "movement-mobility", label: "Mobility and range of motion" },
  strength: { id: "movement-strength", label: "Strength and stability" },
  spatial: { id: "movement-spatial-awareness", label: "Spatial awareness and safe movement" },
};

export const MOVEMENT_MISSIONS: MovementMission[] = [
  { id:"mover-flamingo", level:"Mover", skill:"balance", title:"Flamingo Freeze", emoji:"🦩", seconds:20, instruction:"Stand near a wall. Lift one foot a little and hold still. Switch feet halfway through.", safety:"Keep one hand close to the wall and stop if you feel dizzy.", prompt:"What usually makes balancing easier?", options:["Looking at one steady spot","Closing both eyes","Swinging every limb"], answer:"Looking at one steady spot", hint:"Your eyes can give the brain a stable reference.", explanation:"A steady visual point helps the brain organize balance information.", toolId:"steady-gaze", toolLabel:"Steady Gaze" },
  { id:"mover-line-walk", level:"Mover", skill:"balance", title:"Tape-Line Walk", emoji:"➖", seconds:25, instruction:"Walk heel-to-toe along an imaginary or taped line, then return normally.", safety:"Use a clear floor and keep furniture out of the path.", prompt:"Why should the path be clear first?", options:["To prevent trips","To make the line louder","To make shoes heavier"], answer:"To prevent trips", hint:"Safe movement begins before the first step.", explanation:"Scanning and clearing the path reduces collision and tripping risk.", toolId:"path-check", toolLabel:"Path Check" },
  { id:"mover-cross-crawl", level:"Mover", skill:"coordination", title:"Cross-Crawl March", emoji:"🚶", seconds:30, instruction:"March slowly, touching each hand to the opposite knee.", safety:"Move slowly enough to stay in control.", prompt:"What is the main coordination challenge?", options:["Matching opposite sides","Holding your breath","Moving only one finger"], answer:"Matching opposite sides", hint:"Right hand meets left knee, then switch.", explanation:"Cross-crawl patterns coordinate opposite sides of the body.", toolId:"cross-body-map", toolLabel:"Cross-Body Map" },
  { id:"mover-clap-step", level:"Mover", skill:"coordination", title:"Clap-Step Pattern", emoji:"👏", seconds:25, instruction:"Repeat this pattern: step, step, clap. Keep it even.", safety:"Use small steps in one clear spot.", prompt:"What helps the pattern stay organized?", options:["A steady rhythm","Random speed changes","Looking away from the space"], answer:"A steady rhythm", hint:"The pattern repeats on an even pulse.", explanation:"A steady beat helps sequence movements reliably.", toolId:"movement-beat", toolLabel:"Movement Beat" },
  { id:"mover-reach-circle", level:"Mover", skill:"mobility", title:"Reach the Clock", emoji:"🕒", seconds:30, instruction:"Stand tall and reach gently toward imaginary clock numbers around you without forcing any stretch.", safety:"Move only through a comfortable range and never bounce.", prompt:"What is the safest stretching rule?", options:["Use a comfortable range","Force the farthest reach","Bounce quickly"], answer:"Use a comfortable range", hint:"Stretching should not feel sharp or painful.", explanation:"Controlled movement through a comfortable range supports mobility without forcing tissue.", toolId:"comfortable-range", toolLabel:"Comfortable Range" },
  { id:"mover-chair-sit", level:"Mover", skill:"strength", title:"Slow Chair Stands", emoji:"🪑", seconds:30, instruction:"With a sturdy chair and an adult nearby if needed, stand up and sit down slowly three to five times.", safety:"Use a stable chair that cannot roll.", prompt:"Why move slowly?", options:["To keep control","To make the chair slide","To avoid using muscles"], answer:"To keep control", hint:"Slow movement makes each part easier to manage.", explanation:"Controlled speed helps maintain alignment and stability.", toolId:"slow-control", toolLabel:"Slow Control" },
  { id:"mover-space-bubble", level:"Mover", skill:"spatial", title:"Personal Space Bubble", emoji:"🫧", seconds:25, instruction:"Reach arms around you slowly and notice the space your body needs without touching anything.", safety:"Check all directions before reaching.", prompt:"What is the purpose of the space bubble?", options:["Avoid bumping people and objects","Make the room smaller","Move without looking"], answer:"Avoid bumping people and objects", hint:"It maps the area your body can reach.", explanation:"Knowing your reach helps you move safely around others and objects.", toolId:"space-bubble", toolLabel:"Space Bubble" },
  { id:"coordinator-star-balance", level:"Coordinator", skill:"balance", title:"Star Balance", emoji:"⭐", seconds:35, instruction:"Balance on one foot near a wall and tap the other foot gently forward, sideways, and back.", safety:"Keep taps small and use the wall when needed.", prompt:"What should stay most controlled?", options:["The standing leg and trunk","The room lights","Your breathing speed"], answer:"The standing leg and trunk", hint:"The moving foot explores while the base stays steady.", explanation:"A stable base and trunk allow controlled movement around the body.", toolId:"stable-base", toolLabel:"Stable Base" },
  { id:"coordinator-pattern-switch", level:"Coordinator", skill:"coordination", title:"Pattern Switch", emoji:"🔁", seconds:35, instruction:"Repeat clap, knee tap, clap, shoulder tap. After three rounds, reverse the order.", safety:"Keep the pace slow enough to remember the sequence.", prompt:"What changes when you reverse the pattern?", options:["The movement sequence","The size of the room","The number of shoulders"], answer:"The movement sequence", hint:"Same actions, new order.", explanation:"Reversing a pattern challenges sequencing and motor planning.", toolId:"sequence-switch", toolLabel:"Sequence Switch" },
  { id:"coordinator-lunge-reach", level:"Coordinator", skill:"mobility", title:"Step-and-Reach", emoji:"🌿", seconds:35, instruction:"Take a small step forward, bend gently, and reach arms upward. Return and switch sides.", safety:"Keep the front knee comfortable and the step small.", prompt:"Why use a small controlled step first?", options:["To test the range safely","To stretch as painfully as possible","To remove balance"], answer:"To test the range safely", hint:"Control comes before distance.", explanation:"Starting small lets the body explore mobility while preserving balance and comfort.", toolId:"range-test", toolLabel:"Range Test" },
  { id:"coordinator-wall-push", level:"Coordinator", skill:"strength", title:"Wall Push", emoji:"🧱", seconds:30, instruction:"Place hands on a wall, step back, and perform slow wall push-ups with a straight body line.", safety:"Use a dry, sturdy wall and keep feet planted.", prompt:"What makes the movement easier?", options:["Standing closer to the wall","Moving feet farther away","Using a slippery floor"], answer:"Standing closer to the wall", hint:"A more upright body carries less load through the arms.", explanation:"Changing body angle changes how much force the arms must manage.", toolId:"angle-adjuster", toolLabel:"Angle Adjuster" },
  { id:"coordinator-direction-call", level:"Coordinator", skill:"spatial", title:"Direction Calls", emoji:"🧭", seconds:35, instruction:"Choose a clear spot. Step forward, back, left, or right as someone calls directions, or follow a written sequence.", safety:"Return to center after each small step.", prompt:"What should happen before changing direction?", options:["Check the space","Close your eyes","Jump as far as possible"], answer:"Check the space", hint:"Direction changes can move you toward obstacles.", explanation:"Scanning before moving supports safe spatial planning.", toolId:"scan-then-move", toolLabel:"Scan Then Move" },
  { id:"strategist-eyes-balance", level:"Movement Strategist", skill:"balance", title:"Balance Variables", emoji:"🎛️", seconds:40, instruction:"Near a wall, compare a wide stance and a narrow stance. Notice which feels steadier.", safety:"Do not close your eyes; keep support nearby.", prompt:"Why is a wider stance often steadier?", options:["It creates a larger base of support","It removes gravity","It makes the floor softer"], answer:"It creates a larger base of support", hint:"Think about the area under and between the feet.", explanation:"A larger base of support gives the center of mass more room to remain over the base.", toolId:"base-of-support", toolLabel:"Base of Support" },
  { id:"strategist-dual-pattern", level:"Movement Strategist", skill:"coordination", title:"Dual Pattern", emoji:"🧩", seconds:40, instruction:"Step side-to-side while clapping every second step. Keep both patterns going together.", safety:"Use small steps and reduce speed if the patterns fall apart.", prompt:"What is the best way to learn a difficult combined pattern?", options:["Practice each part, then combine them","Go faster immediately","Change every step randomly"], answer:"Practice each part, then combine them", hint:"Complex skills can be built from smaller pieces.", explanation:"Part practice reduces cognitive load before combining movements.", toolId:"part-to-whole", toolLabel:"Part-to-Whole Practice" },
  { id:"strategist-plan-circuit", level:"Movement Strategist", skill:"strength", title:"Mini Movement Circuit", emoji:"🔄", seconds:45, instruction:"Complete 10 seconds each of chair stands, wall pushes, marching, and quiet breathing.", safety:"Use stable equipment and stop for pain, dizziness, or breathing trouble.", prompt:"Why include different movements in a circuit?", options:["To vary the demands on the body","To make safety checks unnecessary","To avoid rest forever"], answer:"To vary the demands on the body", hint:"Each station asks the body to do something different.", explanation:"A varied circuit can combine strength, coordination, movement, and recovery.", toolId:"balanced-circuit", toolLabel:"Balanced Circuit" },
];

export function movementMissionById(id: string): MovementMission | null {
  return MOVEMENT_MISSIONS.find((mission) => mission.id === id) ?? null;
}
