export type WorldLevel = "Navigator" | "Explorer" | "World Builder";
export type WorldSkill = "map" | "land" | "regions" | "community" | "environment";

export type WorldMission = {
  id: string;
  level: WorldLevel;
  skill: WorldSkill;
  emoji: string;
  place: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  stampId: string;
  stampLabel: string;
};

export const WORLD_SKILLS: Record<WorldSkill, { id: string; label: string }> = {
  map: { id: "geography-map-skills", label: "Map skills and directions" },
  land: { id: "geography-land-water", label: "Landforms and water" },
  regions: { id: "geography-places-regions", label: "Places and regions" },
  community: { id: "geography-communities-culture", label: "Communities and culture" },
  environment: { id: "geography-human-environment", label: "People and environments" },
};

export const WORLD_MISSIONS: WorldMission[] = [
  {
    id: "nav-map-north",
    level: "Navigator",
    skill: "map",
    emoji: "🧭",
    place: "Map Room",
    scene: "The playground is north of the school. The library is east of the school.",
    prompt: "Which direction would you travel from the school to the playground?",
    options: ["North", "East", "South"],
    answer: "North",
    hint: "The first sentence names the playground's direction.",
    explanation: "The playground is north of the school, so you would travel north.",
    stampId: "compass",
    stampLabel: "Compass Keeper",
  },
  {
    id: "nav-map-key",
    level: "Navigator",
    skill: "map",
    emoji: "🗺️",
    place: "Map Room",
    scene: "On a park map, a blue square means restroom, a green tree means picnic area, and a red cross means first aid.",
    prompt: "Which symbol should you look for when someone needs a bandage?",
    options: ["Red cross", "Green tree", "Blue square"],
    answer: "Red cross",
    hint: "Use the map key to match the need with the symbol.",
    explanation: "The key says a red cross marks first aid.",
    stampId: "map-key",
    stampLabel: "Map Key Reader",
  },
  {
    id: "nav-land-island",
    level: "Navigator",
    skill: "land",
    emoji: "🏝️",
    place: "Island Bay",
    scene: "A small piece of land has water on every side.",
    prompt: "What kind of landform is it?",
    options: ["Island", "Valley", "Desert"],
    answer: "Island",
    hint: "Think about land completely surrounded by water.",
    explanation: "An island is land surrounded by water on all sides.",
    stampId: "island",
    stampLabel: "Island Finder",
  },
  {
    id: "nav-land-river",
    level: "Navigator",
    skill: "land",
    emoji: "🏞️",
    place: "River Trail",
    scene: "Water moves downhill in a long channel toward a lake or ocean.",
    prompt: "What is this moving body of water called?",
    options: ["River", "Mountain", "Plain"],
    answer: "River",
    hint: "It flows through a channel and moves downhill.",
    explanation: "A river is flowing water that travels through a channel.",
    stampId: "river",
    stampLabel: "River Tracker",
  },
  {
    id: "nav-regions-continent",
    level: "Navigator",
    skill: "regions",
    emoji: "🌎",
    place: "Planet Deck",
    scene: "Earth's largest land areas are divided into seven enormous regions.",
    prompt: "What are these largest land regions called?",
    options: ["Continents", "Neighborhoods", "Oceans"],
    answer: "Continents",
    hint: "North America, Africa, and Asia are examples.",
    explanation: "Earth's largest land regions are called continents.",
    stampId: "continents",
    stampLabel: "Continent Scout",
  },
  {
    id: "nav-regions-ocean",
    level: "Navigator",
    skill: "regions",
    emoji: "🌊",
    place: "Planet Deck",
    scene: "Most of Earth's surface is covered by one connected body of salty water divided into named areas.",
    prompt: "What are the largest named areas of salty water called?",
    options: ["Oceans", "Rivers", "Ponds"],
    answer: "Oceans",
    hint: "The Pacific and Atlantic are examples.",
    explanation: "The largest named areas of salty water are oceans.",
    stampId: "ocean",
    stampLabel: "Ocean Observer",
  },
  {
    id: "nav-community-services",
    level: "Navigator",
    skill: "community",
    emoji: "🚒",
    place: "Community Square",
    scene: "A neighborhood shares a fire station, library, park, and roads.",
    prompt: "Which place helps people borrow books and learn?",
    options: ["Library", "Fire station", "Road"],
    answer: "Library",
    hint: "Think about where a community keeps books for everyone to use.",
    explanation: "A public library lets community members borrow books and learn.",
    stampId: "community",
    stampLabel: "Community Helper",
  },
  {
    id: "nav-community-tradition",
    level: "Navigator",
    skill: "community",
    emoji: "🥁",
    place: "Festival Street",
    scene: "Families gather each year to cook special foods, play music, and tell stories taught by older relatives.",
    prompt: "What word best describes these repeated community practices?",
    options: ["Traditions", "Directions", "Landforms"],
    answer: "Traditions",
    hint: "These practices are passed from one generation to another.",
    explanation: "Traditions are customs, stories, or activities passed through a community over time.",
    stampId: "tradition",
    stampLabel: "Tradition Listener",
  },
  {
    id: "nav-environment-rain",
    level: "Navigator",
    skill: "environment",
    emoji: "🌧️",
    place: "Rainy Harbor",
    scene: "A town receives rain on many days of the year.",
    prompt: "Which item would help people adapt to the wet weather?",
    options: ["Raincoat", "Snow shovel", "Desert shade cloth"],
    answer: "Raincoat",
    hint: "Choose the item designed to keep water off clothing.",
    explanation: "Raincoats help people stay dry in a rainy climate.",
    stampId: "rain",
    stampLabel: "Weather Adapter",
  },
  {
    id: "nav-environment-bridge",
    level: "Navigator",
    skill: "environment",
    emoji: "🌉",
    place: "Crossing Town",
    scene: "Homes and a school sit on opposite sides of a river.",
    prompt: "What could people build to cross the river safely?",
    options: ["Bridge", "Volcano", "Forest"],
    answer: "Bridge",
    hint: "Think about a structure that connects two sides.",
    explanation: "A bridge lets people and vehicles cross over water safely.",
    stampId: "bridge",
    stampLabel: "Bridge Builder",
  },
  {
    id: "exp-map-route",
    level: "Explorer",
    skill: "map",
    emoji: "🧭",
    place: "Trail Junction",
    scene: "From camp, walk 2 blocks east to the stream, then 1 block north to the lookout.",
    prompt: "Where is the lookout compared with camp?",
    options: ["Northeast", "Northwest", "Southwest"],
    answer: "Northeast",
    hint: "Combine the east movement with the north movement.",
    explanation: "A place that is both east and north of camp is northeast.",
    stampId: "route",
    stampLabel: "Route Planner",
  },
  {
    id: "exp-map-scale",
    level: "Explorer",
    skill: "map",
    emoji: "📏",
    place: "Survey Tent",
    scene: "A map scale says 1 centimeter represents 5 kilometers. Two towns are 3 centimeters apart on the map.",
    prompt: "How far apart are the towns in real life?",
    options: ["15 kilometers", "8 kilometers", "3 kilometers"],
    answer: "15 kilometers",
    hint: "Multiply each map centimeter by 5 kilometers.",
    explanation: "Three centimeters times 5 kilometers per centimeter equals 15 kilometers.",
    stampId: "scale",
    stampLabel: "Scale Solver",
  },
  {
    id: "exp-land-peninsula",
    level: "Explorer",
    skill: "land",
    emoji: "🗾",
    place: "Coastal Point",
    scene: "A piece of land is surrounded by water on three sides but remains connected to a larger land area.",
    prompt: "What landform is described?",
    options: ["Peninsula", "Island", "Canyon"],
    answer: "Peninsula",
    hint: "Unlike an island, it is still attached on one side.",
    explanation: "A peninsula is land surrounded by water on three sides and connected on the fourth.",
    stampId: "peninsula",
    stampLabel: "Coastline Reader",
  },
  {
    id: "exp-land-delta",
    level: "Explorer",
    skill: "land",
    emoji: "🐊",
    place: "River Mouth",
    scene: "Near the ocean, a river slows down and drops soil into branching channels that form new land.",
    prompt: "What feature is forming?",
    options: ["Delta", "Plateau", "Glacier"],
    answer: "Delta",
    hint: "This feature forms where a river enters a larger body of water.",
    explanation: "A delta forms when river sediment builds up near the river's mouth.",
    stampId: "delta",
    stampLabel: "Delta Detective",
  },
  {
    id: "exp-regions-climate",
    level: "Explorer",
    skill: "regions",
    emoji: "🌵",
    place: "Drylands Station",
    scene: "A region receives very little rain, has sparse plants, and experiences large temperature changes.",
    prompt: "Which region best matches this description?",
    options: ["Desert", "Rainforest", "Wetland"],
    answer: "Desert",
    hint: "Focus on the very low rainfall.",
    explanation: "Deserts are regions defined by very little precipitation.",
    stampId: "desert",
    stampLabel: "Desert Researcher",
  },
  {
    id: "exp-regions-rainforest",
    level: "Explorer",
    skill: "regions",
    emoji: "🌴",
    place: "Canopy Camp",
    scene: "A warm region receives heavy rain and supports many layers of dense plant life.",
    prompt: "Which region is being described?",
    options: ["Tropical rainforest", "Tundra", "Grassland"],
    answer: "Tropical rainforest",
    hint: "Look for warmth, heavy rain, and dense plant layers.",
    explanation: "Tropical rainforests are warm, wet regions with dense and diverse vegetation.",
    stampId: "rainforest",
    stampLabel: "Canopy Explorer",
  },
  {
    id: "exp-community-urban-rural",
    level: "Explorer",
    skill: "community",
    emoji: "🏙️",
    place: "Settlement Lab",
    scene: "Place A has tall buildings, many people, buses, and closely spaced homes. Place B has farms, open land, and homes far apart.",
    prompt: "Which description is correct?",
    options: ["A is urban and B is rural", "A is rural and B is urban", "Both are oceans"],
    answer: "A is urban and B is rural",
    hint: "Urban places are densely built; rural places have more open land.",
    explanation: "Place A has urban features, while Place B has rural features.",
    stampId: "settlements",
    stampLabel: "Settlement Spotter",
  },
  {
    id: "exp-community-perspective",
    level: "Explorer",
    skill: "community",
    emoji: "🗣️",
    place: "Story Circle",
    scene: "Two families describe the same neighborhood festival differently because they joined different events and have different memories.",
    prompt: "Why can both accounts be useful?",
    options: ["People can experience the same event from different perspectives", "Only one person can remember anything", "Festivals never really happen"],
    answer: "People can experience the same event from different perspectives",
    hint: "Think about how location and experience shape what someone notices.",
    explanation: "Different perspectives can reveal different parts of the same event.",
    stampId: "perspective",
    stampLabel: "Perspective Collector",
  },
  {
    id: "exp-environment-irrigation",
    level: "Explorer",
    skill: "environment",
    emoji: "💧",
    place: "Dry Valley Farm",
    scene: "Farmers live in a dry valley with a river nearby. Rain alone is not enough for their crops.",
    prompt: "Which adaptation would most directly bring water to the fields?",
    options: ["Irrigation channels", "Taller mountains", "More road signs"],
    answer: "Irrigation channels",
    hint: "Choose the system designed to move water to crops.",
    explanation: "Irrigation carries water from a source such as a river to farmland.",
    stampId: "irrigation",
    stampLabel: "Water Planner",
  },
  {
    id: "exp-environment-harbor",
    level: "Explorer",
    skill: "environment",
    emoji: "⚓",
    place: "Harbor City",
    scene: "A coastal city has a naturally protected bay deep enough for ships.",
    prompt: "Which activity is the location especially suited for?",
    options: ["Shipping and trade", "Growing crops on ice", "Building desert wells"],
    answer: "Shipping and trade",
    hint: "Think about what ships can do in a protected deep-water bay.",
    explanation: "A good natural harbor supports ships, transportation, and trade.",
    stampId: "harbor",
    stampLabel: "Harbor Navigator",
  },
  {
    id: "build-map-coordinates",
    level: "World Builder",
    skill: "map",
    emoji: "🌐",
    place: "Coordinate Lab",
    scene: "Latitude lines measure distance north or south of the equator. Longitude lines measure distance east or west of the prime meridian.",
    prompt: "Which coordinate tells how far north or south a place is?",
    options: ["Latitude", "Longitude", "Elevation"],
    answer: "Latitude",
    hint: "Remember that the equator is the starting line for this coordinate.",
    explanation: "Latitude measures angular distance north or south of the equator.",
    stampId: "coordinates",
    stampLabel: "Coordinate Navigator",
  },
  {
    id: "build-map-contour",
    level: "World Builder",
    skill: "map",
    emoji: "⛰️",
    place: "Topographic Tent",
    scene: "On a topographic map, contour lines connect places of equal elevation. Lines close together show rapid elevation change.",
    prompt: "What do tightly packed contour lines usually indicate?",
    options: ["A steep slope", "Flat ground", "An ocean current"],
    answer: "A steep slope",
    hint: "The elevation changes quickly over a short horizontal distance.",
    explanation: "Closely spaced contour lines show that elevation changes rapidly, which means the slope is steep.",
    stampId: "topographic",
    stampLabel: "Terrain Analyst",
  },
  {
    id: "build-land-watershed",
    level: "World Builder",
    skill: "land",
    emoji: "💦",
    place: "Watershed Ridge",
    scene: "Rain falling on several hills drains into small streams that all join the same river.",
    prompt: "What is the entire land area draining into that river called?",
    options: ["Watershed", "Peninsula", "Time zone"],
    answer: "Watershed",
    hint: "It includes all the land whose water flows toward one shared outlet.",
    explanation: "A watershed is the land area that drains water into a common river, lake, or other outlet.",
    stampId: "watershed",
    stampLabel: "Watershed Watcher",
  },
  {
    id: "build-land-rain-shadow",
    level: "World Builder",
    skill: "land",
    emoji: "🏔️",
    place: "Mountain Weather Post",
    scene: "Moist air rises over a mountain, cools, and drops rain on one side. The air descends drier on the opposite side.",
    prompt: "What is the dry region on the far side often called?",
    options: ["Rain shadow", "River delta", "Coral reef"],
    answer: "Rain shadow",
    hint: "The mountain blocks much of the moisture before air reaches the far side.",
    explanation: "A rain shadow is a dry area on the leeward side of a mountain range.",
    stampId: "rain-shadow",
    stampLabel: "Climate Detective",
  },
  {
    id: "build-regions-density",
    level: "World Builder",
    skill: "regions",
    emoji: "🏘️",
    place: "Population Lab",
    scene: "Region A has 10,000 people living in 10 square kilometers. Region B has 10,000 people living in 100 square kilometers.",
    prompt: "Which region has greater population density?",
    options: ["Region A", "Region B", "They are equal"],
    answer: "Region A",
    hint: "The same number of people are packed into a smaller area.",
    explanation: "Region A has more people per square kilometer, so it has higher population density.",
    stampId: "density",
    stampLabel: "Population Analyst",
  },
  {
    id: "build-regions-functional",
    level: "World Builder",
    skill: "regions",
    emoji: "🚆",
    place: "Metro Network",
    scene: "Several towns are connected to one central city by commuter trains, jobs, shopping, and shared services.",
    prompt: "Why might geographers study these places as one functional region?",
    options: ["They are linked by daily movement and services", "They all have the same weather every day", "They are surrounded by one wall"],
    answer: "They are linked by daily movement and services",
    hint: "A functional region is organized around connections to a central place.",
    explanation: "Transportation, work, and services link the towns and city into a functional region.",
    stampId: "metro",
    stampLabel: "Regional Thinker",
  },
  {
    id: "build-community-source",
    level: "World Builder",
    skill: "community",
    emoji: "📰",
    place: "History Desk",
    scene: "A mayor's speech praises a new dam. A farmer's diary describes losing fields to the reservoir. An engineering report explains how much electricity the dam produces.",
    prompt: "What is the strongest way to understand the dam's impact?",
    options: ["Compare all three sources and their perspectives", "Use only the mayor's speech", "Ignore every source"],
    answer: "Compare all three sources and their perspectives",
    hint: "Each source reveals a different part of the story.",
    explanation: "Comparing multiple sources helps reveal benefits, costs, and differing perspectives.",
    stampId: "sources",
    stampLabel: "Source Investigator",
  },
  {
    id: "build-community-public-space",
    level: "World Builder",
    skill: "community",
    emoji: "🏞️",
    place: "Civic Design Lab",
    scene: "A growing neighborhood has many apartments but no nearby shared outdoor space. Residents include children, older adults, cyclists, and people using wheelchairs.",
    prompt: "Which plan best serves the whole community?",
    options: ["An accessible park with shade, paths, seating, and play areas", "A locked field for one private group", "A parking lot with no walkway"],
    answer: "An accessible park with shade, paths, seating, and play areas",
    hint: "Choose the plan that supports many ages and abilities.",
    explanation: "Inclusive public space should be safe and usable by a wide range of community members.",
    stampId: "civic-design",
    stampLabel: "Civic Designer",
  },
  {
    id: "build-environment-floodplain",
    level: "World Builder",
    skill: "environment",
    emoji: "🌧️",
    place: "River Planning Office",
    scene: "A river regularly spreads onto nearby low land during heavy rain. A city is deciding where to build a hospital.",
    prompt: "Which choice best reduces flood risk?",
    options: ["Build on higher ground outside the floodplain", "Build at the river's lowest bank", "Remove every storm drain"],
    answer: "Build on higher ground outside the floodplain",
    hint: "Critical buildings should avoid land that commonly floods.",
    explanation: "Locating the hospital above and outside the floodplain lowers its exposure to river flooding.",
    stampId: "floodplain",
    stampLabel: "Resilient Planner",
  },
  {
    id: "build-environment-sustainability",
    level: "World Builder",
    skill: "environment",
    emoji: "♻️",
    place: "Island Council",
    scene: "A small island imports fuel and has strong sunlight and steady wind. Leaders want reliable energy with less pollution.",
    prompt: "Which plan best uses the island's local conditions?",
    options: ["Combine solar, wind, storage, and energy conservation", "Burn more imported fuel only", "Turn off all electricity forever"],
    answer: "Combine solar, wind, storage, and energy conservation",
    hint: "Use the abundant local resources while planning for times when the sun or wind is weaker.",
    explanation: "A mixed renewable system with storage and conservation can use local resources while improving reliability.",
    stampId: "sustainability",
    stampLabel: "Sustainable World Builder",
  },
];

export function worldMissionById(id: string): WorldMission | null {
  return WORLD_MISSIONS.find((mission) => mission.id === id) ?? null;
}
