export type EnvironmentLevel = "Nature Helper" | "Eco Explorer" | "Systems Steward";
export type EnvironmentSkill = "ecosystems" | "resources" | "waste" | "energy" | "climate-action";

export type EnvironmentMission = {
  id: string;
  level: EnvironmentLevel;
  skill: EnvironmentSkill;
  emoji: string;
  title: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const ENVIRONMENT_SKILLS: Record<EnvironmentSkill, { id: string; label: string }> = {
  ecosystems: { id: "environment-ecosystems", label: "Ecosystems and living relationships" },
  resources: { id: "environment-resources", label: "Natural resources and conservation" },
  waste: { id: "environment-waste-cycles", label: "Waste, reuse, and material cycles" },
  energy: { id: "environment-energy", label: "Energy choices and efficiency" },
  "climate-action": { id: "environment-climate-action", label: "Weather, climate, and practical action" },
};

export const ENVIRONMENT_MISSIONS: EnvironmentMission[] = [
  { id:"helper-pollinator", level:"Nature Helper", skill:"ecosystems", emoji:"🐝", title:"Flower Visitors", scene:"Bees visit flowers for nectar and carry pollen between plants.", prompt:"Why are bees important to many flowering plants?", options:["They help plants make seeds and fruit","They paint the petals","They keep every insect away"], answer:"They help plants make seeds and fruit", hint:"Think about what pollen helps a flower do next.", explanation:"Pollination helps many plants reproduce and form seeds or fruit.", toolId:"pollinator-connection", toolLabel:"Pollinator Connection" },
  { id:"helper-habitat", level:"Nature Helper", skill:"ecosystems", emoji:"🐸", title:"Pond Home", scene:"A pond gives frogs water, shelter, insects to eat, and places to lay eggs.", prompt:"What makes the pond a habitat?", options:["It provides what the frogs need to live","It is always perfectly clean","Only frogs can use it"], answer:"It provides what the frogs need to live", hint:"A habitat is more than a location.", explanation:"A habitat supplies food, water, shelter, and space for living things.", toolId:"habitat-check", toolLabel:"Habitat Check" },
  { id:"helper-water", level:"Nature Helper", skill:"resources", emoji:"🚰", title:"Running Faucet", scene:"Water keeps flowing while a child brushes teeth.", prompt:"What is the best conservation step?", options:["Turn off the faucet while brushing","Let it run because water returns instantly","Use more water to finish faster"], answer:"Turn off the faucet while brushing", hint:"Save the resource when it is not being used.", explanation:"Turning off unused water reduces waste without changing the brushing task.", toolId:"use-only-what-needed", toolLabel:"Use Only What Is Needed" },
  { id:"helper-lunch", level:"Nature Helper", skill:"waste", emoji:"🥪", title:"Reusable Lunch", scene:"A lunch can be packed with a reusable container or several single-use bags.", prompt:"Which choice usually creates less trash?", options:["The reusable container","The single-use bags","Throwing both away"], answer:"The reusable container", hint:"Think about which item can serve the same job many times.", explanation:"A durable reusable container can replace many disposable bags.", toolId:"reuse-first", toolLabel:"Reuse First" },
  { id:"helper-light", level:"Nature Helper", skill:"energy", emoji:"💡", title:"Empty Room", scene:"The lights are on in an empty room during daylight.", prompt:"What is the best next step?", options:["Turn off the unnecessary lights","Close every curtain and add more lights","Leave them on forever"], answer:"Turn off the unnecessary lights", hint:"Efficiency means getting the needed result with less wasted energy.", explanation:"Turning off unused lighting saves energy without reducing anyone's comfort.", toolId:"energy-off-check", toolLabel:"Energy-Off Check" },

  { id:"explorer-food-web", level:"Eco Explorer", skill:"ecosystems", emoji:"🕸️", title:"Food Web Change", scene:"A wetland loses many insects after a chemical spill. Fish and birds both depend on those insects.", prompt:"What is the most likely result?", options:["Several populations may be affected","Only the insects matter","The food web becomes stronger automatically"], answer:"Several populations may be affected", hint:"Food webs connect more than one species.", explanation:"A decline in one food source can ripple through predators and competitors.", toolId:"ripple-effect", toolLabel:"Ecosystem Ripple Effect" },
  { id:"explorer-groundwater", level:"Eco Explorer", skill:"resources", emoji:"💧", title:"Shared Groundwater", scene:"A town pumps groundwater faster than rain can replace it.", prompt:"What problem can develop?", options:["The water table can fall","The aquifer becomes infinite","Rain stops forever"], answer:"The water table can fall", hint:"Compare the removal rate with the replacement rate.", explanation:"Using groundwater faster than recharge lowers the stored supply.", toolId:"recharge-balance", toolLabel:"Recharge Balance" },
  { id:"explorer-compost", level:"Eco Explorer", skill:"waste", emoji:"🍂", title:"Compost Cycle", scene:"Fruit peels and dry leaves are collected in a compost bin instead of sent to a landfill.", prompt:"What useful change can happen?", options:["They can become soil-like material","They become plastic","They stop decomposing"], answer:"They can become soil-like material", hint:"Decomposers break organic matter into simpler materials.", explanation:"Composting returns nutrients and organic matter to soil.", toolId:"cycle-the-nutrients", toolLabel:"Cycle the Nutrients" },
  { id:"explorer-insulation", level:"Eco Explorer", skill:"energy", emoji:"🏠", title:"Warm House", scene:"A drafty house needs constant heating in winter. Sealing leaks and adding insulation are proposed.", prompt:"Why can that save energy?", options:["Less heat escapes","The heater creates colder air","Insulation makes electricity"], answer:"Less heat escapes", hint:"Efficiency often means reducing unwanted transfer.", explanation:"Insulation and sealing reduce heat loss, so less energy is needed to maintain temperature.", toolId:"efficiency-before-more", toolLabel:"Efficiency Before More" },
  { id:"explorer-weather-climate", level:"Eco Explorer", skill:"climate-action", emoji:"🌦️", title:"One Cold Day", scene:"A city has one unusually cold day during a long warming trend.", prompt:"What is the strongest interpretation?", options:["One day's weather does not erase a long-term climate trend","Climate and weather are identical","The trend must be false"], answer:"One day's weather does not erase a long-term climate trend", hint:"Compare a short event with a long pattern.", explanation:"Weather describes short-term conditions; climate describes patterns over much longer periods.", toolId:"weather-vs-climate", toolLabel:"Weather vs. Climate" },

  { id:"steward-keystone", level:"Systems Steward", skill:"ecosystems", emoji:"🦦", title:"Keystone Species", scene:"Sea otters eat sea urchins. Where otters disappear, urchins can overgraze kelp forests.", prompt:"What does this show?", options:["One species can strongly shape an ecosystem","Every species has exactly the same effect","Predators never help habitats"], answer:"One species can strongly shape an ecosystem", hint:"Trace the indirect effect from otter to urchin to kelp.", explanation:"Some species have outsized effects because their interactions stabilize many others.", toolId:"indirect-effect-map", toolLabel:"Indirect Effect Map" },
  { id:"steward-forest", level:"Systems Steward", skill:"resources", emoji:"🌲", title:"Forest Harvest", scene:"A forest supplies wood, wildlife habitat, water protection, and recreation. A plan maximizes only short-term timber harvest.", prompt:"What is the main systems problem?", options:["It ignores other services and future supply","Wood is never useful","All forests must remain untouched"], answer:"It ignores other services and future supply", hint:"A resource can provide several benefits across time.", explanation:"Sustainable planning weighs multiple ecosystem services and regeneration, not one immediate output.", toolId:"multiple-benefits", toolLabel:"Multiple-Benefit Lens" },
  { id:"steward-life-cycle", level:"Systems Steward", skill:"waste", emoji:"📦", title:"Hidden Product Waste", scene:"Two products look similar, but one uses more raw material, travels farther, and cannot be repaired.", prompt:"Which comparison is most complete?", options:["Compare the whole life cycle","Compare only the store price","Compare only the package color"], answer:"Compare the whole life cycle", hint:"Impacts occur before purchase and after disposal too.", explanation:"Life-cycle thinking includes extraction, production, transport, use, repair, and disposal.", toolId:"life-cycle-lens", toolLabel:"Life-Cycle Lens" },
  { id:"steward-grid", level:"Systems Steward", skill:"energy", emoji:"🔋", title:"Clean Energy Mix", scene:"Solar and wind output change with weather. A community wants reliable low-carbon electricity.", prompt:"Which plan is strongest?", options:["Use a mix of generation, storage, efficiency, and grid planning","Rely on one source with no backup","Ignore demand patterns"], answer:"Use a mix of generation, storage, efficiency, and grid planning", hint:"Reliable systems combine several tools.", explanation:"Diverse generation, storage, efficiency, and flexible demand can work together for reliability.", toolId:"energy-system-mix", toolLabel:"Energy System Mix" },
  { id:"steward-action", level:"Systems Steward", skill:"climate-action", emoji:"🏙️", title:"Cooler Neighborhood", scene:"A neighborhood has little shade and high summer heat. Leaders consider trees, reflective roofs, cooling centers, and emergency alerts.", prompt:"Why is a combined plan useful?", options:["Different actions reduce exposure in different ways","Only one action can ever work","Heat affects every place identically"], answer:"Different actions reduce exposure in different ways", hint:"Think prevention, protection, and emergency response.", explanation:"Layered adaptation addresses heat at building, street, community, and emergency-response levels.", toolId:"layered-action", toolLabel:"Layered Action Plan" },
];

export function environmentMissionById(id: string): EnvironmentMission | null {
  return ENVIRONMENT_MISSIONS.find((mission) => mission.id === id) ?? null;
}
