export type DigitalLevel = "Safe Starter" | "Smart Sharer" | "Digital Detective";
export type DigitalSkill = "privacy" | "security" | "kindness" | "media" | "balance";

export type DigitalScenario = {
  id: string;
  level: DigitalLevel;
  skill: DigitalSkill;
  emoji: string;
  title: string;
  situation: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const DIGITAL_SKILLS: Record<DigitalSkill, { id: string; label: string }> = {
  privacy: { id: "digital-privacy-sharing", label: "Privacy and thoughtful sharing" },
  security: { id: "digital-security-scams", label: "Passwords, scams, and account safety" },
  kindness: { id: "digital-kindness-boundaries", label: "Online kindness and boundaries" },
  media: { id: "digital-media-ai-literacy", label: "Media and AI literacy" },
  balance: { id: "digital-balance-help", label: "Screen balance and getting help" },
};

export const DIGITAL_SCENARIOS: DigitalScenario[] = [
  { id:"starter-photo", level:"Safe Starter", skill:"privacy", emoji:"📸", title:"The Team Photo", situation:"A game asks Kai to post a photo showing the front of his house and street sign.", prompt:"What is the safest choice?", options:["Ask a trusted adult before sharing","Post it because the game asked","Add his school name too"], answer:"Ask a trusted adult before sharing", hint:"Photos can reveal where someone lives.", explanation:"Location clues should stay private unless a trusted adult approves the sharing.", toolId:"pause-before-post", toolLabel:"Pause Before Posting" },
  { id:"starter-password", level:"Safe Starter", skill:"security", emoji:"🔑", title:"Secret Password", situation:"A classmate asks for Mina's game password so they can use her character.", prompt:"What should Mina do?", options:["Keep the password private","Share it with everyone","Write it in a public chat"], answer:"Keep the password private", hint:"A password is like a key to an account.", explanation:"Passwords should stay private, even with friends.", toolId:"password-keeper", toolLabel:"Password Keeper" },
  { id:"starter-chat", level:"Safe Starter", skill:"kindness", emoji:"💬", title:"The Mean Message", situation:"Someone writes, 'You are bad at this game,' in a group chat.", prompt:"What is the best response?", options:["Do not pile on, and tell an adult if it continues","Send a meaner message","Share the message everywhere"], answer:"Do not pile on, and tell an adult if it continues", hint:"Online words can hurt just like spoken words.", explanation:"Refusing to join cruelty and getting help protects the person being targeted.", toolId:"kind-chat", toolLabel:"Kind Chat Choice" },
  { id:"starter-video", level:"Safe Starter", skill:"media", emoji:"🎥", title:"The Talking Dinosaur", situation:"A funny video shows a dinosaur giving today's weather report.", prompt:"What should Leo remember?", options:["Videos can be edited or generated","Everything in a video is real","Dinosaurs now work at weather stations"], answer:"Videos can be edited or generated", hint:"A screen can show things that never happened.", explanation:"Images, audio, and video can be created or changed, so seeing is not always proof.", toolId:"screen-skeptic", toolLabel:"Screen Skeptic" },
  { id:"starter-bedtime", level:"Safe Starter", skill:"balance", emoji:"🌙", title:"One More Level", situation:"It is bedtime, but the game asks Nora to play one more level for a reward.", prompt:"What is the healthiest choice?", options:["Stop and follow the bedtime plan","Keep playing until morning","Hide the device under the pillow"], answer:"Stop and follow the bedtime plan", hint:"Games are designed to make stopping feel difficult.", explanation:"A planned stopping point protects sleep even when a game offers another reward.", toolId:"stop-point", toolLabel:"Healthy Stop Point" },

  { id:"sharer-location", level:"Smart Sharer", skill:"privacy", emoji:"📍", title:"Live Location", situation:"A new online friend asks Adrian to share his live location so they can see if they live nearby.", prompt:"What should Adrian do?", options:["Do not share it and tell a trusted adult","Share it for five minutes","Send his daily schedule instead"], answer:"Do not share it and tell a trusted adult", hint:"Someone online may not be who they claim to be.", explanation:"Live location and routines are sensitive information and should not be shared with online contacts.", toolId:"location-lock", toolLabel:"Location Lock" },
  { id:"sharer-link", level:"Smart Sharer", skill:"security", emoji:"🎁", title:"Free Coins Link", situation:"A message promises free game coins if Sofia clicks a link and signs in immediately.", prompt:"What is the strongest next step?", options:["Close it and check through the official app with an adult","Click quickly before it expires","Reply with her password"], answer:"Close it and check through the official app with an adult", hint:"Urgency and free prizes are common scam signals.", explanation:"Checking through the official app avoids a suspicious link and protects the account.", toolId:"scam-signal", toolLabel:"Scam Signal Spotter" },
  { id:"sharer-screenshot", level:"Smart Sharer", skill:"kindness", emoji:"🖼️", title:"Private Screenshot", situation:"A friend sends Jay a private message about feeling embarrassed. Another child asks Jay to screenshot it for the group.", prompt:"What should Jay do?", options:["Keep it private and support his friend","Share it because screenshots are funny","Post it without the friend's name"], answer:"Keep it private and support his friend", hint:"Removing a name does not always remove the harm.", explanation:"Private conversations should not be redistributed without permission, except when safety requires adult help.", toolId:"consent-before-share", toolLabel:"Consent Before Sharing" },
  { id:"sharer-headline", level:"Smart Sharer", skill:"media", emoji:"📰", title:"The Wild Headline", situation:"A post says, 'Scientists prove homework makes children invisible!' but gives no source.", prompt:"What should Priya do first?", options:["Check reliable sources before believing or sharing","Share it because it is surprising","Assume many likes make it true"], answer:"Check reliable sources before believing or sharing", hint:"A dramatic claim needs strong evidence.", explanation:"Likes and surprise do not prove a claim. Reliable reporting and original evidence matter.", toolId:"source-check", toolLabel:"Source Check" },
  { id:"sharer-autoplay", level:"Smart Sharer", skill:"balance", emoji:"▶️", title:"Autoplay Tunnel", situation:"After one video, autoplay keeps serving new videos even though Mateo planned to stop.", prompt:"What strategy helps most?", options:["Turn off autoplay and use a timer","Trust the app to stop for him","Skip sleep to finish the feed"], answer:"Turn off autoplay and use a timer", hint:"Change the environment, not just willpower.", explanation:"Disabling autoplay and setting an external stopping cue reduces endless continuation.", toolId:"attention-plan", toolLabel:"Attention Plan" },

  { id:"detective-data", level:"Digital Detective", skill:"privacy", emoji:"🧩", title:"The Personality Quiz", situation:"A quiz asks for a birthday, school, pet name, hometown, and parent's first name before revealing a result.", prompt:"Why is this risky?", options:["The answers can expose identity or password-recovery clues","Long quizzes are always illegal","Pet names should never be spoken"], answer:"The answers can expose identity or password-recovery clues", hint:"Several harmless details can become powerful when combined.", explanation:"Personal details can be aggregated to identify someone or guess security answers.", toolId:"data-minimizer", toolLabel:"Data Minimizer" },
  { id:"detective-login", level:"Digital Detective", skill:"security", emoji:"🛡️", title:"Unexpected Login", situation:"An account sends a notice about a login from an unknown device.", prompt:"What is the best response?", options:["Use the official app to change the password and tell an adult","Use the email link without checking","Ignore every security notice"], answer:"Use the official app to change the password and tell an adult", hint:"Respond through a trusted route, not an unexpected link.", explanation:"Opening the official service directly and changing credentials avoids phishing while addressing a possible breach.", toolId:"trusted-route", toolLabel:"Trusted Route Check" },
  { id:"detective-dogpile", level:"Digital Detective", skill:"kindness", emoji:"🧯", title:"The Dogpile", situation:"A creator makes a mistake. Hundreds of people begin insulting the creator and sharing private information.", prompt:"Which response is responsible?", options:["Critique the action without harassment or exposing private information","Join because many people are doing it","Search for the creator's home address"], answer:"Critique the action without harassment or exposing private information", hint:"Accountability does not require humiliation or danger.", explanation:"People can challenge harmful behavior while refusing harassment, threats, or doxxing.", toolId:"accountability-without-harm", toolLabel:"Accountability Without Harm" },
  { id:"detective-ai", level:"Digital Detective", skill:"media", emoji:"🤖", title:"The AI Answer", situation:"An AI assistant gives a confident answer about a science fact but provides no evidence.", prompt:"What should Elena do?", options:["Verify the claim with trustworthy sources","Assume confidence means accuracy","Copy it into a report unchanged"], answer:"Verify the claim with trustworthy sources", hint:"AI can produce fluent mistakes.", explanation:"AI output is a starting point, not proof. Important claims should be checked against reliable evidence.", toolId:"ai-verifier", toolLabel:"AI Answer Verifier" },
  { id:"detective-pressure", level:"Digital Detective", skill:"balance", emoji:"🚨", title:"Keep This Secret", situation:"An online contact pressures Ben to keep their conversations secret from adults and gets angry when Ben logs off.", prompt:"What should Ben do?", options:["Stop contact, save evidence if safe, and tell a trusted adult","Keep the secret to avoid upsetting them","Meet the person alone"], answer:"Stop contact, save evidence if safe, and tell a trusted adult", hint:"Requests for secrecy and isolation are major warning signs.", explanation:"A safe relationship does not demand secrecy from trusted adults or punish someone for leaving.", toolId:"trusted-adult-escalation", toolLabel:"Trusted Adult Escalation" },
];

export function digitalScenarioById(id: string): DigitalScenario | null {
  return DIGITAL_SCENARIOS.find((scenario) => scenario.id === id) ?? null;
}
