export type CivicLevel = "Community Helper" | "Citizen" | "Civic Designer";
export type CivicSkill = "rules" | "services" | "rights" | "decisions" | "information";

export type CivicMission = {
  id: string;
  level: CivicLevel;
  skill: CivicSkill;
  setting: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  cardId: string;
  cardLabel: string;
};

export const CIVIC_SKILLS: Record<CivicSkill, { id: string; label: string }> = {
  rules: { id: "civics-rules-responsibilities", label: "Rules and responsibilities" },
  services: { id: "civics-public-services", label: "Public services and institutions" },
  rights: { id: "civics-rights-fairness", label: "Rights, fairness, and inclusion" },
  decisions: { id: "civics-decision-making", label: "Community decision-making" },
  information: { id: "civics-information-literacy", label: "Civic information literacy" },
};

export const CIVIC_MISSIONS: CivicMission[] = [
  {
    id: "helper-library-voices",
    level: "Community Helper",
    skill: "rules",
    setting: "The Library",
    emoji: "📚",
    scene: "The library asks everyone to use quiet voices near people who are reading.",
    prompt: "What is the main purpose of this rule?",
    options: ["Help everyone read and focus", "Make books heavier", "Stop people from borrowing books"],
    answer: "Help everyone read and focus",
    hint: "Think about what readers need from the room around them.",
    explanation: "Good rules have a purpose. Quiet voices protect everyone's chance to read and concentrate.",
    cardId: "rule-purpose-helper",
    cardLabel: "Rule Purpose Helper",
  },
  {
    id: "helper-playground-responsibility",
    level: "Community Helper",
    skill: "rules",
    setting: "The Playground",
    emoji: "🛝",
    scene: "Children may use the playground equipment. They are also expected to take turns and keep sand out of other children's faces.",
    prompt: "Which choice shows a responsibility?",
    options: ["Taking turns on the slide", "Owning every swing", "Never letting anyone play"],
    answer: "Taking turns on the slide",
    hint: "A responsibility is something a person should do to help shared life work.",
    explanation: "Using the playground is something children may do. Taking turns is a responsibility that helps everyone use it safely.",
    cardId: "responsibility-partner",
    cardLabel: "Responsibility Partner",
  },
  {
    id: "helper-fire-station",
    level: "Community Helper",
    skill: "services",
    setting: "The Fire Station",
    emoji: "🚒",
    scene: "Smoke is coming from a neighborhood building. Trained firefighters bring equipment and help people leave safely.",
    prompt: "What community need does the fire department serve?",
    options: ["Emergency safety", "Selling groceries", "Teaching piano lessons"],
    answer: "Emergency safety",
    hint: "Think about why the firefighters came when there was smoke.",
    explanation: "Fire departments are public-safety services that respond to fires and other emergencies.",
    cardId: "service-spotter",
    cardLabel: "Service Spotter",
  },
  {
    id: "helper-park-cleanup",
    level: "Community Helper",
    skill: "services",
    setting: "The Public Park",
    emoji: "🌳",
    scene: "A city park has paths, trees, benches, and trash cans. Workers repair broken equipment and collect litter.",
    prompt: "Why does the community maintain the park?",
    options: ["So many people can use a safe shared space", "So only one family can enter", "So the trees can attend school"],
    answer: "So many people can use a safe shared space",
    hint: "A public place is meant to serve the community, not only one person.",
    explanation: "Maintaining a public park protects a shared place that many residents can enjoy.",
    cardId: "community-place-helper",
    cardLabel: "Community Place Helper",
  },
  {
    id: "helper-game-turns",
    level: "Community Helper",
    skill: "rights",
    setting: "Game Day",
    emoji: "🎲",
    scene: "Four children want to play a board game, but only one child has been taking every turn.",
    prompt: "Which solution is fairest?",
    options: ["Give each player a turn in order", "Let the loudest child take every turn", "Hide the game"],
    answer: "Give each player a turn in order",
    hint: "Fair does not always mean getting everything. It means everyone is treated by a reasonable rule.",
    explanation: "A turn-taking rule gives each player an equal opportunity to participate.",
    cardId: "fair-turn-finder",
    cardLabel: "Fair Turn Finder",
  },
  {
    id: "helper-ramp-access",
    level: "Community Helper",
    skill: "rights",
    setting: "The Community Center",
    emoji: "♿",
    scene: "The community center entrance has only stairs. A visitor who uses a wheelchair cannot enter independently.",
    prompt: "Which change would make access fairer?",
    options: ["Add a safe ramp or lift", "Add more stairs", "Lock the front door"],
    answer: "Add a safe ramp or lift",
    hint: "Fair access may require removing a barrier that affects some people more than others.",
    explanation: "A ramp or lift removes a physical barrier and gives more people meaningful access to the building.",
    cardId: "access-builder",
    cardLabel: "Access Builder",
  },
  {
    id: "helper-class-choice",
    level: "Community Helper",
    skill: "decisions",
    setting: "Class Choice",
    emoji: "🗳️",
    scene: "The class can choose one read-aloud book. The teacher lets every student hear the choices and cast one vote.",
    prompt: "Why is this process reasonable?",
    options: ["Everyone gets a voice and the votes are counted", "Only the tallest student decides", "The teacher hides the choices"],
    answer: "Everyone gets a voice and the votes are counted",
    hint: "Look for participation and a clear way to reach a result.",
    explanation: "A fair decision process lets people understand the options, participate, and know how the result was chosen.",
    cardId: "voice-listener",
    cardLabel: "Voice Listener",
  },
  {
    id: "helper-tie-vote",
    level: "Community Helper",
    skill: "decisions",
    setting: "A Tie Vote",
    emoji: "🤝",
    scene: "A group has two votes for drawing and two votes for building blocks.",
    prompt: "What is a constructive next step?",
    options: ["Discuss a compromise or use a fair tie-breaker", "Say the group can never decide anything", "Let one person secretly change a vote"],
    answer: "Discuss a compromise or use a fair tie-breaker",
    hint: "A tie means the group needs another fair step, not a hidden trick.",
    explanation: "Groups can handle ties through discussion, compromise, rotation, or an agreed tie-breaking rule.",
    cardId: "tie-breaker-thinker",
    cardLabel: "Tie-Breaker Thinker",
  },
  {
    id: "helper-poster-claim",
    level: "Community Helper",
    skill: "information",
    setting: "The Big Poster",
    emoji: "📣",
    scene: "A poster says, 'Our plan is the best!' but gives no reason or evidence.",
    prompt: "What should you ask next?",
    options: ["What facts or reasons support the claim?", "Is the poster the brightest color?", "Can the words be made larger?"],
    answer: "What facts or reasons support the claim?",
    hint: "A claim is not automatically true just because it is printed boldly.",
    explanation: "Careful citizens ask for reasons and evidence before accepting a claim.",
    cardId: "fact-finder",
    cardLabel: "Fact Finder",
  },
  {
    id: "helper-park-hours-source",
    level: "Community Helper",
    skill: "information",
    setting: "Park Hours",
    emoji: "🕒",
    scene: "One child guesses the park closes at six. The official sign at the gate says it closes at seven.",
    prompt: "Which source is better for checking the closing time?",
    options: ["The official sign", "The child's guess", "A picture of a bicycle"],
    answer: "The official sign",
    hint: "Choose the source created to provide the exact information being asked about.",
    explanation: "The official park sign is intended to communicate current park hours, so it is stronger evidence than a guess.",
    cardId: "source-checker",
    cardLabel: "Source Checker",
  },
  {
    id: "citizen-school-rule-review",
    level: "Citizen",
    skill: "rules",
    setting: "Reviewing a School Rule",
    emoji: "🏫",
    scene: "A school rule says students may never carry water bottles. During hot weather, many students become thirsty outside.",
    prompt: "What is the best civic response?",
    options: ["Review whether the rule still serves safety and student needs", "Assume every old rule is perfect", "Ignore all rules without discussion"],
    answer: "Review whether the rule still serves safety and student needs",
    hint: "Rules should have purposes and can be reviewed when circumstances reveal a problem.",
    explanation: "Responsible communities follow rules while also examining whether those rules remain reasonable and effective.",
    cardId: "rule-reviewer",
    cardLabel: "Rule Reviewer",
  },
  {
    id: "citizen-right-responsibility",
    level: "Citizen",
    skill: "rules",
    setting: "Speaking at a Meeting",
    emoji: "🎤",
    scene: "Residents may speak during public comment. Each speaker receives two minutes so many people can participate.",
    prompt: "Which responsibility supports this right?",
    options: ["Respect the time limit and other speakers", "Interrupt everyone else", "Use every speaker's time"],
    answer: "Respect the time limit and other speakers",
    hint: "Rights often work best when people also respect procedures that protect others' participation.",
    explanation: "The right to speak is paired with a responsibility to follow fair limits that allow others to be heard.",
    cardId: "responsibility-balancer",
    cardLabel: "Responsibility Balancer",
  },
  {
    id: "citizen-public-good",
    level: "Citizen",
    skill: "services",
    setting: "Streetlights and Sidewalks",
    emoji: "💡",
    scene: "A neighborhood considers paying together for safer sidewalks and streetlights that everyone can use.",
    prompt: "Why might this be treated as a public service?",
    options: ["The benefits are shared across the community", "Only one shoe can use a sidewalk", "Streetlights are private toys"],
    answer: "The benefits are shared across the community",
    hint: "A public service often addresses a need shared by many people.",
    explanation: "Sidewalks and streetlights create broad safety and access benefits that are difficult to provide one household at a time.",
    cardId: "public-goods-planner",
    cardLabel: "Public Goods Planner",
  },
  {
    id: "citizen-agency-match",
    level: "Citizen",
    skill: "services",
    setting: "Who Should Help?",
    emoji: "🏢",
    scene: "A broken water main is flooding a street. The library, parks department, and water utility all serve the city in different ways.",
    prompt: "Which institution is most directly responsible?",
    options: ["The water utility", "The library", "The parks department"],
    answer: "The water utility",
    hint: "Match the problem to the institution with the relevant responsibility and expertise.",
    explanation: "A water utility manages water infrastructure, making it the institution best equipped to repair the main.",
    cardId: "service-matchmaker",
    cardLabel: "Service Matchmaker",
  },
  {
    id: "citizen-free-expression",
    level: "Citizen",
    skill: "rights",
    setting: "Different Opinions",
    emoji: "💬",
    scene: "Two students disagree about a new school policy. Both explain their views without threats or personal attacks.",
    prompt: "Which principle does this illustrate?",
    options: ["People can express different views respectfully", "Only one opinion may exist", "Disagreement always requires punishment"],
    answer: "People can express different views respectfully",
    hint: "A community can protect expression without requiring agreement.",
    explanation: "Civic freedom includes room for disagreement, while respectful rules protect everyone's safety and participation.",
    cardId: "rights-protector",
    cardLabel: "Rights Protector",
  },
  {
    id: "citizen-fair-process",
    level: "Citizen",
    skill: "rights",
    setting: "The Missing Equipment",
    emoji: "⚖️",
    scene: "A ball goes missing. One student is blamed immediately, but nobody asks what happened or checks any evidence.",
    prompt: "What would make the process fairer?",
    options: ["Hear the student's account and examine evidence", "Punish first and ask later", "Choose the newest student automatically"],
    answer: "Hear the student's account and examine evidence",
    hint: "A fair process gives people a chance to be heard and uses evidence before deciding.",
    explanation: "Fair procedures reduce arbitrary decisions by requiring notice, a chance to respond, and attention to evidence.",
    cardId: "fair-process-checker",
    cardLabel: "Fair Process Checker",
  },
  {
    id: "citizen-majority-minority",
    level: "Citizen",
    skill: "decisions",
    setting: "The Lunch Vote",
    emoji: "🥗",
    scene: "Most students vote for a meal containing nuts, but several students have serious nut allergies.",
    prompt: "What should decision-makers consider besides the vote total?",
    options: ["Safety and the rights of students in the smaller group", "Only the majority preference", "Whether the menu title rhymes"],
    answer: "Safety and the rights of students in the smaller group",
    hint: "Majority rule does not remove the need to protect basic safety and equal access.",
    explanation: "Democratic decisions count preferences while also respecting rights and preventing serious harm to minorities.",
    cardId: "majority-minority-thinker",
    cardLabel: "Majority-Minority Thinker",
  },
  {
    id: "citizen-budget-choice",
    level: "Citizen",
    skill: "decisions",
    setting: "A Small Community Budget",
    emoji: "💵",
    scene: "A youth council has enough money for either two shaded benches or one large decorative sign. Surveys show many people avoid the park because there is nowhere cool to rest.",
    prompt: "Which choice is best supported by the evidence?",
    options: ["Buy the shaded benches", "Buy the sign because it is larger", "Spend nothing without explaining why"],
    answer: "Buy the shaded benches",
    hint: "Choose the option that responds to the documented community need.",
    explanation: "The survey identifies heat and lack of seating as a barrier, so shaded benches directly address the strongest evidence.",
    cardId: "budget-chooser",
    cardLabel: "Budget Chooser",
  },
  {
    id: "citizen-headline-check",
    level: "Citizen",
    skill: "information",
    setting: "A Surprising Headline",
    emoji: "📰",
    scene: "A headline says, 'Everyone Hates the New Park!' The article reports a survey of only three people standing outside one store.",
    prompt: "What is the main problem with the claim?",
    options: ["The tiny sample does not represent everyone", "The headline has capital letters", "Parks cannot be discussed"],
    answer: "The tiny sample does not represent everyone",
    hint: "Ask who was included and whether the evidence matches the size of the claim.",
    explanation: "A survey of three conveniently chosen people cannot support a claim about everyone in a community.",
    cardId: "claim-checker",
    cardLabel: "Claim Checker",
  },
  {
    id: "citizen-photo-context",
    level: "Citizen",
    skill: "information",
    setting: "The Cropped Photo",
    emoji: "📸",
    scene: "A post shows a close-up of an empty section of a public meeting and claims nobody attended. A wider official photo shows a full audience on the other side of the room.",
    prompt: "What lesson does this provide?",
    options: ["Images need context and can be selectively framed", "Every photograph is false", "Audience size never matters"],
    answer: "Images need context and can be selectively framed",
    hint: "Compare what the close-up excludes with what the wider view reveals.",
    explanation: "A real image can still mislead when cropping removes important context.",
    cardId: "context-seeker",
    cardLabel: "Context Seeker",
  },
  {
    id: "designer-rule-impact",
    level: "Civic Designer",
    skill: "rules",
    setting: "Designing a Curfew Rule",
    emoji: "🌙",
    scene: "A proposed park rule would close all fields at 4 p.m. to reduce evening noise. Youth teams and adults who work late say they would lose nearly all access.",
    prompt: "What should policymakers do before adopting the rule?",
    options: ["Compare noise evidence, affected groups, and less restrictive options", "Adopt it because it is simple", "Ignore the people who use the fields"],
    answer: "Compare noise evidence, affected groups, and less restrictive options",
    hint: "Good rule design examines purpose, impact, evidence, and alternatives.",
    explanation: "A rule should be proportionate to the problem and tested against its effects on different community members.",
    cardId: "rule-impact-auditor",
    cardLabel: "Rule Impact Auditor",
  },
  {
    id: "designer-accountability",
    level: "Civic Designer",
    skill: "rules",
    setting: "A Powerful Committee",
    emoji: "🔍",
    scene: "A committee can spend public money but publishes no meeting notes, reasons, or spending records.",
    prompt: "Which reform most improves accountability?",
    options: ["Publish decisions, reasons, and accessible spending records", "Give the committee more secrecy", "Stop residents from asking questions"],
    answer: "Publish decisions, reasons, and accessible spending records",
    hint: "Accountability requires people to know what was done and why.",
    explanation: "Transparency allows the public and oversight bodies to examine whether power and funds were used properly.",
    cardId: "accountability-builder",
    cardLabel: "Accountability Builder",
  },
  {
    id: "designer-budget-tradeoff",
    level: "Civic Designer",
    skill: "services",
    setting: "The City Budget",
    emoji: "📊",
    scene: "The city can fully fund either a new fountain or repairs to several unsafe pedestrian crossings. Crash reports identify repeated injuries at the crossings.",
    prompt: "Which budget principle best supports prioritizing repairs?",
    options: ["Use evidence to address urgent public risk", "Always choose the newest object", "Spend equally on every possible idea"],
    answer: "Use evidence to address urgent public risk",
    hint: "Public budgets require trade-offs, so evidence and severity matter.",
    explanation: "Repeated injuries indicate a documented safety need that reasonably outranks a decorative project.",
    cardId: "public-budget-analyst",
    cardLabel: "Public Budget Analyst",
  },
  {
    id: "designer-emergency-plan",
    level: "Civic Designer",
    skill: "services",
    setting: "Wildfire Smoke Plan",
    emoji: "🌫️",
    scene: "During smoke emergencies, some residents have air filters and cars while others do not. The city is planning clean-air centers and transportation routes.",
    prompt: "Which plan best supports equitable service?",
    options: ["Place centers across neighborhoods and provide transit access", "Open one center only in the wealthiest area", "Assume every resident can drive"],
    answer: "Place centers across neighborhoods and provide transit access",
    hint: "Equal availability is not meaningful if some people cannot reach the service.",
    explanation: "Equitable emergency planning considers location, transportation, disability, language, and other access barriers.",
    cardId: "emergency-service-planner",
    cardLabel: "Emergency Service Planner",
  },
  {
    id: "designer-rights-conflict",
    level: "Civic Designer",
    skill: "rights",
    setting: "Speech and Safety",
    emoji: "🧭",
    scene: "A public forum protects strong criticism of officials but prohibits direct threats against participants.",
    prompt: "What principle does this balance?",
    options: ["Protect expression while preventing targeted harm", "Ban all disagreement", "Treat criticism as a threat"],
    answer: "Protect expression while preventing targeted harm",
    hint: "Rights can coexist with narrow rules aimed at protecting others from specific harm.",
    explanation: "A community can preserve robust debate while restricting direct threats that undermine safety and participation.",
    cardId: "rights-tradeoff-analyst",
    cardLabel: "Rights Trade-Off Analyst",
  },
  {
    id: "designer-language-access",
    level: "Civic Designer",
    skill: "rights",
    setting: "Emergency Instructions",
    emoji: "🗣️",
    scene: "A city sends evacuation instructions only in one language, although many residents use other languages at home.",
    prompt: "Which improvement best supports equal civic access?",
    options: ["Provide translated and visual instructions through multiple channels", "Use smaller text", "Send fewer warnings"],
    answer: "Provide translated and visual instructions through multiple channels",
    hint: "Access depends on whether people can understand and receive essential information.",
    explanation: "Multilingual, visual, and multi-channel communication helps more residents act on urgent public information.",
    cardId: "inclusion-designer",
    cardLabel: "Inclusion Designer",
  },
  {
    id: "designer-deliberation",
    level: "Civic Designer",
    skill: "decisions",
    setting: "Choosing a Transit Route",
    emoji: "🚌",
    scene: "One route serves more riders, while another reaches a clinic used by fewer residents with limited transportation options.",
    prompt: "What is the strongest decision process?",
    options: ["Compare ridership, access needs, costs, and public testimony", "Choose only the route with the biggest number", "Let the map designer decide alone"],
    answer: "Compare ridership, access needs, costs, and public testimony",
    hint: "Complex public choices often involve several legitimate values, not one number.",
    explanation: "Transparent deliberation considers efficiency, equity, cost, and lived experience before explaining the final trade-off.",
    cardId: "deliberation-facilitator",
    cardLabel: "Deliberation Facilitator",
  },
  {
    id: "designer-pilot-program",
    level: "Civic Designer",
    skill: "decisions",
    setting: "Testing a Street Design",
    emoji: "🚲",
    scene: "Residents disagree about replacing parking spaces with a protected bike lane. The city can test temporary barriers for three months and collect safety and usage data.",
    prompt: "Why might a pilot program help?",
    options: ["It creates evidence before a permanent decision", "It guarantees everyone will agree", "It avoids measuring any result"],
    answer: "It creates evidence before a permanent decision",
    hint: "A pilot is a limited test that can be evaluated and revised.",
    explanation: "A temporary trial allows decision-makers to observe real effects, gather feedback, and adjust before committing permanently.",
    cardId: "policy-pilot-planner",
    cardLabel: "Policy Pilot Planner",
  },
  {
    id: "designer-source-triangulation",
    level: "Civic Designer",
    skill: "information",
    setting: "Checking a Budget Claim",
    emoji: "🧾",
    scene: "A viral post says the library budget doubled. The official budget table, meeting minutes, and an independent local report all show a five-percent increase.",
    prompt: "Which conclusion is best supported?",
    options: ["The viral claim conflicts with multiple stronger sources", "The viral post must win because it spread farther", "Budget records cannot answer budget questions"],
    answer: "The viral claim conflicts with multiple stronger sources",
    hint: "Compare source relevance, independence, and agreement.",
    explanation: "Several relevant sources corroborate a five-percent increase, making the unsupported doubling claim unreliable.",
    cardId: "source-triangulator",
    cardLabel: "Source Triangulator",
  },
  {
    id: "designer-emotional-manipulation",
    level: "Civic Designer",
    skill: "information",
    setting: "The Alarmist Video",
    emoji: "🎥",
    scene: "A video uses frightening music and says a proposal will 'destroy the entire town,' but it never links to the proposal or gives measurable evidence.",
    prompt: "What is the most responsible next step?",
    options: ["Find the original proposal and compare credible evidence", "Share it immediately because it feels urgent", "Assume music proves the claim"],
    answer: "Find the original proposal and compare credible evidence",
    hint: "Strong emotion is a reason to slow down and inspect the underlying source.",
    explanation: "Civic information should be checked against original documents and reliable evidence, especially when emotional framing is intense.",
    cardId: "manipulation-detector",
    cardLabel: "Manipulation Detector",
  },
];

export function civicMissionById(id: string): CivicMission | null {
  return CIVIC_MISSIONS.find((mission) => mission.id === id) ?? null;
}
