export type EconomicsLevel = "Money Explorer" | "Budget Builder" | "Market Thinker";
export type EconomicsSkill = "scarcity" | "budget" | "tradeoffs" | "markets" | "enterprise";

export type EconomicsMission = {
  id: string;
  level: EconomicsLevel;
  skill: EconomicsSkill;
  setting: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const ECONOMICS_SKILLS: Record<EconomicsSkill, { id: string; label: string }> = {
  scarcity: { id: "economics-needs-scarcity", label: "Needs, wants, and scarcity" },
  budget: { id: "economics-budget-saving", label: "Budgeting and saving" },
  tradeoffs: { id: "economics-tradeoffs", label: "Trade-offs and opportunity cost" },
  markets: { id: "economics-markets-prices", label: "Markets, prices, and exchange" },
  enterprise: { id: "economics-work-enterprise", label: "Work, value, and enterprise" },
};

export const ECONOMICS_MISSIONS: EconomicsMission[] = [
  {
    id: "explorer-picnic-needs",
    level: "Money Explorer",
    skill: "scarcity",
    setting: "Packing a Picnic",
    emoji: "🧺",
    scene: "Lena can carry only three things to the park. She chooses water, sandwiches, sunscreen, a toy drum, and a glitter hat.",
    prompt: "Which item is most clearly a need for a sunny picnic?",
    options: ["Water", "Glitter hat", "Toy drum"],
    answer: "Water",
    hint: "A need helps a person stay healthy or safe.",
    explanation: "Water supports health and safety. The hat and drum may be fun, but they are wants in this situation.",
    toolId: "need-want-sorter",
    toolLabel: "Need-and-Want Sorter",
  },
  {
    id: "explorer-one-swing",
    level: "Money Explorer",
    skill: "scarcity",
    setting: "One Swing, Four Children",
    emoji: "🛝",
    scene: "Four children want to use the only working swing at the same time.",
    prompt: "What problem are they facing?",
    options: ["Scarcity", "Unlimited supply", "A missing price tag"],
    answer: "Scarcity",
    hint: "There is less of the thing than people want right now.",
    explanation: "Scarcity means available resources are limited compared with how much people want them.",
    toolId: "scarcity-spotter",
    toolLabel: "Scarcity Spotter",
  },
  {
    id: "explorer-three-coins",
    level: "Money Explorer",
    skill: "budget",
    setting: "Three Coins",
    emoji: "🪙",
    scene: "Noah has three coins. A sticker costs one coin and a small book costs three coins.",
    prompt: "What can Noah buy without spending more than he has?",
    options: ["Either one sticker or one book", "A book and a sticker", "Two books"],
    answer: "Either one sticker or one book",
    hint: "A budget cannot use more coins than are available.",
    explanation: "Noah can afford one book or up to three stickers, but not a book plus another item.",
    toolId: "budget-counter",
    toolLabel: "Budget Counter",
  },
  {
    id: "explorer-saving-jar",
    level: "Money Explorer",
    skill: "budget",
    setting: "The Saving Jar",
    emoji: "🫙",
    scene: "Maya wants a puzzle that costs eight dollars. She has four dollars and earns one dollar each week for watering plants.",
    prompt: "What is a useful plan?",
    options: ["Save four more dollars", "Spend the four dollars now and still expect the puzzle", "Pretend the puzzle costs less"],
    answer: "Save four more dollars",
    hint: "Compare the price with the money Maya already has.",
    explanation: "Maya needs four additional dollars, so saving future earnings moves her toward the goal.",
    toolId: "saving-goal-maker",
    toolLabel: "Saving Goal Maker",
  },
  {
    id: "explorer-library-or-park",
    level: "Money Explorer",
    skill: "tradeoffs",
    setting: "Saturday Choice",
    emoji: "📚",
    scene: "Kai has time for either the library craft hour or a soccer game, but the events happen at the same time.",
    prompt: "What does Kai give up by choosing soccer?",
    options: ["The library craft hour", "All future library visits", "The soccer game"],
    answer: "The library craft hour",
    hint: "The opportunity cost is the next-best choice not taken.",
    explanation: "Choosing soccer means giving up the craft hour that happens at the same time.",
    toolId: "choice-compass",
    toolLabel: "Choice Compass",
  },
  {
    id: "explorer-cookie-choice",
    level: "Money Explorer",
    skill: "tradeoffs",
    setting: "One Last Cookie",
    emoji: "🍪",
    scene: "Ari can eat the final cookie now or save it for lunch tomorrow.",
    prompt: "Which statement describes the trade-off?",
    options: ["Having it now means not having it tomorrow", "Eating it creates another cookie", "Saving it costs no choice"],
    answer: "Having it now means not having it tomorrow",
    hint: "A trade-off means gaining one thing while giving up another.",
    explanation: "The cookie can be used only once, so using it now removes the option to use it tomorrow.",
    toolId: "tradeoff-teller",
    toolLabel: "Trade-Off Teller",
  },
  {
    id: "explorer-lemonade-price",
    level: "Money Explorer",
    skill: "markets",
    setting: "Two Lemonade Stands",
    emoji: "🍋",
    scene: "Two stands sell the same-size lemonade. One charges two dollars and the other charges four dollars.",
    prompt: "What information helps a buyer compare the stands?",
    options: ["Price and quality", "The seller's favorite color", "Which sign has more glitter"],
    answer: "Price and quality",
    hint: "A buyer compares what is received with what must be given up.",
    explanation: "Price matters, but quality, size, and service can also affect value.",
    toolId: "value-comparer",
    toolLabel: "Value Comparer",
  },
  {
    id: "explorer-trading-crayons",
    level: "Money Explorer",
    skill: "markets",
    setting: "Crayon Trade",
    emoji: "🖍️",
    scene: "Iris has two blue crayons and wants red. Ben has two red crayons and wants blue.",
    prompt: "Why might both agree to trade one crayon?",
    options: ["Each values what the other has", "Trading makes every crayon disappear", "A trade must hurt one person"],
    answer: "Each values what the other has",
    hint: "A voluntary trade happens when both expect to be better off.",
    explanation: "Each child has something the other wants, so both can benefit from exchanging.",
    toolId: "exchange-explainer",
    toolLabel: "Exchange Explainer",
  },
  {
    id: "explorer-dog-walking",
    level: "Money Explorer",
    skill: "enterprise",
    setting: "Helpful Work",
    emoji: "🐕",
    scene: "Zoe walks a neighbor's dog while the neighbor is at work. The neighbor pays Zoe five dollars.",
    prompt: "Why is Zoe paid?",
    options: ["She provides a useful service", "Money appears whenever a dog walks", "She owns the sidewalk"],
    answer: "She provides a useful service",
    hint: "Work can create value by solving a problem for someone.",
    explanation: "Zoe earns money because her time and effort provide a service the neighbor values.",
    toolId: "value-creator",
    toolLabel: "Value Creator",
  },
  {
    id: "explorer-bracelet-stand",
    level: "Money Explorer",
    skill: "enterprise",
    setting: "Bracelet Stand",
    emoji: "📿",
    scene: "Sam makes bracelets for one dollar each and sells them for three dollars each.",
    prompt: "Why does Sam need to remember the one-dollar cost?",
    options: ["It affects how much remains after a sale", "Costs never matter", "The selling price must always equal zero"],
    answer: "It affects how much remains after a sale",
    hint: "Revenue is not the same as profit.",
    explanation: "Part of the selling price replaces the cost of materials. What remains after costs is profit.",
    toolId: "cost-counter",
    toolLabel: "Cost Counter",
  },
  {
    id: "builder-cafeteria-scarcity",
    level: "Budget Builder",
    skill: "scarcity",
    setting: "Cafeteria Choices",
    emoji: "🥗",
    scene: "The cafeteria has enough strawberries for only half the lunches today because a delivery was delayed.",
    prompt: "Which response best manages the temporary scarcity?",
    options: ["Offer another fruit and share the strawberries fairly", "Promise unlimited strawberries", "Throw away the other fruit"],
    answer: "Offer another fruit and share the strawberries fairly",
    hint: "A useful response recognizes the limit and considers alternatives.",
    explanation: "Substitutes and fair allocation help manage scarcity without pretending the shortage does not exist.",
    toolId: "scarcity-planner",
    toolLabel: "Scarcity Planner",
  },
  {
    id: "builder-water-use",
    level: "Budget Builder",
    skill: "scarcity",
    setting: "Dry-Season Water",
    emoji: "💧",
    scene: "A town has less stored water than usual. Homes, farms, and firefighters all need water.",
    prompt: "Why must the town prioritize uses?",
    options: ["The resource is limited and needs differ", "Water has no uses", "Every use can receive unlimited water"],
    answer: "The resource is limited and needs differ",
    hint: "Scarcity forces choices among competing uses.",
    explanation: "Limited supply means the town must weigh urgency, safety, and alternatives.",
    toolId: "priority-setter",
    toolLabel: "Priority Setter",
  },
  {
    id: "builder-weekly-budget",
    level: "Budget Builder",
    skill: "budget",
    setting: "A Twelve-Dollar Week",
    emoji: "🧾",
    scene: "Eli has twelve dollars. He wants to save five, buy a four-dollar notebook, and buy a five-dollar snack box.",
    prompt: "What must Eli change to keep the budget balanced?",
    options: ["Remove or reduce one goal by two dollars", "Spend fourteen dollars anyway", "Count the same dollar twice"],
    answer: "Remove or reduce one goal by two dollars",
    hint: "Add the planned amounts and compare them with twelve.",
    explanation: "The plan totals fourteen dollars, so Eli must cut or delay at least two dollars of spending or saving.",
    toolId: "balanced-budget-builder",
    toolLabel: "Balanced Budget Builder",
  },
  {
    id: "builder-emergency-fund",
    level: "Budget Builder",
    skill: "budget",
    setting: "Broken Bicycle Tire",
    emoji: "🚲",
    scene: "Rina saves part of her allowance each month. When her bicycle tire breaks, she uses some savings for the repair.",
    prompt: "What purpose did the savings serve?",
    options: ["An emergency fund for an unexpected cost", "A reason to make the tire break", "A way to avoid all future choices"],
    answer: "An emergency fund for an unexpected cost",
    hint: "Some savings protect against costs that are hard to predict.",
    explanation: "Emergency savings create a cushion for unexpected but important expenses.",
    toolId: "safety-cushion-planner",
    toolLabel: "Safety Cushion Planner",
  },
  {
    id: "builder-game-or-gift",
    level: "Budget Builder",
    skill: "tradeoffs",
    setting: "Game or Gift",
    emoji: "🎁",
    scene: "Nico has twenty dollars. He can buy a game for twenty dollars or buy a ten-dollar birthday gift and keep ten dollars.",
    prompt: "What is the opportunity cost of buying the game?",
    options: ["The gift and the remaining ten dollars", "Nothing, because the game is fun", "Another twenty dollars appears"],
    answer: "The gift and the remaining ten dollars",
    hint: "Name the best alternative bundle Nico gives up.",
    explanation: "Choosing the game means giving up both the gift purchase and the unspent money in the alternative plan.",
    toolId: "opportunity-cost-finder",
    toolLabel: "Opportunity Cost Finder",
  },
  {
    id: "builder-study-time",
    level: "Budget Builder",
    skill: "tradeoffs",
    setting: "One Free Hour",
    emoji: "⏰",
    scene: "Mei has one free hour. She can practice piano, finish a science model, or watch a show.",
    prompt: "Why can the opportunity cost differ from person to person?",
    options: ["People value the alternatives differently", "Time is unlimited", "Every choice has the same value"],
    answer: "People value the alternatives differently",
    hint: "The next-best option depends on the chooser's goals.",
    explanation: "Opportunity cost is the most valued alternative forgone, and preferences can differ.",
    toolId: "goal-tradeoff-analyst",
    toolLabel: "Goal Trade-Off Analyst",
  },
  {
    id: "builder-sold-out-cakes",
    level: "Budget Builder",
    skill: "markets",
    setting: "Sold-Out Cupcakes",
    emoji: "🧁",
    scene: "A bakery sells every cupcake before noon for several days. Many customers still ask for more.",
    prompt: "What signal is the bakery receiving?",
    options: ["Demand is greater than the current supply", "Nobody wants cupcakes", "The price contains no information"],
    answer: "Demand is greater than the current supply",
    hint: "A repeated sellout suggests more buyers want the item than the bakery made.",
    explanation: "The bakery may respond by making more, changing the price, or improving how it rations the limited supply.",
    toolId: "market-signal-reader",
    toolLabel: "Market Signal Reader",
  },
  {
    id: "builder-apple-harvest",
    level: "Budget Builder",
    skill: "markets",
    setting: "A Huge Apple Harvest",
    emoji: "🍎",
    scene: "Farms produce far more apples than usual, while the number of buyers stays about the same.",
    prompt: "What is one likely pressure on apple prices?",
    options: ["Prices may fall", "Prices must become infinite", "Supply no longer matters"],
    answer: "Prices may fall",
    hint: "More supply is competing for roughly the same number of buyers.",
    explanation: "When supply rises without a similar rise in demand, sellers often lower prices to attract buyers.",
    toolId: "supply-demand-reader",
    toolLabel: "Supply-and-Demand Reader",
  },
  {
    id: "builder-lawn-service",
    level: "Budget Builder",
    skill: "enterprise",
    setting: "Neighborhood Lawn Service",
    emoji: "🌱",
    scene: "Tariq notices several neighbors need help pulling weeds. He estimates time, buys gloves, and offers a clear price.",
    prompt: "Which action is entrepreneurial?",
    options: ["Identifying a need and organizing a service", "Waiting for weeds to pay him", "Ignoring all costs"],
    answer: "Identifying a need and organizing a service",
    hint: "Entrepreneurs combine ideas, resources, and effort to create value.",
    explanation: "Tariq spots a problem, plans a service, and takes the risk of offering it.",
    toolId: "opportunity-spotter",
    toolLabel: "Opportunity Spotter",
  },
  {
    id: "builder-profit-reinvestment",
    level: "Budget Builder",
    skill: "enterprise",
    setting: "More Art Prints",
    emoji: "🎨",
    scene: "June earns thirty dollars selling art prints. Paper and ink cost eighteen dollars. She uses six dollars of the remaining money to buy better paper.",
    prompt: "What is June doing with the six dollars?",
    options: ["Reinvesting in the project", "Erasing the original costs", "Creating revenue without sales"],
    answer: "Reinvesting in the project",
    hint: "She uses part of what remains to improve future production.",
    explanation: "Reinvestment uses current earnings to support future quality or growth.",
    toolId: "reinvestment-planner",
    toolLabel: "Reinvestment Planner",
  },
  {
    id: "thinker-scarce-lab-time",
    level: "Market Thinker",
    skill: "scarcity",
    setting: "The Shared Science Lab",
    emoji: "🔬",
    scene: "Three classes need the same laboratory for two available periods. One experiment must happen today, one can use a classroom kit, and one can be delayed without harm.",
    prompt: "Which allocation best reflects opportunity cost and alternatives?",
    options: ["Give the lab to the time-sensitive experiment and use substitutes or delay for the others", "Let the loudest class use both periods", "Cancel every experiment"],
    answer: "Give the lab to the time-sensitive experiment and use substitutes or delay for the others",
    hint: "Use urgency and available substitutes to reduce the cost of the choice.",
    explanation: "Scarce resources are allocated more effectively when decision-makers consider urgency, alternatives, and the cost imposed on each use.",
    toolId: "resource-allocation-analyst",
    toolLabel: "Resource Allocation Analyst",
  },
  {
    id: "thinker-congestion-space",
    level: "Market Thinker",
    skill: "scarcity",
    setting: "Crowded Curb Space",
    emoji: "🚗",
    scene: "Delivery trucks, buses, cyclists, and parked cars all compete for limited curb space on one busy block.",
    prompt: "What makes this an economic problem?",
    options: ["A scarce resource has several valuable uses", "The curb is unlimited", "Only money can be scarce"],
    answer: "A scarce resource has several valuable uses",
    hint: "Economics studies choices involving limited resources, including time and space.",
    explanation: "Curb space is limited, and using it for one purpose prevents simultaneous use for another.",
    toolId: "scarce-space-analyst",
    toolLabel: "Scarce Space Analyst",
  },
  {
    id: "thinker-monthly-plan",
    level: "Market Thinker",
    skill: "budget",
    setting: "A Flexible Monthly Plan",
    emoji: "📊",
    scene: "A student earns sixty dollars monthly. She plans thirty for a long-term goal, twenty for regular expenses, and ten for flexible spending. One month, an essential expense rises by eight dollars.",
    prompt: "Which response keeps the plan balanced without borrowing?",
    options: ["Reduce flexible spending or temporarily adjust saving by eight dollars", "Spend sixty-eight dollars and call it balanced", "Ignore the higher expense"],
    answer: "Reduce flexible spending or temporarily adjust saving by eight dollars",
    hint: "A budget must adapt when one category changes.",
    explanation: "A balanced plan reallocates limited income rather than counting money that is not available.",
    toolId: "adaptive-budget-analyst",
    toolLabel: "Adaptive Budget Analyst",
  },
  {
    id: "thinker-interest-growth",
    level: "Market Thinker",
    skill: "budget",
    setting: "Savings That Earn",
    emoji: "🏦",
    scene: "Two savings accounts are equally safe. One pays no interest. The other pays a small percentage each year and has no fees.",
    prompt: "Why might the interest-paying account better support a long-term goal?",
    options: ["The saved balance can grow over time", "Interest guarantees unlimited wealth", "The account removes every risk in life"],
    answer: "The saved balance can grow over time",
    hint: "Interest is an additional return paid on saved money.",
    explanation: "Interest can help savings compound, although the rate, time, fees, inflation, and access rules still matter.",
    toolId: "long-term-saving-analyst",
    toolLabel: "Long-Term Saving Analyst",
  },
  {
    id: "thinker-training-choice",
    level: "Market Thinker",
    skill: "tradeoffs",
    setting: "Training or Immediate Earnings",
    emoji: "🧰",
    scene: "A teenager can work extra hours this summer or spend part of that time in a free training program that may improve future job skills.",
    prompt: "What is a key trade-off?",
    options: ["Current earnings versus possible future earning ability", "Work has no opportunity cost", "Training guarantees a specific salary"],
    answer: "Current earnings versus possible future earning ability",
    hint: "Compare the immediate benefit with a possible longer-term benefit.",
    explanation: "Choosing training sacrifices some current earnings in exchange for the possibility of stronger future skills and opportunities.",
    toolId: "time-investment-analyst",
    toolLabel: "Time Investment Analyst",
  },
  {
    id: "thinker-sunk-cost",
    level: "Market Thinker",
    skill: "tradeoffs",
    setting: "The Unhelpful Subscription",
    emoji: "📱",
    scene: "Dara paid for a one-year app subscription but no longer uses it. Continuing to spend two hours each week on the app will not recover the payment.",
    prompt: "Which reasoning is strongest?",
    options: ["Decide based on future benefits and costs, not only the money already spent", "Keep using it because past spending must control future time", "The payment can be erased by pretending"],
    answer: "Decide based on future benefits and costs, not only the money already spent",
    hint: "A sunk cost is already paid and cannot be recovered by a new choice.",
    explanation: "Future decisions should focus on future costs and benefits. The past payment is relevant to learning, but it should not force more wasted time.",
    toolId: "sunk-cost-detector",
    toolLabel: "Sunk Cost Detector",
  },
  {
    id: "thinker-bus-pricing",
    level: "Market Thinker",
    skill: "markets",
    setting: "Busy-Hour Bus Seats",
    emoji: "🚌",
    scene: "A private shuttle charges more during the busiest hour and less when many seats would otherwise be empty.",
    prompt: "What is the price change trying to do?",
    options: ["Signal scarcity and shift some riders to less crowded times", "Prove high prices are always fair", "Make the number of seats unlimited"],
    answer: "Signal scarcity and shift some riders to less crowded times",
    hint: "Prices can influence when people choose to use a limited service.",
    explanation: "Variable pricing can ration scarce capacity and encourage schedule changes, though fairness and access still require evaluation.",
    toolId: "price-signal-analyst",
    toolLabel: "Price Signal Analyst",
  },
  {
    id: "thinker-competition-quality",
    level: "Market Thinker",
    skill: "markets",
    setting: "Two Repair Shops",
    emoji: "🔧",
    scene: "A second bicycle repair shop opens nearby. Both shops begin posting clearer prices and offering faster estimates.",
    prompt: "What market force may explain the change?",
    options: ["Competition for customers", "A complete end to scarcity", "A rule that every shop must be identical"],
    answer: "Competition for customers",
    hint: "Each shop now has another seller trying to attract the same buyers.",
    explanation: "Competition can encourage sellers to improve price, quality, information, or service to win customers.",
    toolId: "competition-reader",
    toolLabel: "Competition Reader",
  },
  {
    id: "thinker-productivity-tool",
    level: "Market Thinker",
    skill: "enterprise",
    setting: "A Faster Baking Tool",
    emoji: "🥖",
    scene: "A bakery buys a mixer that lets the same team prepare twice as much dough in an hour with similar quality.",
    prompt: "What changed most directly?",
    options: ["Worker productivity increased", "All ingredients became free", "Demand automatically doubled"],
    answer: "Worker productivity increased",
    hint: "Productivity compares output with the resources or time used.",
    explanation: "The team produces more output per hour, which is an increase in labor productivity.",
    toolId: "productivity-measurer",
    toolLabel: "Productivity Measurer",
  },
  {
    id: "thinker-incentive-side-effect",
    level: "Market Thinker",
    skill: "enterprise",
    setting: "Rewarding Fast Repairs",
    emoji: "🛠️",
    scene: "A company rewards technicians only for the number of repairs completed each day. Repairs become faster, but return visits for unfinished problems rise.",
    prompt: "What lesson does this show about incentives?",
    options: ["People may optimize the measured target while neglecting quality", "Rewards never affect behavior", "Faster work always improves every outcome"],
    answer: "People may optimize the measured target while neglecting quality",
    hint: "Compare the rewarded number with the outcome customers actually need.",
    explanation: "An incentive can change behavior in unintended ways when the measurement captures only part of the desired result.",
    toolId: "incentive-designer",
    toolLabel: "Incentive Designer",
  },
];

export function economicsMissionById(id: string): EconomicsMission | null {
  return ECONOMICS_MISSIONS.find((mission) => mission.id === id) ?? null;
}
