export type HistoryLevel = "Time Traveler" | "Historian" | "Evidence Detective";
export type HistorySkill = "chronology" | "change" | "cause" | "sources" | "perspective";

export type HistoryMission = {
  id: string;
  level: HistoryLevel;
  skill: HistorySkill;
  era: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  cardId: string;
  cardLabel: string;
};

export const HISTORY_SKILLS: Record<HistorySkill, { id: string; label: string }> = {
  chronology: { id: "history-chronology", label: "Chronology and timelines" },
  change: { id: "history-change-continuity", label: "Change and continuity" },
  cause: { id: "history-cause-effect", label: "Cause and effect" },
  sources: { id: "history-sources-evidence", label: "Sources and evidence" },
  perspective: { id: "history-perspective", label: "Historical perspective" },
};

export const HISTORY_MISSIONS: HistoryMission[] = [
  {
    id: "time-morning-order",
    level: "Time Traveler",
    skill: "chronology",
    era: "A Day in Order",
    emoji: "🌅",
    scene: "Milo woke up, ate breakfast, packed his backpack, and then walked to school.",
    prompt: "What happened immediately before Milo walked to school?",
    options: ["He packed his backpack", "He woke up", "He ate dinner"],
    answer: "He packed his backpack",
    hint: "Look at the action just before the word then.",
    explanation: "A timeline follows events in order. Packing the backpack came directly before walking to school.",
    cardId: "timeline-builder",
    cardLabel: "Timeline Builder",
  },
  {
    id: "time-photo-order",
    level: "Time Traveler",
    skill: "chronology",
    era: "Family Photo Box",
    emoji: "📷",
    scene: "One photo shows a baby crawling. Another shows the same child riding a small bike. A third shows the child reading a chapter book.",
    prompt: "Which photo belongs first on the timeline?",
    options: ["The baby crawling", "The child riding a bike", "The child reading a chapter book"],
    answer: "The baby crawling",
    hint: "Choose the event that usually happens at the youngest age.",
    explanation: "Crawling usually happens before bike riding and chapter-book reading, so it belongs first.",
    cardId: "photo-detective",
    cardLabel: "Photo Detective",
  },
  {
    id: "time-letters-messages",
    level: "Time Traveler",
    skill: "change",
    era: "Messages Then and Now",
    emoji: "✉️",
    scene: "Long ago, a letter might travel for days. Today, a message can arrive on a phone almost immediately.",
    prompt: "What changed most?",
    options: ["Messages can travel much faster", "People stopped sharing news", "Words no longer have meaning"],
    answer: "Messages can travel much faster",
    hint: "Compare how long each message takes to arrive.",
    explanation: "The need to communicate continued, but the speed and technology changed.",
    cardId: "change-spotter",
    cardLabel: "Change Spotter",
  },
  {
    id: "time-lighting",
    level: "Time Traveler",
    skill: "change",
    era: "Lighting a Home",
    emoji: "💡",
    scene: "Some homes once used candles or oil lamps at night. Many homes now use electric lights.",
    prompt: "What stayed the same?",
    options: ["People still need light after dark", "Every lamp uses oil", "Homes have no windows"],
    answer: "People still need light after dark",
    hint: "A continuity is something that remains even when tools change.",
    explanation: "The tools changed, but people continued needing safe light after sunset.",
    cardId: "continuity-keeper",
    cardLabel: "Continuity Keeper",
  },
  {
    id: "time-bridge-cause",
    level: "Time Traveler",
    skill: "cause",
    era: "The New Bridge",
    emoji: "🌉",
    scene: "Families had to wait for a small ferry to cross the river. The town built a bridge so people could cross more easily.",
    prompt: "Why did the town build the bridge?",
    options: ["Crossing by ferry was slow", "The river disappeared", "People wanted fewer roads"],
    answer: "Crossing by ferry was slow",
    hint: "The cause is the problem that came before the solution.",
    explanation: "The slow ferry crossing created a need. The bridge was an effect of that need.",
    cardId: "cause-finder",
    cardLabel: "Cause Finder",
  },
  {
    id: "time-streetlights",
    level: "Time Traveler",
    skill: "cause",
    era: "Safer Streets",
    emoji: "🏮",
    scene: "People found it difficult to see road corners after sunset. The community installed streetlights along the busiest paths.",
    prompt: "What was one likely effect of adding streetlights?",
    options: ["People could see the paths better", "Night became daytime", "Roads became rivers"],
    answer: "People could see the paths better",
    hint: "An effect is what happened because of the new lights.",
    explanation: "Streetlights improved visibility. That is a direct effect of the community's decision.",
    cardId: "effect-tracker",
    cardLabel: "Effect Tracker",
  },
  {
    id: "time-old-toy-source",
    level: "Time Traveler",
    skill: "sources",
    era: "The Attic Toy",
    emoji: "🪀",
    scene: "A museum finds a wooden toy with worn paint and a maker's mark on the bottom.",
    prompt: "What can the toy itself help historians learn?",
    options: ["What materials and tools were used", "The exact thoughts of every child", "Tomorrow's weather"],
    answer: "What materials and tools were used",
    hint: "An object can show physical evidence, but it cannot reveal every private thought.",
    explanation: "The wood, paint, and maker's mark are direct evidence about how the toy was made.",
    cardId: "artifact-reader",
    cardLabel: "Artifact Reader",
  },
  {
    id: "time-diary-source",
    level: "Time Traveler",
    skill: "sources",
    era: "A Rainy-Day Diary",
    emoji: "📓",
    scene: "A child wrote in a diary, 'The rain flooded our garden today, so school closed early.'",
    prompt: "Which detail comes directly from the diary?",
    options: ["School closed early", "Everyone enjoyed the flood", "The rain lasted seven weeks"],
    answer: "School closed early",
    hint: "Choose only what the writer actually recorded.",
    explanation: "The diary directly states that school closed early. The other choices add claims not found in the source.",
    cardId: "source-reader",
    cardLabel: "Source Reader",
  },
  {
    id: "time-rain-perspective",
    level: "Time Traveler",
    skill: "perspective",
    era: "One Rainstorm, Two Views",
    emoji: "🌧️",
    scene: "A farmer welcomed the rain because the fields were dry. A traveler disliked it because the muddy road slowed the trip.",
    prompt: "Why did they describe the same rain differently?",
    options: ["The rain affected their needs differently", "Only one person saw rain", "They lived in different centuries"],
    answer: "The rain affected their needs differently",
    hint: "Think about what each person hoped to do.",
    explanation: "Perspective depends on a person's situation. The same event helped the farmer and delayed the traveler.",
    cardId: "perspective-pair",
    cardLabel: "Perspective Pair",
  },
  {
    id: "time-market-perspective",
    level: "Time Traveler",
    skill: "perspective",
    era: "Busy Market Day",
    emoji: "🧺",
    scene: "A shopkeeper called the crowded market exciting because many customers arrived. A small child called it noisy and hard to cross.",
    prompt: "Which statement is best supported?",
    options: ["People can experience the same place differently", "The market was empty", "The child owned every shop"],
    answer: "People can experience the same place differently",
    hint: "Compare how each person felt about the same crowd.",
    explanation: "The two accounts differ because the shopkeeper and child had different roles and needs.",
    cardId: "viewpoint-listener",
    cardLabel: "Viewpoint Listener",
  },
  {
    id: "historian-farming-cities",
    level: "Historian",
    skill: "chronology",
    era: "From Farms to Cities",
    emoji: "🌾",
    scene: "Some communities learned to grow reliable food supplies. Larger permanent settlements developed later as more people could live in one place.",
    prompt: "Which event belongs earlier on the timeline?",
    options: ["Reliable farming developed", "Large permanent settlements grew", "Modern skyscrapers appeared"],
    answer: "Reliable farming developed",
    hint: "The scene says larger settlements developed later.",
    explanation: "Reliable agriculture helped support larger settlements, so farming belongs earlier in this sequence.",
    cardId: "early-settlement-timeline",
    cardLabel: "Settlement Timeline",
  },
  {
    id: "historian-print-order",
    level: "Historian",
    skill: "chronology",
    era: "Printing and News",
    emoji: "📰",
    scene: "Movable-type printing made it faster to produce many copies of text. Printed books became more available, and regularly printed newspapers spread later.",
    prompt: "Which order best matches the scene?",
    options: ["Faster printing, more books, more newspapers", "More newspapers, handwriting, faster printing", "Telephones, printing, cave paintings"],
    answer: "Faster printing, more books, more newspapers",
    hint: "Follow the chain described from invention to wider use.",
    explanation: "The printing technology came first, then books became more available, and regular newspapers expanded later.",
    cardId: "sequence-scholar",
    cardLabel: "Sequence Scholar",
  },
  {
    id: "historian-copying-printing",
    level: "Historian",
    skill: "change",
    era: "Copying a Book",
    emoji: "📚",
    scene: "Before mechanical printing, copying a book by hand could take a long time. Printing allowed many similar copies to be produced more quickly.",
    prompt: "Which change mattered most?",
    options: ["Written information could spread to more people", "Books stopped using words", "People forgot how to read"],
    answer: "Written information could spread to more people",
    hint: "Think about the result of making many copies faster.",
    explanation: "Printing reduced the time needed to copy texts and helped information reach wider audiences.",
    cardId: "printing-change",
    cardLabel: "Printing Change",
  },
  {
    id: "historian-transit-change",
    level: "Historian",
    skill: "change",
    era: "A Street in Motion",
    emoji: "🚋",
    scene: "A city street first carried walkers, carts, and horse-drawn vehicles. Later, electric streetcars carried larger groups on regular routes.",
    prompt: "What continued even as transportation changed?",
    options: ["People needed ways to move through the city", "Every vehicle used horses", "Streets were no longer needed"],
    answer: "People needed ways to move through the city",
    hint: "Look for the need that existed both before and after streetcars.",
    explanation: "Transportation technology changed, while the need to move people through the city continued.",
    cardId: "transport-continuity",
    cardLabel: "Transport Continuity",
  },
  {
    id: "historian-rail-market",
    level: "Historian",
    skill: "cause",
    era: "Rails to the Market",
    emoji: "🚂",
    scene: "A farming region gained a railway connection to a distant city. Travel time fell, and farmers could send fresh food to a larger market.",
    prompt: "Which effect followed most directly from the railway?",
    options: ["Farmers reached more customers", "The farms moved into the ocean", "The city stopped needing food"],
    answer: "Farmers reached more customers",
    hint: "Focus on what shorter travel made possible.",
    explanation: "The railway connected producers with a larger market, allowing farmers to reach more customers.",
    cardId: "connection-cause",
    cardLabel: "Connection Cause",
  },
  {
    id: "historian-clean-water",
    level: "Historian",
    skill: "cause",
    era: "Cleaner City Water",
    emoji: "🚰",
    scene: "City investigators noticed that illness was more common where drinking water mixed with waste. Leaders improved pipes and water treatment.",
    prompt: "What evidence helped cause the public works change?",
    options: ["Illness patterns linked to unsafe water", "A new style of hat", "Fewer clouds over the city"],
    answer: "Illness patterns linked to unsafe water",
    hint: "Choose the observation connected to the problem leaders tried to solve.",
    explanation: "The pattern of illness near unsafe water supported changes to sanitation and water systems.",
    cardId: "public-health-cause",
    cardLabel: "Public Health Cause",
  },
  {
    id: "historian-two-sources",
    level: "Historian",
    skill: "sources",
    era: "The Closed Mill",
    emoji: "🏭",
    scene: "A newspaper says a mill closed on Tuesday. A worker's dated letter also says the gates were locked Tuesday morning.",
    prompt: "Why is the claim stronger with both sources?",
    options: ["Independent sources agree on the date", "Two sources are always perfect", "Letters cannot contain mistakes"],
    answer: "Independent sources agree on the date",
    hint: "Historians call this corroboration.",
    explanation: "When separate sources agree, they corroborate one another and make a claim more strongly supported.",
    cardId: "corroboration-check",
    cardLabel: "Corroboration Check",
  },
  {
    id: "historian-primary-secondary",
    level: "Historian",
    skill: "sources",
    era: "Inside the Archive",
    emoji: "🗄️",
    scene: "A soldier's letter was written during a war. A textbook chapter about that war was written many years later using several sources.",
    prompt: "Which is a primary source for the soldier's experience?",
    options: ["The soldier's letter", "The later textbook chapter", "A blank notebook"],
    answer: "The soldier's letter",
    hint: "A primary source was created during the time being studied by someone connected to it.",
    explanation: "The letter is direct evidence from a participant at the time. The textbook is a later secondary source.",
    cardId: "primary-source-finder",
    cardLabel: "Primary Source Finder",
  },
  {
    id: "historian-factory-views",
    level: "Historian",
    skill: "perspective",
    era: "Inside a Factory",
    emoji: "⚙️",
    scene: "An owner praised a new machine because production increased. A worker worried because the faster pace made each shift more tiring.",
    prompt: "What explains the different accounts?",
    options: ["Their roles shaped what they noticed", "One account must be imaginary", "Machines affected nobody"],
    answer: "Their roles shaped what they noticed",
    hint: "Ask what each person gained or experienced.",
    explanation: "The owner focused on production while the worker focused on working conditions. Role shapes perspective.",
    cardId: "role-perspective",
    cardLabel: "Role Perspective",
  },
  {
    id: "historian-road-debate",
    level: "Historian",
    skill: "perspective",
    era: "The New Road Debate",
    emoji: "🛣️",
    scene: "A merchant supported a new road because deliveries would arrive faster. A nearby resident worried that construction would remove old trees and increase noise.",
    prompt: "What should a historian do with these two accounts?",
    options: ["Use both to understand competing priorities", "Discard the resident's account", "Assume everyone agreed"],
    answer: "Use both to understand competing priorities",
    hint: "Different accounts can reveal different effects of one decision.",
    explanation: "Using both perspectives produces a fuller picture of the benefits and costs people perceived.",
    cardId: "debate-listener",
    cardLabel: "Debate Listener",
  },
  {
    id: "detective-century-order",
    level: "Evidence Detective",
    skill: "chronology",
    era: "Dating the Documents",
    emoji: "🗓️",
    scene: "Three documents are dated 1848, 1906, and 1969.",
    prompt: "Which document belongs in the middle of the timeline?",
    options: ["1906", "1848", "1969"],
    answer: "1906",
    hint: "Order the years from smallest to largest.",
    explanation: "1848 comes first, 1906 is in the middle, and 1969 comes last.",
    cardId: "date-decoder",
    cardLabel: "Date Decoder",
  },
  {
    id: "detective-overlap",
    level: "Evidence Detective",
    skill: "chronology",
    era: "Overlapping Lives",
    emoji: "⏳",
    scene: "Inventor A lived from 1860 to 1925. Writer B lived from 1890 to 1970.",
    prompt: "During which years were both people alive?",
    options: ["1890 to 1925", "1860 to 1890", "1925 to 1970"],
    answer: "1890 to 1925",
    hint: "Find when the later life began and when the earlier life ended.",
    explanation: "Their lifetimes overlapped from Writer B's birth in 1890 until Inventor A's death in 1925.",
    cardId: "overlap-analyst",
    cardLabel: "Overlap Analyst",
  },
  {
    id: "detective-school-change",
    level: "Evidence Detective",
    skill: "change",
    era: "School Across Generations",
    emoji: "🏫",
    scene: "A 1910 school photograph shows slate boards and one room for several ages. A current photograph shows tablets and separate classrooms. Both show students learning together with a teacher.",
    prompt: "Which conclusion includes both change and continuity?",
    options: ["Tools and classroom organization changed, but guided group learning continued", "Nothing changed", "Teachers disappeared"],
    answer: "Tools and classroom organization changed, but guided group learning continued",
    hint: "A strong comparison names what changed and what remained.",
    explanation: "The technology and structure changed, while students continued learning in groups with teachers.",
    cardId: "change-continuity-analysis",
    cardLabel: "Change and Continuity",
  },
  {
    id: "detective-communication-change",
    level: "Evidence Detective",
    skill: "change",
    era: "Communication Revolution",
    emoji: "📡",
    scene: "Letters, telegraphs, telephones, and internet messages used different technologies. Each helped people share information across distance.",
    prompt: "Which statement is the best historical interpretation?",
    options: ["Communication tools changed while the need to connect continued", "Every tool worked at the same speed", "New tools erased all old tools immediately"],
    answer: "Communication tools changed while the need to connect continued",
    hint: "Avoid absolute claims such as every and immediately unless the evidence proves them.",
    explanation: "The technologies and speed changed, but the underlying human need remained.",
    cardId: "continuity-analyst",
    cardLabel: "Continuity Analyst",
  },
  {
    id: "detective-migration-causes",
    level: "Evidence Detective",
    skill: "cause",
    era: "Why Families Moved",
    emoji: "🧳",
    scene: "Several families left a drought-stricken farming area after crops failed. A nearby city also offered new factory jobs and rail transportation.",
    prompt: "Which explanation best fits the evidence?",
    options: ["Migration had both pushing and pulling causes", "Only one cause ever matters", "The families moved because trains were colorful"],
    answer: "Migration had both pushing and pulling causes",
    hint: "Separate reasons that pushed people away from reasons that attracted them elsewhere.",
    explanation: "Crop failure pushed families away, while jobs and transportation pulled them toward the city.",
    cardId: "multiple-cause-analyst",
    cardLabel: "Multiple-Cause Analyst",
  },
  {
    id: "detective-trigger-cause",
    level: "Evidence Detective",
    skill: "cause",
    era: "The Harbor Strike",
    emoji: "⚓",
    scene: "Workers had complained about low pay for years. When managers suddenly lengthened the workday, workers began a strike the next morning.",
    prompt: "Which was the immediate trigger?",
    options: ["The longer workday", "Years of low-pay complaints", "The harbor's location"],
    answer: "The longer workday",
    hint: "The trigger is the event directly before the action began, not every long-term condition.",
    explanation: "Low pay was a long-term cause, while the sudden longer workday triggered the strike.",
    cardId: "trigger-detector",
    cardLabel: "Trigger Detector",
  },
  {
    id: "detective-source-bias",
    level: "Evidence Detective",
    skill: "sources",
    era: "The Campaign Poster",
    emoji: "📜",
    scene: "A campaign poster calls one candidate 'the only wise choice.' It was printed and paid for by that candidate's organization.",
    prompt: "How should a historian use this source?",
    options: ["As evidence of the campaign's message, while checking its bias", "As neutral proof that everyone agreed", "As evidence that elections did not exist"],
    answer: "As evidence of the campaign's message, while checking its bias",
    hint: "Ask who created the source and what they wanted the audience to believe.",
    explanation: "The poster is useful evidence about persuasion, but its purpose and creator make it a biased account of the candidate.",
    cardId: "bias-checker",
    cardLabel: "Bias Checker",
  },
  {
    id: "detective-best-evidence",
    level: "Evidence Detective",
    skill: "sources",
    era: "Testing a Claim",
    emoji: "🔎",
    scene: "A historian claims that a town's population grew quickly between 1880 and 1900.",
    prompt: "Which source would best test that claim?",
    options: ["Population records from both years", "One person's favorite recipe", "A modern drawing of the town"],
    answer: "Population records from both years",
    hint: "The strongest evidence should measure the exact thing named in the claim.",
    explanation: "Comparable population records from 1880 and 1900 directly test whether the population grew.",
    cardId: "evidence-matcher",
    cardLabel: "Evidence Matcher",
  },
  {
    id: "detective-protest-accounts",
    level: "Evidence Detective",
    skill: "perspective",
    era: "Two Accounts of a Protest",
    emoji: "📣",
    scene: "An organizer described a protest as peaceful and determined. A business owner nearby described it as disruptive because customers could not enter the street.",
    prompt: "Which conclusion is most responsible?",
    options: ["Both accounts reveal different experiences and should be compared with more evidence", "Only the organizer can be correct", "Different accounts make history impossible"],
    answer: "Both accounts reveal different experiences and should be compared with more evidence",
    hint: "A historian compares perspectives and checks them against additional sources.",
    explanation: "The accounts reflect different positions. More evidence can clarify what happened while preserving both experiences.",
    cardId: "account-comparer",
    cardLabel: "Account Comparer",
  },
  {
    id: "detective-missing-voice",
    level: "Evidence Detective",
    skill: "perspective",
    era: "Who Is Missing?",
    emoji: "🗣️",
    scene: "An archive about a new dam contains reports from engineers and speeches from city leaders, but no interviews with families whose homes were moved.",
    prompt: "What should a historian notice?",
    options: ["An affected group's perspective is missing", "The archive contains every possible viewpoint", "Engineering reports are never useful"],
    answer: "An affected group's perspective is missing",
    hint: "Ask whose life changed but whose voice does not appear in the collection.",
    explanation: "The archive includes official perspectives but lacks testimony from displaced families, leaving an important gap.",
    cardId: "missing-voice-finder",
    cardLabel: "Missing Voice Finder",
  },
];

export function historyMissionById(id: string): HistoryMission | null {
  return HISTORY_MISSIONS.find((mission) => mission.id === id) ?? null;
}
