export type LifeSkillsLevel = "Helper" | "Independent" | "Planner";
export type LifeSkillsSkill = "routines" | "time" | "food" | "home" | "problem-solving";

export type LifeSkillsMission = {
  id: string;
  level: LifeSkillsLevel;
  skill: LifeSkillsSkill;
  emoji: string;
  title: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const LIFE_SKILLS: Record<LifeSkillsSkill, { id: string; label: string }> = {
  routines: { id: "life-routines-organization", label: "Routines and organization" },
  time: { id: "life-time-planning", label: "Time planning" },
  food: { id: "life-food-prep", label: "Food preparation and kitchen safety" },
  home: { id: "life-household-care", label: "Household care" },
  "problem-solving": { id: "life-help-problem-solving", label: "Everyday problem-solving and asking for help" },
};

export const LIFE_SKILLS_MISSIONS: LifeSkillsMission[] = [
  { id:"helper-backpack", level:"Helper", skill:"routines", emoji:"🎒", title:"Ready Backpack", scene:"School starts tomorrow. A library book, water bottle, and homework are on the table.", prompt:"What is the best way to get ready?", options:["Put each needed item in the backpack tonight","Wait until leaving and guess","Pack only the water bottle"], answer:"Put each needed item in the backpack tonight", hint:"A routine moves important tasks before the rushed moment.", explanation:"Packing from a short checklist the night before reduces forgotten items.", toolId:"night-before-check", toolLabel:"Night-Before Check" },
  { id:"helper-cleanup", level:"Helper", skill:"routines", emoji:"🧺", title:"Five-Minute Reset", scene:"Blocks, books, and crayons are spread across the floor after play.", prompt:"Which cleanup plan is easiest to follow?", options:["Return one category at a time","Throw everything into one hidden pile","Leave it until nobody remembers"], answer:"Return one category at a time", hint:"Sorting makes a large job smaller.", explanation:"Cleaning one category at a time creates a clear sequence and a visible finish line.", toolId:"category-reset", toolLabel:"Category Reset" },
  { id:"helper-clock", level:"Helper", skill:"time", emoji:"⏰", title:"Leave on Time", scene:"It takes 10 minutes to put on shoes and walk to the car. The family must leave at 8:00.", prompt:"When should getting ready begin?", options:["By 7:50","At 8:05","Whenever the clock feels ready"], answer:"By 7:50", hint:"Count backward from the deadline.", explanation:"Backward planning places the start time 10 minutes before departure.", toolId:"count-back", toolLabel:"Count-Back Planner" },
  { id:"helper-snack", level:"Helper", skill:"food", emoji:"🍎", title:"Safe Snack", scene:"A child wants apple slices. A sharp knife is on the counter.", prompt:"What is the safest next step?", options:["Ask a grown-up to cut the apple","Use the knife alone quickly","Bite the knife handle for practice"], answer:"Ask a grown-up to cut the apple", hint:"Sharp tools require the right level of supervision.", explanation:"Choosing adult help is part of food-prep independence, not the opposite of it.", toolId:"kitchen-help-check", toolLabel:"Kitchen Help Check" },
  { id:"helper-spill", level:"Helper", skill:"home", emoji:"🧽", title:"Small Spill", scene:"Water spills onto a smooth kitchen floor.", prompt:"What should happen first?", options:["Tell others and wipe it up","Walk away quietly","Cover it with paper and forget it"], answer:"Tell others and wipe it up", hint:"Think about preventing a slip.", explanation:"Warning people and drying the floor removes the immediate hazard.", toolId:"notice-fix", toolLabel:"Notice and Fix" },

  { id:"independent-morning", level:"Independent", skill:"routines", emoji:"✅", title:"Morning Sequence", scene:"A child often forgets brushing teeth when the morning feels rushed.", prompt:"Which system is most likely to help?", options:["Attach brushing to the same step every morning","Hope memory improves without a cue","Move the toothbrush to a new place daily"], answer:"Attach brushing to the same step every morning", hint:"Reliable routines use a stable cue.", explanation:"Linking a task to an existing habit makes the sequence easier to remember.", toolId:"habit-link", toolLabel:"Habit Link" },
  { id:"independent-homework", level:"Independent", skill:"time", emoji:"📚", title:"Homework Window", scene:"Homework takes about 25 minutes. Dinner begins in 40 minutes, and supplies still need to be gathered.", prompt:"What is the strongest plan?", options:["Gather supplies now and begin immediately","Start a long game first","Wait until dinner begins"], answer:"Gather supplies now and begin immediately", hint:"Include setup time, not only work time.", explanation:"A realistic plan accounts for preparation and protects the deadline.", toolId:"setup-time", toolLabel:"Setup-Time Planner" },
  { id:"independent-leftovers", level:"Independent", skill:"food", emoji:"🥡", title:"Leftover Check", scene:"Cooked food has been sitting on the table for a long time and nobody remembers when it was served.", prompt:"What is the safest choice?", options:["Ask an adult before eating it","Taste a little to test safety","Put it back and tell nobody"], answer:"Ask an adult before eating it", hint:"Smell and taste cannot prove every food is safe.", explanation:"Uncertain food-storage timing is a reason to pause and get adult guidance.", toolId:"food-safety-pause", toolLabel:"Food-Safety Pause" },
  { id:"independent-laundry", level:"Independent", skill:"home", emoji:"👕", title:"Laundry Sort", scene:"A red new shirt and several white clothes need washing.", prompt:"What is the best first step?", options:["Check labels and separate colors if needed","Use the hottest setting without checking","Add every cleaner in the cabinet"], answer:"Check labels and separate colors if needed", hint:"Care instructions and color transfer both matter.", explanation:"Checking labels and sorting reduces shrinking, damage, and dye transfer.", toolId:"label-first", toolLabel:"Label-First Care" },
  { id:"independent-missing-item", level:"Independent", skill:"problem-solving", emoji:"🔎", title:"Missing Permission Slip", scene:"A permission slip is not in the usual folder, and school begins soon.", prompt:"Which plan is most effective?", options:["Check the last likely locations, then tell an adult or teacher","Search every object in the house randomly","Pretend the trip does not exist"], answer:"Check the last likely locations, then tell an adult or teacher", hint:"Use a short search limit and then communicate.", explanation:"A bounded search followed by early communication prevents a small problem from growing.", toolId:"search-then-say", toolLabel:"Search, Then Say" },

  { id:"planner-week", level:"Planner", skill:"routines", emoji:"🗓️", title:"Busy Week Board", scene:"This week includes a library return, sports practice, a project, and a family event.", prompt:"Which system best prevents tasks from disappearing?", options:["Put deadlines and preparation steps on one visible weekly plan","Keep each task only in memory","Write one giant note with no dates"], answer:"Put deadlines and preparation steps on one visible weekly plan", hint:"A useful system shows both when and what comes before.", explanation:"A shared weekly view makes commitments and preparation steps visible.", toolId:"weekly-command-board", toolLabel:"Weekly Command Board" },
  { id:"planner-buffer", level:"Planner", skill:"time", emoji:"🕒", title:"Travel Buffer", scene:"A lesson starts at 4:00. Travel usually takes 20 minutes, but traffic sometimes adds 10.", prompt:"Which departure plan is strongest?", options:["Leave by 3:30","Leave at 3:40 exactly","Leave at 4:00"], answer:"Leave by 3:30", hint:"Strong plans include uncertainty, not only the average.", explanation:"A 10-minute buffer protects the arrival time when normal delays happen.", toolId:"buffer-builder", toolLabel:"Buffer Builder" },
  { id:"planner-meal", level:"Planner", skill:"food", emoji:"🥗", title:"Simple Meal Plan", scene:"A child wants to prepare a simple meal with an adult. Ingredients, handwashing, tools, and cleanup all matter.", prompt:"Which order is best?", options:["Plan ingredients, wash hands, prepare with supervision, clean surfaces","Cook first and search for ingredients later","Skip cleanup because cooking is finished"], answer:"Plan ingredients, wash hands, prepare with supervision, clean surfaces", hint:"A complete food plan includes before, during, and after.", explanation:"Safe meal preparation combines planning, hygiene, appropriate supervision, and cleanup.", toolId:"meal-sequence", toolLabel:"Meal Sequence" },
  { id:"planner-cleaner", level:"Planner", skill:"home", emoji:"🧴", title:"Unknown Cleaner", scene:"A bottle under the sink has a damaged label. A sticky mark needs cleaning.", prompt:"What is the correct decision?", options:["Do not use it; ask an adult for a known product","Smell it closely to identify it","Mix it with another cleaner"], answer:"Do not use it; ask an adult for a known product", hint:"Unknown chemicals and mixed cleaners can be dangerous.", explanation:"Only clearly labeled products should be used, and children should involve an adult with household chemicals.", toolId:"known-product-only", toolLabel:"Known-Product Rule" },
  { id:"planner-plan-b", level:"Planner", skill:"problem-solving", emoji:"🧭", title:"Plan B", scene:"A ride is late, the phone battery is low, and the meeting place is about to close.", prompt:"What is the best response?", options:["Move to the agreed safe backup location and contact a trusted adult","Wander around looking for the ride","Accept transportation from an unknown person"], answer:"Move to the agreed safe backup location and contact a trusted adult", hint:"Good independence includes a safe backup and communication.", explanation:"A predetermined safe location and trusted-adult contact turn uncertainty into a controlled plan.", toolId:"safe-plan-b", toolLabel:"Safe Plan B" },
];

export function lifeSkillsMissionById(id: string): LifeSkillsMission | null {
  return LIFE_SKILLS_MISSIONS.find((mission) => mission.id === id) ?? null;
}
