export type HealthLevel = "Healthy Helper" | "Body Steward" | "Safety Strategist";
export type HealthSkill = "dailyCare" | "hygiene" | "bodySignals" | "medicine" | "emergency";

export type HealthMission = {
  id: string;
  level: HealthLevel;
  skill: HealthSkill;
  setting: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const HEALTH_SKILLS: Record<HealthSkill, { id: string; label: string }> = {
  dailyCare: { id: "health-daily-care", label: "Daily body care" },
  hygiene: { id: "health-hygiene-germs", label: "Hygiene and germ prevention" },
  bodySignals: { id: "health-body-signals-help", label: "Body signals and asking for help" },
  medicine: { id: "health-medicine-poison", label: "Medicine and poison safety" },
  emergency: { id: "health-injury-emergency", label: "Injury and emergency response" },
};

export const HEALTH_MISSIONS: HealthMission[] = [
  {
    id: "helper-bedtime-routine",
    level: "Healthy Helper",
    skill: "dailyCare",
    setting: "Getting Ready for Sleep",
    emoji: "🌙",
    scene: "Ari wants to keep playing a loud game, but bedtime is close and tomorrow is a school day.",
    prompt: "Which choice best helps Ari's body prepare for sleep?",
    options: ["Use a calm routine and dim the screen", "Start a louder game", "Drink a giant sugary drink"],
    answer: "Use a calm routine and dim the screen",
    hint: "Bodies settle more easily when the last part of the day becomes quieter.",
    explanation: "A calm, predictable bedtime routine helps the brain and body shift toward sleep.",
    toolId: "sleep-routine-builder",
    toolLabel: "Sleep Routine Builder",
  },
  {
    id: "helper-water-break",
    level: "Healthy Helper",
    skill: "dailyCare",
    setting: "Playground Water Break",
    emoji: "💧",
    scene: "Noah has been running outside. His mouth feels dry and he keeps thinking about water.",
    prompt: "What should Noah do?",
    options: ["Pause and drink water", "Ignore the feeling all day", "Only lick his lips"],
    answer: "Pause and drink water",
    hint: "A dry mouth after active play can be a body signal asking for fluids.",
    explanation: "Taking regular water breaks during active play helps the body replace fluid it uses.",
    toolId: "water-break-planner",
    toolLabel: "Water Break Planner",
  },
  {
    id: "helper-handwashing",
    level: "Healthy Helper",
    skill: "hygiene",
    setting: "After the Bathroom",
    emoji: "🧼",
    scene: "Mina finishes using the bathroom and is excited to return to her blocks.",
    prompt: "What belongs before she goes back to play?",
    options: ["Wash with soap and water", "Wipe hands on her shirt", "Skip washing because hands look clean"],
    answer: "Wash with soap and water",
    hint: "Germs can be too small to see.",
    explanation: "Washing with soap and water removes germs that may remain even when hands look clean.",
    toolId: "soap-and-water-pro",
    toolLabel: "Soap-and-Water Pro",
  },
  {
    id: "helper-cough-elbow",
    level: "Healthy Helper",
    skill: "hygiene",
    setting: "A Sudden Cough",
    emoji: "🤧",
    scene: "Eli feels a cough coming while standing near classmates.",
    prompt: "What is the best quick choice?",
    options: ["Cough into his elbow", "Cough toward a friend", "Cough into both hands and touch toys"],
    answer: "Cough into his elbow",
    hint: "Use a place that will not immediately touch shared objects.",
    explanation: "Coughing into the elbow helps reduce droplets on hands and nearby people.",
    toolId: "elbow-shield",
    toolLabel: "Elbow Cough Shield",
  },
  {
    id: "helper-stomachache",
    level: "Healthy Helper",
    skill: "bodySignals",
    setting: "Tummy Trouble",
    emoji: "🫶",
    scene: "Zoe's stomach begins hurting during class. She is not sure why.",
    prompt: "What is the safest next step?",
    options: ["Tell a trusted adult", "Hide it until bedtime", "Take medicine from another child's bag"],
    answer: "Tell a trusted adult",
    hint: "Children do not have to diagnose a body signal by themselves.",
    explanation: "A trusted adult can help decide whether Zoe needs rest, water, the nurse, or other care.",
    toolId: "body-signal-reporter",
    toolLabel: "Body Signal Reporter",
  },
  {
    id: "helper-too-dizzy",
    level: "Healthy Helper",
    skill: "bodySignals",
    setting: "Dizzy After Spinning",
    emoji: "🌀",
    scene: "Kai spins many times, stops, and feels too dizzy to walk steadily.",
    prompt: "What should Kai do first?",
    options: ["Sit safely and tell an adult", "Run across the room", "Climb onto a chair"],
    answer: "Sit safely and tell an adult",
    hint: "Choose the action that prevents a fall and brings help closer.",
    explanation: "Sitting in a safe place and telling an adult reduces fall risk while the adult checks how Kai is doing.",
    toolId: "stop-sit-tell",
    toolLabel: "Stop, Sit, Tell",
  },
  {
    id: "helper-unknown-pill",
    level: "Healthy Helper",
    skill: "medicine",
    setting: "A Pill on the Floor",
    emoji: "💊",
    scene: "Luca sees a small pill under a chair. He does not know what it is or who dropped it.",
    prompt: "What should Luca do?",
    options: ["Do not touch it and tell an adult", "Taste it to identify it", "Put it in his pocket"],
    answer: "Do not touch it and tell an adult",
    hint: "Unknown medicine is never a guessing game.",
    explanation: "Children should avoid handling or tasting unknown pills and alert a trusted adult immediately.",
    toolId: "unknown-pill-rule",
    toolLabel: "Unknown Pill Rule",
  },
  {
    id: "helper-medicine-from-adult",
    level: "Healthy Helper",
    skill: "medicine",
    setting: "Cough Medicine Time",
    emoji: "🥄",
    scene: "Sam's friend offers a spoonful of medicine that helped the friend's cough.",
    prompt: "What should Sam say?",
    options: ["No, medicine only comes from my trusted adult", "Yes, friends can share any medicine", "I will take two spoonfuls"],
    answer: "No, medicine only comes from my trusted adult",
    hint: "The right medicine and amount can be different for each person.",
    explanation: "Medicine should never be shared. A trusted adult follows the correct label or health professional's instructions.",
    toolId: "medicine-grownup-check",
    toolLabel: "Medicine Grown-Up Check",
  },
  {
    id: "helper-scraped-knee",
    level: "Healthy Helper",
    skill: "emergency",
    setting: "A Playground Scrape",
    emoji: "🩹",
    scene: "Ivy falls and scrapes her knee. She can stand, but the skin is dirty and bleeding a little.",
    prompt: "What is the best next step?",
    options: ["Tell an adult so it can be cleaned and covered", "Rub playground dirt into it", "Hide the scrape"],
    answer: "Tell an adult so it can be cleaned and covered",
    hint: "Minor injuries still deserve clean care.",
    explanation: "An adult can wash the scrape, check it, and cover it with a clean bandage if needed.",
    toolId: "clean-cover-helper",
    toolLabel: "Clean-and-Cover Helper",
  },
  {
    id: "helper-smoke-alarm",
    level: "Healthy Helper",
    skill: "emergency",
    setting: "The Smoke Alarm Sounds",
    emoji: "🚨",
    scene: "A smoke alarm begins making a loud warning sound and an adult says to leave the house.",
    prompt: "What should the child do?",
    options: ["Leave with the adult and stay outside", "Hide under the bed", "Go back for a toy"],
    answer: "Leave with the adult and stay outside",
    hint: "In a fire warning, getting out matters more than belongings.",
    explanation: "Children should follow the escape plan, leave promptly, and never re-enter until emergency professionals say it is safe.",
    toolId: "get-out-stay-out",
    toolLabel: "Get Out, Stay Out",
  },
  {
    id: "steward-balanced-snack",
    level: "Body Steward",
    skill: "dailyCare",
    setting: "After-School Fuel",
    emoji: "🍎",
    scene: "Jules is hungry after school and has soccer practice later.",
    prompt: "Which snack is most likely to provide steadier fuel?",
    options: ["Fruit with yogurt or cheese", "Only candy", "Nothing until late at night"],
    answer: "Fruit with yogurt or cheese",
    hint: "Pairing foods can provide energy plus protein or other nutrients.",
    explanation: "A varied snack such as fruit plus yogurt or cheese can provide carbohydrates, protein, and nutrients for lasting fuel.",
    toolId: "steady-fuel-builder",
    toolLabel: "Steady Fuel Builder",
  },
  {
    id: "steward-recovery-day",
    level: "Body Steward",
    skill: "dailyCare",
    setting: "A Very Active Week",
    emoji: "🏃",
    scene: "Rin has practiced hard every day and now feels unusually tired and sore.",
    prompt: "Which plan supports healthy recovery?",
    options: ["Use rest, sleep, water, and gentle movement", "Add the hardest workout yet", "Skip food and sleep"],
    answer: "Use rest, sleep, water, and gentle movement",
    hint: "Bodies improve during recovery as well as during practice.",
    explanation: "Rest, hydration, food, sleep, and lighter activity help the body recover from repeated effort.",
    toolId: "recovery-planner",
    toolLabel: "Recovery Planner",
  },
  {
    id: "steward-twenty-second-wash",
    level: "Body Steward",
    skill: "hygiene",
    setting: "The Quick Hand Wash",
    emoji: "⏱️",
    scene: "Omar wets his hands, adds soap, and rinses after only two seconds.",
    prompt: "What should he change?",
    options: ["Scrub all hand surfaces for about 20 seconds", "Use no soap", "Only wash one fingertip"],
    answer: "Scrub all hand surfaces for about 20 seconds",
    hint: "Soap needs rubbing time to reach palms, backs, fingers, and nails.",
    explanation: "Scrubbing with soap for about 20 seconds helps remove germs from all parts of the hands.",
    toolId: "twenty-second-washer",
    toolLabel: "20-Second Washer",
  },
  {
    id: "steward-sun-plan",
    level: "Body Steward",
    skill: "hygiene",
    setting: "A Long Sunny Field Day",
    emoji: "☀️",
    scene: "The class will spend several hours outside on a bright day.",
    prompt: "Which plan best protects skin and helps prevent overheating?",
    options: ["Use shade, a hat, water, and adult-approved sun protection", "Wear no protection and avoid water", "Stay in direct sun without breaks"],
    answer: "Use shade, a hat, water, and adult-approved sun protection",
    hint: "Use more than one layer of protection.",
    explanation: "Shade, protective clothing, hydration, and correctly used sunscreen work together during long outdoor activities.",
    toolId: "sun-safety-layer",
    toolLabel: "Sun Safety Layers",
  },
  {
    id: "steward-head-hit",
    level: "Body Steward",
    skill: "bodySignals",
    setting: "A Hit to the Head",
    emoji: "🧠",
    scene: "During a game, Theo hits his head and then says he feels confused and has a headache.",
    prompt: "What should happen next?",
    options: ["Stop playing and tell an adult immediately", "Return to the game without telling anyone", "Try to hide the symptoms"],
    answer: "Stop playing and tell an adult immediately",
    hint: "Confusion after a head impact is not a play-through signal.",
    explanation: "A child with symptoms after a head impact should stop activity and be evaluated by a responsible adult and health professional as appropriate.",
    toolId: "head-hit-stop-rule",
    toolLabel: "Head-Hit Stop Rule",
  },
  {
    id: "steward-heat-signals",
    level: "Body Steward",
    skill: "bodySignals",
    setting: "Hot-Day Practice",
    emoji: "🌡️",
    scene: "Ava is exercising in hot weather. She develops a headache, weakness, and feels much hotter than usual.",
    prompt: "What is the safest response?",
    options: ["Stop, move to a cooler place, and tell an adult", "Keep sprinting alone", "Wrap in extra blankets"],
    answer: "Stop, move to a cooler place, and tell an adult",
    hint: "Heat symptoms call for cooling and help, not more exertion.",
    explanation: "Stopping activity, moving to a cooler place, and getting adult help are important when heat-related symptoms appear.",
    toolId: "heat-stop-cool-tell",
    toolLabel: "Heat: Stop, Cool, Tell",
  },
  {
    id: "steward-label-dose",
    level: "Body Steward",
    skill: "medicine",
    setting: "Reading the Medicine Label",
    emoji: "🏷️",
    scene: "A caregiver is preparing a child's medicine. The bottle has directions for age, amount, and timing.",
    prompt: "Why should the caregiver follow the label or clinician's instructions exactly?",
    options: ["The safe amount and timing matter", "More is always faster", "Labels are only decoration"],
    answer: "The safe amount and timing matter",
    hint: "Medicine can help at the correct dose and harm at the wrong one.",
    explanation: "Correct medicine, dose, measuring tool, and timing reduce the risk of underdosing, overdosing, or mixing products incorrectly.",
    toolId: "label-before-dose",
    toolLabel: "Label-Before-Dose Check",
  },
  {
    id: "steward-cleaner-spill",
    level: "Body Steward",
    skill: "medicine",
    setting: "A Cleaner Spills",
    emoji: "🧴",
    scene: "A bottle of household cleaner spills and gives off a strong smell.",
    prompt: "What should a child do?",
    options: ["Move away and tell an adult", "Lean close and sniff it", "Mix it with another cleaner"],
    answer: "Move away and tell an adult",
    hint: "Unknown fumes and chemicals should be handled by informed adults.",
    explanation: "Children should leave the area, avoid touching or mixing chemicals, and alert an adult who can follow the product's safety instructions.",
    toolId: "chemical-distance-rule",
    toolLabel: "Chemical Distance Rule",
  },
  {
    id: "steward-small-burn",
    level: "Body Steward",
    skill: "emergency",
    setting: "A Hot Pan Touch",
    emoji: "🔥",
    scene: "Mae briefly touches a hot pan and gets a small burn on her hand.",
    prompt: "What is the best immediate response?",
    options: ["Move away, cool it with cool running water, and tell an adult", "Put ice directly on it", "Hide the burn and keep cooking"],
    answer: "Move away, cool it with cool running water, and tell an adult",
    hint: "Use cool water, not extreme cold, and involve an adult.",
    explanation: "Moving away from heat, cooling a minor burn under cool running water, and getting adult help are safer than applying ice or home remedies.",
    toolId: "cool-water-burn-plan",
    toolLabel: "Cool-Water Burn Plan",
  },
  {
    id: "steward-bike-helmet",
    level: "Body Steward",
    skill: "emergency",
    setting: "Bike Ride Setup",
    emoji: "🚲",
    scene: "Ben is ready to ride his bike. His helmet is hanging from the handlebar.",
    prompt: "What should happen before the bike moves?",
    options: ["Put on and fasten the properly fitted helmet", "Leave the helmet on the handlebar", "Wear it only after falling"],
    answer: "Put on and fasten the properly fitted helmet",
    hint: "Protective gear works before an injury, not after it.",
    explanation: "A properly fitted, fastened helmet helps protect the head during a fall or crash.",
    toolId: "helmet-before-wheels",
    toolLabel: "Helmet Before Wheels",
  },
  {
    id: "strategist-balanced-plan",
    level: "Safety Strategist",
    skill: "dailyCare",
    setting: "Studying for a Big Test",
    emoji: "📚",
    scene: "Nia plans to study all night, skip breakfast, and use energy drinks to stay awake.",
    prompt: "Which revised plan better supports learning and health?",
    options: ["Study in blocks, sleep, eat, and use normal hydration", "Keep the all-night plan", "Skip sleep for several nights"],
    answer: "Study in blocks, sleep, eat, and use normal hydration",
    hint: "Learning depends on recovery and steady fuel, not only extra awake time.",
    explanation: "Distributed practice, adequate sleep, regular food, and hydration support attention and memory better than repeated sleep loss.",
    toolId: "study-recovery-balance",
    toolLabel: "Study-Recovery Balance",
  },
  {
    id: "strategist-training-load",
    level: "Safety Strategist",
    skill: "dailyCare",
    setting: "Increasing a Training Plan",
    emoji: "🏋️",
    scene: "Jordan wants to double every workout immediately because one week of practice felt easy.",
    prompt: "Which principle is safer?",
    options: ["Increase gradually and include recovery", "Double everything at once", "Ignore persistent pain"],
    answer: "Increase gradually and include recovery",
    hint: "Bodies adapt best when workload rises in manageable steps.",
    explanation: "Gradual progression and recovery reduce avoidable overload while still allowing strength and skill to develop.",
    toolId: "gradual-load-planner",
    toolLabel: "Gradual Load Planner",
  },
  {
    id: "strategist-illness-spread",
    level: "Safety Strategist",
    skill: "hygiene",
    setting: "Sick Before a Team Event",
    emoji: "🤒",
    scene: "A child has fever-like symptoms and a new cough before a crowded team event.",
    prompt: "What is the most responsible first step?",
    options: ["Tell a caregiver and follow health guidance before attending", "Hide symptoms and share drinks", "Take someone else's medicine and go"],
    answer: "Tell a caregiver and follow health guidance before attending",
    hint: "Protecting others begins with honest reporting and adult guidance.",
    explanation: "A caregiver can assess symptoms, seek medical advice when needed, and decide when staying home helps protect the child and community.",
    toolId: "symptom-honesty-plan",
    toolLabel: "Symptom Honesty Plan",
  },
  {
    id: "strategist-food-safety",
    level: "Safety Strategist",
    skill: "hygiene",
    setting: "Picnic Food in the Sun",
    emoji: "🧺",
    scene: "Perishable food has been sitting warm in direct sun for a long time, but it still looks normal.",
    prompt: "What is the safest conclusion?",
    options: ["Appearance alone cannot prove it is safe; ask an adult and discard when in doubt", "If it looks normal it is always safe", "Taste a large amount to test it"],
    answer: "Appearance alone cannot prove it is safe; ask an adult and discard when in doubt",
    hint: "Some harmful germs do not change how food looks or smells.",
    explanation: "Time and temperature matter for perishable food. A responsible adult should follow food-safety guidance rather than relying only on appearance.",
    toolId: "food-time-temperature-check",
    toolLabel: "Food Time-and-Temperature Check",
  },
  {
    id: "strategist-breathing-emergency",
    level: "Safety Strategist",
    skill: "bodySignals",
    setting: "Trouble Breathing",
    emoji: "🫁",
    scene: "A child suddenly has severe trouble breathing and cannot speak normally.",
    prompt: "What is the correct response?",
    options: ["Get an adult and call 911 immediately", "Wait alone to see what happens", "Offer random medicine"],
    answer: "Get an adult and call 911 immediately",
    hint: "Severe breathing difficulty is an emergency, not a wait-and-see symptom.",
    explanation: "Severe trouble breathing needs immediate emergency help. Use the child's prescribed emergency plan only as directed while help is called.",
    toolId: "breathing-emergency-recognizer",
    toolLabel: "Breathing Emergency Recognizer",
  },
  {
    id: "strategist-persistent-symptoms",
    level: "Safety Strategist",
    skill: "bodySignals",
    setting: "A Symptom That Keeps Returning",
    emoji: "📋",
    scene: "For several days, a child repeatedly gets headaches during school and has trouble seeing the board.",
    prompt: "Which response is best?",
    options: ["Tell a caregiver and describe when it happens", "Keep it secret forever", "Use a friend's prescription glasses and medicine"],
    answer: "Tell a caregiver and describe when it happens",
    hint: "Patterns are useful information for adults and health professionals.",
    explanation: "Reporting the timing, triggers, and other symptoms helps a caregiver decide whether the child needs an eye check or medical evaluation.",
    toolId: "symptom-pattern-reporter",
    toolLabel: "Symptom Pattern Reporter",
  },
  {
    id: "strategist-two-medicines",
    level: "Safety Strategist",
    skill: "medicine",
    setting: "Two Cold Products",
    emoji: "🧾",
    scene: "Two different cold products have different brand names. A caregiver notices they may contain the same active ingredient.",
    prompt: "Why should the ingredients be checked before combining them?",
    options: ["The same ingredient could be taken twice", "Brand names guarantee different ingredients", "More products are always safer"],
    answer: "The same ingredient could be taken twice",
    hint: "Different packages can still contain overlapping medicine.",
    explanation: "Checking active ingredients helps prevent accidental double dosing. A pharmacist or clinician can answer questions about combinations.",
    toolId: "active-ingredient-check",
    toolLabel: "Active Ingredient Check",
  },
  {
    id: "strategist-supplement-claim",
    level: "Safety Strategist",
    skill: "medicine",
    setting: "A Viral Supplement Video",
    emoji: "📱",
    scene: "A video claims a supplement cures every illness and says children should take it without asking adults.",
    prompt: "What is the safest response?",
    options: ["Do not take it; check with a caregiver and qualified health professional", "Take a large amount immediately", "Share it with younger children"],
    answer: "Do not take it; check with a caregiver and qualified health professional",
    hint: "A confident online claim is not the same as reliable medical evidence.",
    explanation: "Supplements can have side effects, interactions, or poor evidence. Children should not use them without responsible adult and professional guidance.",
    toolId: "health-claim-checker",
    toolLabel: "Health Claim Checker",
  },
  {
    id: "strategist-unconscious-person",
    level: "Safety Strategist",
    skill: "emergency",
    setting: "Someone Will Not Wake Up",
    emoji: "📞",
    scene: "A person is lying still and does not respond when called. The area appears safe to approach.",
    prompt: "What should a child do?",
    options: ["Call 911 and get a nearby adult", "Leave without telling anyone", "Give food or drink"],
    answer: "Call 911 and get a nearby adult",
    hint: "Unresponsiveness is an emergency requiring trained help.",
    explanation: "Calling emergency services and bringing an adult starts the fastest route to trained care. The dispatcher can give instructions.",
    toolId: "emergency-call-starter",
    toolLabel: "Emergency Call Starter",
  },
  {
    id: "strategist-poison-exposure",
    level: "Safety Strategist",
    skill: "emergency",
    setting: "Possible Poison Exposure",
    emoji: "☠️",
    scene: "A child may have swallowed an unknown household product but is awake and breathing normally.",
    prompt: "What should happen next?",
    options: ["Tell an adult immediately and contact Poison Help at 1-800-222-1222", "Make the child vomit", "Wait until tomorrow without telling anyone"],
    answer: "Tell an adult immediately and contact Poison Help at 1-800-222-1222",
    hint: "Poison experts give case-specific instructions; do not invent a home treatment.",
    explanation: "In the United States, Poison Help provides immediate expert guidance at 1-800-222-1222. Call 911 for collapse, seizure, severe breathing trouble, or another life-threatening emergency.",
    toolId: "poison-help-plan",
    toolLabel: "Poison Help Plan",
  },
];

export function healthMissionById(id: string): HealthMission | null {
  return HEALTH_MISSIONS.find((mission) => mission.id === id) ?? null;
}
