export type WellbeingLevel = "Feelings Finder" | "Friendship Builder" | "Calm Problem Solver";
export type WellbeingSkill = "emotions" | "regulation" | "communication" | "empathy" | "conflict";

export type WellbeingMission = {
  id: string;
  level: WellbeingLevel;
  skill: WellbeingSkill;
  setting: string;
  emoji: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const WELLBEING_SKILLS: Record<WellbeingSkill, { id: string; label: string }> = {
  emotions: { id: "wellbeing-emotional-awareness", label: "Emotional awareness" },
  regulation: { id: "wellbeing-self-regulation", label: "Self-regulation" },
  communication: { id: "wellbeing-communication-listening", label: "Communication and listening" },
  empathy: { id: "wellbeing-empathy-perspective", label: "Empathy and perspective" },
  conflict: { id: "wellbeing-conflict-boundaries", label: "Conflict resolution and boundaries" },
};

export const WELLBEING_MISSIONS: WellbeingMission[] = [
  {
    id: "finder-block-tower",
    level: "Feelings Finder",
    skill: "emotions",
    setting: "The Fallen Tower",
    emoji: "🧱",
    scene: "Kai builds a tall block tower. It falls just before he adds the last block. His face feels hot and his hands squeeze into fists.",
    prompt: "Which feeling best matches Kai's clues?",
    options: ["Frustrated", "Sleepy", "Proud"],
    answer: "Frustrated",
    hint: "Look at what happened and what his body is doing.",
    explanation: "A difficult setback, a hot face, and tight fists are clues that Kai may feel frustrated.",
    toolId: "feeling-name-finder",
    toolLabel: "Feeling Name Finder",
  },
  {
    id: "finder-new-class",
    level: "Feelings Finder",
    skill: "emotions",
    setting: "A New Classroom",
    emoji: "🎒",
    scene: "Mina walks into a new classroom. Her stomach feels fluttery, and she stays close to her grown-up even though she wants to meet the other children.",
    prompt: "Which two feelings could both be true?",
    options: ["Nervous and curious", "Angry and asleep", "Bored and certain"],
    answer: "Nervous and curious",
    hint: "People can have more than one feeling at the same time.",
    explanation: "Mina's fluttery stomach suggests nervousness, while wanting to meet the children shows curiosity.",
    toolId: "mixed-feelings-map",
    toolLabel: "Mixed Feelings Map",
  },
  {
    id: "finder-crayon-break",
    level: "Feelings Finder",
    skill: "regulation",
    setting: "The Broken Crayon",
    emoji: "🖍️",
    scene: "Owen's favorite crayon snaps. He wants to throw the pieces across the table.",
    prompt: "What is the best first step?",
    options: ["Pause and take three slow breaths", "Throw the pieces", "Break another crayon"],
    answer: "Pause and take three slow breaths",
    hint: "Choose an action that helps the body slow down before deciding what to do.",
    explanation: "Pausing and breathing creates space between the feeling and the action. Owen can solve the crayon problem after his body settles.",
    toolId: "pause-button",
    toolLabel: "Pause Button",
  },
  {
    id: "finder-loud-room",
    level: "Feelings Finder",
    skill: "regulation",
    setting: "The Loud Party",
    emoji: "🎈",
    scene: "The room is loud and crowded. Tia covers her ears and feels like crying.",
    prompt: "Which choice could help Tia regulate safely?",
    options: ["Ask for a quiet break", "Yell at everyone", "Hide without telling anyone"],
    answer: "Ask for a quiet break",
    hint: "A helpful strategy can change the environment and keep a trusted adult informed.",
    explanation: "Asking for a quiet break protects Tia's needs and lets a grown-up help her find a calmer place.",
    toolId: "calm-space-finder",
    toolLabel: "Calm Space Finder",
  },
  {
    id: "finder-toy-request",
    level: "Feelings Finder",
    skill: "communication",
    setting: "The Red Truck",
    emoji: "🚚",
    scene: "Luis wants the red truck that Ava is using.",
    prompt: "What could Luis say clearly and kindly?",
    options: ["Can I have a turn when you are finished?", "Give it now!", "I will take it."],
    answer: "Can I have a turn when you are finished?",
    hint: "A clear request says what you want without grabbing or threatening.",
    explanation: "Luis names his request and respects that Ava is currently using the truck.",
    toolId: "clear-request-maker",
    toolLabel: "Clear Request Maker",
  },
  {
    id: "finder-listening-eyes",
    level: "Feelings Finder",
    skill: "communication",
    setting: "The Lost Mitten",
    emoji: "🧤",
    scene: "Nora tells Ben where she last saw his mitten. Ben keeps talking over her and misses the clue.",
    prompt: "What should Ben do to listen better?",
    options: ["Stop, look toward Nora, and let her finish", "Talk louder", "Walk away while she speaks"],
    answer: "Stop, look toward Nora, and let her finish",
    hint: "Listening means making room for the other person's words.",
    explanation: "Pausing, orienting toward the speaker, and waiting for the full message helps Ben understand the clue.",
    toolId: "listening-ears",
    toolLabel: "Listening Ears",
  },
  {
    id: "finder-sad-friend",
    level: "Feelings Finder",
    skill: "empathy",
    setting: "The Missed Goal",
    emoji: "⚽",
    scene: "Jamal misses a soccer goal and sits alone with his head down.",
    prompt: "What is a kind first response?",
    options: ["Ask if he wants company", "Tell him it does not matter", "Laugh about the miss"],
    answer: "Ask if he wants company",
    hint: "Empathy notices the feeling and offers support without forcing it.",
    explanation: "Asking if Jamal wants company shows care while allowing him to choose what would help.",
    toolId: "kindness-check-in",
    toolLabel: "Kindness Check-In",
  },
  {
    id: "finder-drawing-difference",
    level: "Feelings Finder",
    skill: "empathy",
    setting: "Two Drawings",
    emoji: "🎨",
    scene: "Ari loves a bright, busy drawing. Sam prefers a simple drawing with only two colors.",
    prompt: "Which statement shows perspective-taking?",
    options: ["Different people can enjoy different styles", "Ari's choice is the only good one", "Sam must secretly agree with Ari"],
    answer: "Different people can enjoy different styles",
    hint: "Perspective-taking allows another person's preference to be real even when it differs from yours.",
    explanation: "Ari and Sam can honestly prefer different art without either preference being wrong.",
    toolId: "perspective-window",
    toolLabel: "Perspective Window",
  },
  {
    id: "finder-swing-turn",
    level: "Feelings Finder",
    skill: "conflict",
    setting: "The Playground Swing",
    emoji: "🛝",
    scene: "Two children reach the only open swing at the same time. Both want to go first.",
    prompt: "Which plan is most fair?",
    options: ["Agree on short turns or use a fair chooser", "Push to see who is stronger", "One child keeps it all recess"],
    answer: "Agree on short turns or use a fair chooser",
    hint: "A fair solution gives both children a predictable chance.",
    explanation: "Short turns or a neutral chooser solves the conflict without using force or excluding one child.",
    toolId: "fair-turn-planner",
    toolLabel: "Fair Turn Planner",
  },
  {
    id: "finder-no-hug",
    level: "Feelings Finder",
    skill: "conflict",
    setting: "Not Right Now",
    emoji: "🖐️",
    scene: "Rae does not want a hug right now. A friend opens their arms and steps closer.",
    prompt: "What can Rae say?",
    options: ["No hug, please. I can wave instead.", "I have to hug everyone", "Say nothing and feel trapped"],
    answer: "No hug, please. I can wave instead.",
    hint: "A boundary can be direct, respectful, and include another option.",
    explanation: "Rae is allowed to decline physical affection. A clear no and an alternative protect the boundary kindly.",
    toolId: "boundary-voice",
    toolLabel: "Boundary Voice",
  },
  {
    id: "builder-project-feedback",
    level: "Friendship Builder",
    skill: "emotions",
    setting: "The Project Feedback",
    emoji: "📋",
    scene: "Maya worked hard on a model. Her teacher says one section needs to be rebuilt. Maya feels disappointed, embarrassed, and still determined to improve it.",
    prompt: "What is the most accurate description?",
    options: ["Several feelings can happen together", "Only one feeling is allowed", "Determination means she is not disappointed"],
    answer: "Several feelings can happen together",
    hint: "Feelings do not cancel one another out.",
    explanation: "Maya can feel disappointed and embarrassed while also feeling determined. Mixed emotions are common during challenges.",
    toolId: "emotion-layer-detector",
    toolLabel: "Emotion Layer Detector",
  },
  {
    id: "builder-body-signals",
    level: "Friendship Builder",
    skill: "emotions",
    setting: "Before the Presentation",
    emoji: "🎤",
    scene: "Before speaking to the class, Eli notices a fast heartbeat, shaky knees, and many thoughts about making a mistake.",
    prompt: "What useful information do these body clues provide?",
    options: ["Eli may be anxious and can choose support", "Eli is definitely in danger", "Eli should ignore every body signal"],
    answer: "Eli may be anxious and can choose support",
    hint: "Body clues can help name a feeling, but they do not automatically prove danger.",
    explanation: "The clues may signal anxiety. Naming it helps Eli choose a strategy such as breathing, practicing, or asking to go second.",
    toolId: "body-clue-detective",
    toolLabel: "Body Clue Detective",
  },
  {
    id: "builder-game-loss",
    level: "Friendship Builder",
    skill: "regulation",
    setting: "The Close Game",
    emoji: "🎲",
    scene: "Dev loses a close board game. He feels an urge to accuse the winner of cheating even though he saw no cheating.",
    prompt: "Which response uses regulation before reaction?",
    options: ["Take a pause, name the disappointment, then congratulate the winner", "Make the accusation immediately", "Knock the game off the table"],
    answer: "Take a pause, name the disappointment, then congratulate the winner",
    hint: "The goal is not to erase disappointment. It is to choose an action that fits the facts.",
    explanation: "Dev can acknowledge the strong feeling while preventing it from becoming an unsupported accusation.",
    toolId: "feeling-action-gap",
    toolLabel: "Feeling-to-Action Gap",
  },
  {
    id: "builder-worry-plan",
    level: "Friendship Builder",
    skill: "regulation",
    setting: "Tomorrow's Field Trip",
    emoji: "🚌",
    scene: "Lena keeps imagining that she will forget something important for tomorrow's field trip.",
    prompt: "Which strategy best combines calming and problem-solving?",
    options: ["Make a short checklist, pack, then do a calming activity", "Stay awake worrying all night", "Refuse to think about the trip at all"],
    answer: "Make a short checklist, pack, then do a calming activity",
    hint: "Some worries need one practical step and then permission to stop rehearsing the problem.",
    explanation: "A checklist addresses the solvable part. A calming activity helps Lena stop repeating the worry after preparation is complete.",
    toolId: "worry-plan-separator",
    toolLabel: "Worry and Plan Separator",
  },
  {
    id: "builder-i-message",
    level: "Friendship Builder",
    skill: "communication",
    setting: "The Interrupted Story",
    emoji: "💬",
    scene: "Each time Theo tells a story, his friend interrupts before he reaches the ending.",
    prompt: "Which message is clearest and least blaming?",
    options: ["I feel frustrated when I am interrupted. Please let me finish.", "You are the worst listener ever", "Never talk again"],
    answer: "I feel frustrated when I am interrupted. Please let me finish.",
    hint: "Name the feeling, the specific behavior, and the request.",
    explanation: "The message describes the problem without attacking the friend's whole character and gives a clear request.",
    toolId: "i-message-builder",
    toolLabel: "I-Message Builder",
  },
  {
    id: "builder-check-understanding",
    level: "Friendship Builder",
    skill: "communication",
    setting: "The Science Directions",
    emoji: "🧪",
    scene: "Niko thinks his partner said to pour the blue liquid first, but the room was noisy and he is not sure.",
    prompt: "What should Niko say before acting?",
    options: ["I heard blue first. Is that right?", "I will guess", "You never explain anything"],
    answer: "I heard blue first. Is that right?",
    hint: "Reflect back what you heard and invite correction.",
    explanation: "A quick understanding check prevents a mistake and shows careful listening without blame.",
    toolId: "listening-loop",
    toolLabel: "Listening Loop",
  },
  {
    id: "builder-cancelled-plan",
    level: "Friendship Builder",
    skill: "empathy",
    setting: "The Cancelled Visit",
    emoji: "📅",
    scene: "Jun's friend cancels a visit because a grandparent is sick. Jun feels disappointed about the cancelled plan.",
    prompt: "Which response holds both perspectives?",
    options: ["I am disappointed, and I understand your family needs you", "My disappointment is the only thing that matters", "I am not allowed to feel disappointed"],
    answer: "I am disappointed, and I understand your family needs you",
    hint: "Empathy does not require deleting your own feeling.",
    explanation: "Jun can recognize his disappointment while also understanding the friend's difficult family situation.",
    toolId: "both-things-bridge",
    toolLabel: "Both-Things Bridge",
  },
  {
    id: "builder-quiet-partner",
    level: "Friendship Builder",
    skill: "empathy",
    setting: "The Quiet Partner",
    emoji: "🤝",
    scene: "During group work, Sal's partner speaks very little. Sal assumes the partner has no ideas, but notices several detailed notes on the page.",
    prompt: "What is the best next move?",
    options: ["Ask what ideas the partner would like to share", "Decide the partner does not care", "Take over without asking"],
    answer: "Ask what ideas the partner would like to share",
    hint: "Use curiosity before making a conclusion about another person's inner experience.",
    explanation: "The notes suggest the partner may have ideas but communicate differently. Asking creates space without guessing.",
    toolId: "curiosity-before-assumption",
    toolLabel: "Curiosity Before Assumption",
  },
  {
    id: "builder-shared-poster",
    level: "Friendship Builder",
    skill: "conflict",
    setting: "The Shared Poster",
    emoji: "🖼️",
    scene: "Two teammates both want to draw the title on a class poster. The deadline is close.",
    prompt: "Which solution protects the project and both teammates?",
    options: ["One sketches while the other colors, then switch roles on the next section", "Argue until time runs out", "Rip the poster in half"],
    answer: "One sketches while the other colors, then switch roles on the next section",
    hint: "Look for a plan that shares meaningful work and respects the deadline.",
    explanation: "Dividing and rotating roles addresses both people's wish to contribute while keeping the project moving.",
    toolId: "win-win-designer",
    toolLabel: "Win-Win Designer",
  },
  {
    id: "builder-teasing-boundary",
    level: "Friendship Builder",
    skill: "conflict",
    setting: "The Joke That Hurts",
    emoji: "🛑",
    scene: "A friend keeps using a nickname after Priya has said she does not like it. The friend says, 'I am only joking.'",
    prompt: "What is the strongest respectful response?",
    options: ["I asked you to stop. Do not use that name for me.", "Laugh so the friend is comfortable", "Use a hurtful nickname back"],
    answer: "I asked you to stop. Do not use that name for me.",
    hint: "Intent does not erase the other person's boundary.",
    explanation: "Priya can repeat the boundary clearly. A joke is not harmless when the targeted person has asked for it to stop.",
    toolId: "boundary-repeater",
    toolLabel: "Boundary Repeater",
  },
  {
    id: "solver-feedback-sting",
    level: "Calm Problem Solver",
    skill: "emotions",
    setting: "Useful Feedback That Stings",
    emoji: "📝",
    scene: "Amir receives accurate feedback that his argument needs evidence. He feels defensive and notices thoughts like, 'They think I am bad at everything.'",
    prompt: "Which interpretation is most balanced?",
    options: ["The feedback targets one skill, while the defensive feeling may be making it feel global", "The feedback proves Amir is bad at everything", "Accurate feedback should never feel uncomfortable"],
    answer: "The feedback targets one skill, while the defensive feeling may be making it feel global",
    hint: "Separate the feeling, the thought, and the actual scope of the feedback.",
    explanation: "The feeling is real, but the evidence concerns one part of one assignment. Naming that difference can reduce all-or-nothing thinking.",
    toolId: "feeling-fact-sorter",
    toolLabel: "Feeling and Fact Sorter",
  },
  {
    id: "solver-jealous-friend",
    level: "Calm Problem Solver",
    skill: "emotions",
    setting: "A Friend's Good News",
    emoji: "🏅",
    scene: "Sofia's friend wins an award Sofia also wanted. Sofia feels happy for her friend and jealous at the same time.",
    prompt: "What is the healthiest understanding of the jealousy?",
    options: ["It can reveal what Sofia values without requiring unkind behavior", "It makes Sofia a bad friend", "She must pretend the feeling does not exist"],
    answer: "It can reveal what Sofia values without requiring unkind behavior",
    hint: "A feeling can carry information without deciding the next action.",
    explanation: "Jealousy may show that achievement matters to Sofia. She can name it, congratulate her friend, and make her own growth plan.",
    toolId: "emotion-information-reader",
    toolLabel: "Emotion Information Reader",
  },
  {
    id: "solver-escalation-signs",
    level: "Calm Problem Solver",
    skill: "regulation",
    setting: "The Argument Is Climbing",
    emoji: "🌡️",
    scene: "During an argument, Mateo notices his voice getting louder, his thinking getting faster, and his urge to say something cruel increasing.",
    prompt: "What is the most effective next step?",
    options: ["Call a brief pause and agree on when to return", "Keep arguing until someone wins", "Leave forever without explanation"],
    answer: "Call a brief pause and agree on when to return",
    hint: "A useful pause lowers intensity and includes a plan to resume the conversation.",
    explanation: "A time-limited pause protects the relationship from impulsive harm without avoiding the issue permanently.",
    toolId: "temperature-check",
    toolLabel: "Conflict Temperature Check",
  },
  {
    id: "solver-control-circle",
    level: "Calm Problem Solver",
    skill: "regulation",
    setting: "The Weather Changes the Plan",
    emoji: "⛈️",
    scene: "A storm cancels an outdoor celebration that Rowan spent weeks planning. Rowan cannot change the weather but still has choices about what happens next.",
    prompt: "Which response focuses on what Rowan can control?",
    options: ["Name the disappointment and redesign an indoor version", "Demand that the storm stop", "Blame a friend for the weather"],
    answer: "Name the disappointment and redesign an indoor version",
    hint: "Separate the uncontrollable event from the choices still available.",
    explanation: "Rowan cannot control the storm, but can process the disappointment and direct effort toward a new plan.",
    toolId: "control-circle",
    toolLabel: "Circle of Control",
  },
  {
    id: "solver-hard-conversation",
    level: "Calm Problem Solver",
    skill: "communication",
    setting: "The Unequal Workload",
    emoji: "⚖️",
    scene: "In a group project, one student has completed most of the work. The deadline is tomorrow, and resentment is growing.",
    prompt: "Which opening is direct and solution-focused?",
    options: ["I am worried the work is uneven. Can we list what remains and assign it now?", "You are all lazy", "I will stay silent and complain later"],
    answer: "I am worried the work is uneven. Can we list what remains and assign it now?",
    hint: "State the observable problem, its effect, and a concrete next step.",
    explanation: "The opening is honest without attacking identities and immediately moves the group toward a workable plan.",
    toolId: "hard-conversation-opener",
    toolLabel: "Hard Conversation Opener",
  },
  {
    id: "solver-repair-listening",
    level: "Calm Problem Solver",
    skill: "communication",
    setting: "The Misunderstood Text",
    emoji: "📱",
    scene: "A short message sounded rude to Keira, but the sender says that was not the intention. Both people are upset.",
    prompt: "What communication move is most likely to clarify the problem?",
    options: ["Describe how the message landed, then ask what the sender meant", "Assume the worst intention", "Post the message publicly"],
    answer: "Describe how the message landed, then ask what the sender meant",
    hint: "Separate impact from assumed intent and invite more information.",
    explanation: "Keira can honor the impact while checking the sender's intended meaning. That creates better evidence for repair.",
    toolId: "impact-intent-bridge",
    toolLabel: "Impact and Intent Bridge",
  },
  {
    id: "solver-excluded-friend",
    level: "Calm Problem Solver",
    skill: "empathy",
    setting: "The Changed Lunch Table",
    emoji: "🥪",
    scene: "A friend becomes quiet after the group changes tables without telling them. The group did not mean to exclude anyone, but the friend ate alone.",
    prompt: "Which response shows empathy and accountability?",
    options: ["We did not mean to exclude you, but I see that you were left alone. I am sorry.", "You should not feel excluded because it was accidental", "Intent is the only thing that matters"],
    answer: "We did not mean to exclude you, but I see that you were left alone. I am sorry.",
    hint: "A strong repair can name both intention and impact without using intention to erase impact.",
    explanation: "The response acknowledges what happened, takes responsibility for the impact, and opens the door to repair.",
    toolId: "accountable-empathy",
    toolLabel: "Accountable Empathy",
  },
  {
    id: "solver-different-risk",
    level: "Calm Problem Solver",
    skill: "empathy",
    setting: "The High Climbing Wall",
    emoji: "🧗",
    scene: "Leah loves the high climbing wall. Her friend freezes halfway up and asks to come down. Leah thinks the wall is easy.",
    prompt: "What response respects the friend's perspective?",
    options: ["You can come down. Do you want support or a lower route?", "It is easy for me, so it must be easy for you", "Keep climbing or we are not friends"],
    answer: "You can come down. Do you want support or a lower route?",
    hint: "Another person's fear does not need to match yours to deserve respect.",
    explanation: "Leah validates the friend's choice and offers support without pressure or ridicule.",
    toolId: "difference-respecter",
    toolLabel: "Difference Respecter",
  },
  {
    id: "solver-apology-repair",
    level: "Calm Problem Solver",
    skill: "conflict",
    setting: "The Damaged Model",
    emoji: "🛠️",
    scene: "Noah carelessly bumps a classmate's model and breaks a piece. He says, 'Sorry you are upset.'",
    prompt: "Which repair is stronger?",
    options: ["I broke the piece when I was careless. I am sorry. How can I help repair it?", "Sorry you feel that way", "Pretend it did not happen"],
    answer: "I broke the piece when I was careless. I am sorry. How can I help repair it?",
    hint: "A repair names the action, takes responsibility, and offers a meaningful next step.",
    explanation: "The stronger apology does not blame the injured person's feelings. It owns the behavior and offers repair.",
    toolId: "repair-builder",
    toolLabel: "Repair Builder",
  },
  {
    id: "solver-boundary-consequence",
    level: "Calm Problem Solver",
    skill: "conflict",
    setting: "The Shared Password",
    emoji: "🔒",
    scene: "A friend keeps asking for a private account password after being told no. The friend says sharing would prove trust.",
    prompt: "Which response protects the boundary and the relationship most clearly?",
    options: ["I do not share passwords. Please stop asking. We can choose another way to show trust.", "Give the password to avoid conflict", "Share it and change it secretly later"],
    answer: "I do not share passwords. Please stop asking. We can choose another way to show trust.",
    hint: "A healthy boundary does not require surrendering privacy to prove friendship.",
    explanation: "The response is direct, protects digital privacy, and offers a safer way to maintain connection.",
    toolId: "safe-boundary-plan",
    toolLabel: "Safe Boundary Plan",
  },
];

export function wellbeingMissionById(id: string): WellbeingMission | null {
  return WELLBEING_MISSIONS.find((mission) => mission.id === id) ?? null;
}
