export type LifeSkillsLevel = "Helper" | "Independent Starter" | "Life Planner";
export type LifeSkillsSkill = "routines" | "organization" | "food" | "home" | "communication";

export type LifeSkillsMission = {
  id: string;
  level: LifeSkillsLevel;
  skill: LifeSkillsSkill;
  emoji: string;
  title: string;
  scene: string;
  prompt: string;
  options: string[];
  answer: string;
  hint: string;
  explanation: string;
  toolId: string;
  toolLabel: string;
};

export const LIFE_SKILLS: Record<LifeSkillsSkill, { id: string; label: string }> = {
  routines: { id: "life-routines-time", label: "Routines and time planning" },
  organization: { id: "life-organization", label: "Organization and task setup" },
  food: { id: "life-food-prep", label: "Simple food preparation" },
  home: { id: "life-home-responsibility", label: "Household responsibility" },
  communication: { id: "life-help-communication", label: "Asking for help and communicating needs" },
};

export const LIFE_SKILLS_MISSIONS: LifeSkillsMission[] = [
  { id:"helper-morning", level:"Helper", skill:"routines", emoji:"⏰", title:"Morning Order", scene:"Shoes are on, but the backpack is still open and the water bottle is on the counter.", prompt:"What should happen before leaving?", options:["Put the bottle in the backpack and close it","Leave quickly and hope","Empty the backpack"], answer:"Put the bottle in the backpack and close it", hint:"Finish the parts that make the school bag ready.", explanation:"A short final check prevents forgotten items and makes the routine complete.", toolId:"ready-check", toolLabel:"Ready Check" },
  { id:"helper-timer", level:"Helper", skill:"routines", emoji:"⏳", title:"Five-Minute Finish", scene:"Cleanup time starts in five minutes, but toys are spread across the floor.", prompt:"What is the best first move?", options:["Start with one toy group now","Wait until the timer ends","Hide everything under a blanket"], answer:"Start with one toy group now", hint:"Use the available time instead of waiting for urgency.", explanation:"Starting one clear category turns a vague task into a manageable routine.", toolId:"start-now", toolLabel:"Start-Now Move" },
  { id:"helper-home-spot", level:"Helper", skill:"organization", emoji:"🧺", title:"A Home for Everything", scene:"Crayons are often lost because they are left in different rooms.", prompt:"What system would help most?", options:["Keep them in one labeled box","Buy new crayons every day","Remember every location"], answer:"Keep them in one labeled box", hint:"Good systems reduce the need to remember many places.", explanation:"A consistent home makes cleanup and finding supplies easier.", toolId:"one-home", toolLabel:"One-Home System" },
  { id:"helper-snack", level:"Helper", skill:"food", emoji:"🍎", title:"Simple Snack", scene:"A child wants apple slices and yogurt. A clean spoon, bowl, and washed apple are available.", prompt:"What should happen before eating?", options:["Wash hands and prepare food on a clean surface","Use an unknown knife alone","Eat from the floor"], answer:"Wash hands and prepare food on a clean surface", hint:"Think clean hands, clean surface, and age-safe tools.", explanation:"Basic hygiene and safe tools are the foundation of simple food preparation.", toolId:"clean-prep", toolLabel:"Clean Prep" },
  { id:"helper-spill", level:"Helper", skill:"home", emoji:"🧻", title:"Small Spill", scene:"Water spills on the kitchen floor and makes a slippery patch.", prompt:"What is the best response?", options:["Tell an adult and wipe it up safely","Walk away","Cover it with a toy"], answer:"Tell an adult and wipe it up safely", hint:"The goal is to prevent someone from slipping.", explanation:"Prompt cleanup and adult help remove the hazard instead of hiding it.", toolId:"hazard-fix", toolLabel:"Notice and Fix" },
  { id:"helper-help", level:"Helper", skill:"communication", emoji:"🙋", title:"Clear Help Request", scene:"A zipper is stuck and pulling harder is not working.", prompt:"What should the child say?", options:["Can you help me unstick this zipper?","This is impossible!","Say nothing and yank harder"], answer:"Can you help me unstick this zipper?", hint:"Name the problem and the help needed.", explanation:"A specific request makes it easier for another person to help.", toolId:"clear-request", toolLabel:"Clear Help Request" },
  { id:"independent-backward", level:"Independent Starter", skill:"routines", emoji:"🗓️", title:"Plan Backward", scene:"A project is due Friday. It needs research, a draft, and a final check.", prompt:"Which plan is strongest?", options:["Research Tuesday, draft Wednesday, check Thursday","Do everything Friday morning","Wait for someone to remind you"], answer:"Research Tuesday, draft Wednesday, check Thursday", hint:"Leave time for each stage and a final check.", explanation:"Planning backward spreads work across manageable steps and protects review time.", toolId:"backward-plan", toolLabel:"Backward Planner" },
  { id:"independent-launchpad", level:"Independent Starter", skill:"organization", emoji:"🎒", title:"Launch Pad", scene:"Keys, backpack, and permission slip are often forgotten in the morning.", prompt:"What system would reduce forgetting?", options:["Place them together by the door the night before","Keep them in random rooms","Rely on panic"], answer:"Place them together by the door the night before", hint:"Group tomorrow's essential items in one visible place.", explanation:"A launch pad reduces morning decisions and memory load.", toolId:"launch-pad", toolLabel:"Launch Pad" },
  { id:"independent-label", level:"Independent Starter", skill:"food", emoji:"🥛", title:"Check Before Using", scene:"Milk in the refrigerator smells unusual and the date has passed.", prompt:"What should happen?", options:["Ask an adult and do not use it","Taste a large amount","Mix it into food to hide the smell"], answer:"Ask an adult and do not use it", hint:"When food seems unsafe, stop instead of testing it by eating.", explanation:"Questionable food should not be consumed; an adult can decide how to discard it safely.", toolId:"food-stop-check", toolLabel:"Food Stop Check" },
  { id:"independent-laundry", level:"Independent Starter", skill:"home", emoji:"👕", title:"Laundry Sort", scene:"A red new shirt is mixed with white clothes for the first wash.", prompt:"What is the safest plan?", options:["Ask about washing it separately or with similar colors","Use the hottest setting without checking","Add bleach"], answer:"Ask about washing it separately or with similar colors", hint:"New dark or bright fabric may release color.", explanation:"Sorting and checking care instructions helps prevent color transfer and damage.", toolId:"care-label-check", toolLabel:"Care Label Check" },
  { id:"independent-update", level:"Independent Starter", skill:"communication", emoji:"📣", title:"Give an Update", scene:"A task will take longer than expected and another person is waiting.", prompt:"What is the responsible response?", options:["Explain the delay and give a new realistic time","Disappear","Promise it is already done"], answer:"Explain the delay and give a new realistic time", hint:"Good communication includes the problem and the revised plan.", explanation:"An honest update lets other people adjust and rebuilds reliability.", toolId:"status-update", toolLabel:"Status Update" },
  { id:"planner-priority", level:"Life Planner", skill:"routines", emoji:"🎯", title:"Important Before Urgent", scene:"Homework is due tomorrow, laundry is needed in three days, and a game event starts now.", prompt:"Which choice protects the most important commitment?", options:["Finish the due homework before joining the game","Ignore homework","Wash every item before homework"], answer:"Finish the due homework before joining the game", hint:"Compare deadlines and consequences.", explanation:"Priority planning considers urgency, importance, and consequences rather than whichever activity is loudest.", toolId:"priority-filter", toolLabel:"Priority Filter" },
  { id:"planner-reset", level:"Life Planner", skill:"organization", emoji:"🔄", title:"Weekly Reset", scene:"Papers, chargers, and supplies have accumulated in several places over the week.", prompt:"What is the best maintenance system?", options:["Schedule a short weekly reset","Wait until nothing can be found","Create more random piles"], answer:"Schedule a short weekly reset", hint:"Systems work better with regular maintenance.", explanation:"A recurring reset prevents small disorder from becoming a crisis.", toolId:"weekly-reset", toolLabel:"Weekly Reset" },
  { id:"planner-recipe", level:"Life Planner", skill:"food", emoji:"🥣", title:"Read the Whole Recipe", scene:"A recipe has six steps and needs the oven preheated before mixing begins.", prompt:"What should happen first?", options:["Read the full recipe and gather ingredients","Mix immediately","Turn on equipment without understanding the steps"], answer:"Read the full recipe and gather ingredients", hint:"Preparation reveals timing, missing items, and adult-help steps.", explanation:"Reading first prevents surprises and identifies where supervision or special tools are needed.", toolId:"recipe-preview", toolLabel:"Recipe Preview" },
  { id:"planner-shared-space", level:"Life Planner", skill:"home", emoji:"🏠", title:"Shared Space Standard", scene:"One person finishes a craft at the dining table, but another person needs the table for dinner.", prompt:"What shows responsibility for the shared space?", options:["Restore the table to a usable condition","Leave supplies because the craft matters more","Move the mess onto a chair"], answer:"Restore the table to a usable condition", hint:"Shared spaces should be ready for the next agreed use.", explanation:"Responsibility includes restoring common spaces, not merely finishing one's own activity.", toolId:"restore-space", toolLabel:"Restore the Space" },
  { id:"planner-boundary-help", level:"Life Planner", skill:"communication", emoji:"🧭", title:"Ask Early, Not Too Late", scene:"Instructions are unclear, but the task is due soon. Guessing could waste an hour.", prompt:"What is the strongest next move?", options:["Ask a focused question now","Wait until the deadline passes","Pretend to understand"], answer:"Ask a focused question now", hint:"Early clarification protects time and quality.", explanation:"Independent people still ask for help; they do it clearly and early enough to use the answer.", toolId:"early-clarifier", toolLabel:"Early Clarifier" },
];

export function lifeSkillsMissionById(id: string): LifeSkillsMission | null {
  return LIFE_SKILLS_MISSIONS.find((mission) => mission.id === id) ?? null;
}
