import type { CurriculumStandard } from "@/lib/adrian-curriculum";

// Curated priority standards for the AdrianOS elementary product.
// Grade 2 remains in adrian-curriculum.ts because it was the first detailed cohort pack.
// These are intentionally a focused, playable subset rather than a claim of exhaustive coverage.
export const ELEMENTARY_PRIORITY_STANDARDS: CurriculumStandard[] = [
  // Transitional Kindergarten foundations. California TK uses developmentally appropriate
  // foundations rather than Common Core grade codes, so AdrianOS uses transparent TK labels.
  { code: "TK.MATH.1", framework: "CA TK Foundations", grade: -1, subject: "Math", title: "Count, match, and compare small groups", childGoal: "I can count objects carefully and tell which group has more, less, or the same.", skillIds: ["math-counting"], strength: "direct" },
  { code: "TK.MATH.2", framework: "CA TK Foundations", grade: -1, subject: "Math", title: "Put together and take apart small numbers", childGoal: "I can show different ways to make a small number.", skillIds: ["math-addition"], strength: "supporting" },
  { code: "TK.ELA.1", framework: "CA TK Foundations", grade: -1, subject: "Reading", title: "Listen, remember, and retell", childGoal: "I can tell what happened first, next, and last in a short story.", skillIds: ["reading-sequencing"], strength: "supporting" },
  { code: "TK.ELA.2", framework: "CA TK Foundations", grade: -1, subject: "Reading", title: "Notice letters, sounds, and rhymes", childGoal: "I can notice sounds in words and connect familiar sounds to letters.", skillIds: ["reading-spelling-easy"], strength: "supporting" },
  { code: "TK.W.1", framework: "CA TK Foundations", grade: -1, subject: "Reading", title: "Draw, dictate, and tell an idea", childGoal: "I can draw or tell an idea and add a useful detail.", skillIds: ["writing-ideas"], strength: "direct" },
  { code: "TK.SCI.1", framework: "CA TK Foundations", grade: -1, subject: "Science", title: "Observe patterns in the world", childGoal: "I can look closely, describe what I notice, and find a pattern.", skillIds: ["science-earth", "logic-patterns"], strength: "supporting" },

  // Kindergarten
  { code: "K.CC.A.1", framework: "CA CCSS Math", grade: 0, subject: "Math", title: "Count to 100 by ones and tens", childGoal: "I can count forward and notice the pattern made by groups of ten.", skillIds: ["math-counting"], strength: "direct" },
  { code: "K.CC.B.4", framework: "CA CCSS Math", grade: 0, subject: "Math", title: "Connect counting to quantity", childGoal: "I can count each object once and know the last number tells how many.", skillIds: ["math-counting"], strength: "direct" },
  { code: "K.OA.A.1", framework: "CA CCSS Math", grade: 0, subject: "Math", title: "Represent addition and subtraction", childGoal: "I can use pictures, objects, or equations to show putting together and taking apart.", skillIds: ["math-addition", "math-subtraction"], strength: "direct" },
  { code: "K.G.A.2", framework: "CA CCSS Math", grade: 0, subject: "Math", title: "Name shapes in different positions and sizes", childGoal: "I can recognize a shape even when it is turned, moved, or resized.", skillIds: ["math-geometry"], strength: "direct" },
  { code: "RL.K.1", framework: "CA CCSS ELA", grade: 0, subject: "Reading", title: "Ask and answer questions about a story", childGoal: "I can answer a question using something that happened in the story.", skillIds: ["reading-comprehension-detail"], strength: "direct" },
  { code: "RF.K.2", framework: "CA CCSS ELA", grade: 0, subject: "Reading", title: "Hear words, syllables, and sounds", childGoal: "I can notice rhymes, syllables, and beginning or ending sounds.", skillIds: ["reading-spelling-easy"], strength: "supporting" },
  { code: "W.K.3", framework: "CA CCSS ELA", grade: 0, subject: "Reading", title: "Tell events in order", childGoal: "I can draw, dictate, or write about events in the order they happened.", skillIds: ["writing-ideas", "writing-sentences"], strength: "direct" },
  { code: "K-PS2-1", framework: "CA NGSS", grade: 0, subject: "Science", title: "Compare pushes and pulls", childGoal: "I can test how different pushes or pulls change an object’s motion.", skillIds: ["engineering-iteration", "science-technology"], strength: "supporting" },
  { code: "K-LS1-1", framework: "CA NGSS", grade: 0, subject: "Science", title: "What living things need", childGoal: "I can use observations to explain what plants and animals need to live.", skillIds: ["environment-ecosystems", "science-body"], strength: "supporting" },

  // Grade 1
  { code: "1.OA.A.1", framework: "CA CCSS Math", grade: 1, subject: "Math", title: "Solve addition and subtraction story problems", childGoal: "I can choose addition or subtraction to solve a story problem within 20.", skillIds: ["math-word-problems", "math-addition", "math-subtraction"], strength: "direct" },
  { code: "1.OA.C.6", framework: "CA CCSS Math", grade: 1, subject: "Math", title: "Add and subtract within 20", childGoal: "I can use a strategy to add and subtract accurately within 20.", skillIds: ["math-addition", "math-subtraction"], strength: "direct" },
  { code: "1.NBT.B.2", framework: "CA CCSS Math", grade: 1, subject: "Math", title: "Understand tens and ones", childGoal: "I can explain how a two-digit number is made of tens and ones.", skillIds: ["math-place-value"], strength: "direct" },
  { code: "1.MD.A.1", framework: "CA CCSS Math", grade: 1, subject: "Math", title: "Compare and order lengths", childGoal: "I can compare lengths and put objects in order from shortest to longest.", skillIds: ["math-measurement"], strength: "direct" },
  { code: "RL.1.1", framework: "CA CCSS ELA", grade: 1, subject: "Reading", title: "Use story details in an answer", childGoal: "I can answer who, what, where, when, why, and how questions with story details.", skillIds: ["reading-comprehension-detail"], strength: "direct" },
  { code: "RF.1.3", framework: "CA CCSS ELA", grade: 1, subject: "Reading", title: "Use grade-level phonics and word patterns", childGoal: "I can use letter patterns and sounds to read or build unfamiliar words.", skillIds: ["reading-spelling-easy", "reading-spelling-medium"], strength: "direct" },
  { code: "W.1.3", framework: "CA CCSS ELA", grade: 1, subject: "Reading", title: "Write a short sequenced narrative", childGoal: "I can write events in order and include details about what happened.", skillIds: ["writing-ideas", "writing-sentences", "writing-organization"], strength: "direct" },
  { code: "1-PS4-1", framework: "CA NGSS", grade: 1, subject: "Science", title: "Investigate sound and vibration", childGoal: "I can use evidence to explain that vibrating materials can make sound.", skillIds: ["creativity-rhythm", "science-technology"], strength: "supporting" },
  { code: "1-LS1-1", framework: "CA NGSS", grade: 1, subject: "Science", title: "Design a solution inspired by living things", childGoal: "I can notice how a plant or animal solves a problem and use the idea in a design.", skillIds: ["engineering-structures", "engineering-iteration"], strength: "supporting" },

  // Grade 3
  { code: "3.OA.A.1", framework: "CA CCSS Math", grade: 3, subject: "Math", title: "Interpret products of whole numbers", childGoal: "I can explain multiplication as equal groups or an array.", skillIds: ["math-multiplication"], strength: "direct" },
  { code: "3.OA.B.6", framework: "CA CCSS Math", grade: 3, subject: "Math", title: "Understand division as an unknown factor", childGoal: "I can connect a division problem to a related multiplication fact.", skillIds: ["math-division", "math-multiplication"], strength: "direct" },
  { code: "3.OA.C.7", framework: "CA CCSS Math", grade: 3, subject: "Math", title: "Multiply and divide within 100", childGoal: "I can use patterns and strategies to solve multiplication and division facts.", skillIds: ["math-multiplication", "math-division"], strength: "direct" },
  { code: "3.NF.A.1", framework: "CA CCSS Math", grade: 3, subject: "Math", title: "Understand unit fractions", childGoal: "I can explain a fraction as equal parts of one whole.", skillIds: ["math-fractions"], strength: "direct" },
  { code: "3.MD.B.3", framework: "CA CCSS Math", grade: 3, subject: "Math", title: "Represent and interpret data", childGoal: "I can read a graph and solve one- or two-step questions about its data.", skillIds: ["math-measurement", "logic-multi-step"], strength: "supporting" },
  { code: "RL.3.1", framework: "CA CCSS ELA", grade: 3, subject: "Reading", title: "Refer explicitly to a text", childGoal: "I can point to the part of a story that supports my answer.", skillIds: ["reading-comprehension-detail", "reading-inference"], strength: "direct" },
  { code: "RI.3.3", framework: "CA CCSS ELA", grade: 3, subject: "Reading", title: "Connect events, ideas, and procedures", childGoal: "I can explain how events, ideas, or steps connect in an informational text.", skillIds: ["reading-sequencing", "reading-comprehension-detail"], strength: "direct" },
  { code: "W.3.2", framework: "CA CCSS ELA", grade: 3, subject: "Reading", title: "Write an informative explanation", childGoal: "I can organize facts and explain a topic clearly.", skillIds: ["writing-ideas", "writing-organization", "writing-revision"], strength: "direct" },
  { code: "3-PS2-1", framework: "CA NGSS", grade: 3, subject: "Science", title: "Investigate balanced and unbalanced forces", childGoal: "I can plan an investigation and use evidence to explain changes in motion.", skillIds: ["science-technology", "engineering-iteration"], strength: "supporting" },
  { code: "3-LS1-1", framework: "CA NGSS", grade: 3, subject: "Science", title: "Model life cycles", childGoal: "I can use a model to compare stages in the life cycles of living things.", skillIds: ["science-body", "environment-ecosystems"], strength: "supporting" },
  { code: "3-5-ETS1-1", framework: "CA NGSS", grade: 3, subject: "Science", title: "Define a design problem", childGoal: "I can describe a problem, the goal, and the limits a solution must follow.", skillIds: ["engineering-iteration", "engineering-materials"], strength: "direct" },

  // Grade 4
  { code: "4.OA.A.3", framework: "CA CCSS Math", grade: 4, subject: "Math", title: "Solve multi-step whole-number problems", childGoal: "I can choose operations, solve a multi-step problem, and check whether my answer makes sense.", skillIds: ["math-word-problems", "logic-multi-step"], strength: "direct" },
  { code: "4.NBT.B.4", framework: "CA CCSS Math", grade: 4, subject: "Math", title: "Add and subtract multi-digit numbers", childGoal: "I can add and subtract whole numbers accurately using place value.", skillIds: ["math-place-value", "math-addition", "math-subtraction"], strength: "direct" },
  { code: "4.NBT.B.5", framework: "CA CCSS Math", grade: 4, subject: "Math", title: "Multiply multi-digit whole numbers", childGoal: "I can multiply using place value, partial products, or an area model.", skillIds: ["math-multiplication", "math-place-value"], strength: "direct" },
  { code: "4.NF.A.1", framework: "CA CCSS Math", grade: 4, subject: "Math", title: "Recognize equivalent fractions", childGoal: "I can explain why two fractions can name the same amount.", skillIds: ["math-fractions"], strength: "direct" },
  { code: "4.MD.A.3", framework: "CA CCSS Math", grade: 4, subject: "Math", title: "Use area and perimeter formulas", childGoal: "I can solve real problems involving the area and perimeter of rectangles.", skillIds: ["math-measurement", "math-geometry"], strength: "direct" },
  { code: "RL.4.1", framework: "CA CCSS ELA", grade: 4, subject: "Reading", title: "Use details and examples as evidence", childGoal: "I can use exact details and examples to explain what a text says or implies.", skillIds: ["reading-comprehension-detail", "reading-inference"], strength: "direct" },
  { code: "RI.4.5", framework: "CA CCSS ELA", grade: 4, subject: "Reading", title: "Describe informational text structure", childGoal: "I can recognize sequence, cause and effect, comparison, and problem-solution structures.", skillIds: ["reading-sequencing", "history-cause-effect"], strength: "supporting" },
  { code: "W.4.2", framework: "CA CCSS ELA", grade: 4, subject: "Reading", title: "Develop an informative text", childGoal: "I can organize information, explain ideas, and revise for clarity.", skillIds: ["writing-organization", "writing-revision", "writing-conventions"], strength: "direct" },
  { code: "4-PS3-1", framework: "CA NGSS", grade: 4, subject: "Science", title: "Use evidence about energy and motion", childGoal: "I can explain how an object’s speed relates to its energy.", skillIds: ["science-technology"], strength: "supporting" },
  { code: "4-LS1-1", framework: "CA NGSS", grade: 4, subject: "Science", title: "Explain how structures support survival", childGoal: "I can argue from evidence that plant and animal structures help living things survive and grow.", skillIds: ["science-body", "environment-ecosystems"], strength: "supporting" },
  { code: "4-ESS1-1", framework: "CA NGSS", grade: 4, subject: "Science", title: "Use rock evidence to explain landscape change", childGoal: "I can use patterns in rocks and fossils to explain how a landscape changed over time.", skillIds: ["science-earth", "history-sources-evidence"], strength: "supporting" },

  // Grade 5
  { code: "5.OA.A.1", framework: "CA CCSS Math", grade: 5, subject: "Math", title: "Use grouping symbols in numerical expressions", childGoal: "I can use parentheses and brackets to show which calculation happens first.", skillIds: ["logic-multi-step", "math-multiplication"], strength: "supporting" },
  { code: "5.NBT.A.3", framework: "CA CCSS Math", grade: 5, subject: "Math", title: "Read, write, and compare decimals", childGoal: "I can use place value to read, write, and compare decimals to thousandths.", skillIds: ["math-decimals", "math-place-value"], strength: "direct" },
  { code: "5.NBT.B.5", framework: "CA CCSS Math", grade: 5, subject: "Math", title: "Fluently multiply multi-digit whole numbers", childGoal: "I can multiply multi-digit whole numbers accurately and explain my method.", skillIds: ["math-multiplication"], strength: "direct" },
  { code: "5.NF.A.1", framework: "CA CCSS Math", grade: 5, subject: "Math", title: "Add and subtract fractions with unlike denominators", childGoal: "I can find equivalent fractions and use them to add or subtract.", skillIds: ["math-fractions"], strength: "direct" },
  { code: "5.MD.C.3", framework: "CA CCSS Math", grade: 5, subject: "Math", title: "Understand volume", childGoal: "I can measure volume with unit cubes and connect it to multiplication.", skillIds: ["math-measurement", "math-geometry", "math-multiplication"], strength: "direct" },
  { code: "RL.5.1", framework: "CA CCSS ELA", grade: 5, subject: "Reading", title: "Quote accurately from a text", childGoal: "I can quote or point to exact evidence when explaining a text.", skillIds: ["reading-comprehension-detail", "reading-inference"], strength: "direct" },
  { code: "RI.5.8", framework: "CA CCSS ELA", grade: 5, subject: "Reading", title: "Explain how reasons and evidence support claims", childGoal: "I can identify a claim and explain whether the evidence actually supports it.", skillIds: ["reading-inference", "history-sources-evidence", "civics-information-literacy"], strength: "supporting" },
  { code: "W.5.2", framework: "CA CCSS ELA", grade: 5, subject: "Reading", title: "Write a clear informative text", childGoal: "I can organize information, connect ideas, use precise language, and revise my explanation.", skillIds: ["writing-organization", "writing-revision", "writing-conventions"], strength: "direct" },
  { code: "5-PS1-1", framework: "CA NGSS", grade: 5, subject: "Science", title: "Model matter as particles", childGoal: "I can use a model to explain that matter is made of particles too small to see.", skillIds: ["engineering-materials", "science-technology"], strength: "supporting" },
  { code: "5-PS2-1", framework: "CA NGSS", grade: 5, subject: "Science", title: "Support an argument about gravity", childGoal: "I can use evidence to support the idea that Earth’s gravity pulls objects downward.", skillIds: ["science-space"], strength: "supporting" },
  { code: "5-LS1-1", framework: "CA NGSS", grade: 5, subject: "Science", title: "Explain where plants get materials for growth", childGoal: "I can use evidence to explain that plants get most growth material from air and water.", skillIds: ["environment-ecosystems"], strength: "supporting" },
  { code: "5-ESS1-1", framework: "CA NGSS", grade: 5, subject: "Science", title: "Compare the brightness of stars and the sun", childGoal: "I can explain how distance affects how bright stars appear from Earth.", skillIds: ["science-space"], strength: "supporting" },
];
