"use client";
import GameFrame from "@/components/GameFrame";
import Link from "next/link";
import {useState} from "react";
const Q=[
["Which organ pumps blood around your body?",["Heart","Lungs","Stomach","Brain"],0,"The heart is a powerful muscle that pumps blood."],
["Which organs help you breathe?",["Kidneys","Lungs","Bones","Skin"],1,"Your lungs bring oxygen into your body."],
["Which organ helps you think and remember?",["Brain","Liver","Heart","Bladder"],0,"Your brain controls thoughts, memory, movement, and senses."],
["What protects your brain?",["Ribs","Skull","Muscles","Hair"],1,"The skull is a hard helmet made of bone."],
["Which body part helps digest food?",["Stomach","Elbow","Ear","Ankle"],0,"The stomach mixes food with digestive juices."],
["What carries messages between your brain and body?",["Nerves","Teeth","Nails","Sweat"],0,"Nerves carry electrical messages throughout your body."]
] as const;
export default function Page(){const[i,setI]=useState(0),[choice,setChoice]=useState<number|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false);const q=Q[i];function pick(x:number){if(choice!==null)return;setChoice(x);if(x===q[2])setScore(s=>s+1)}function next(){if(i===Q.length-1)setDone(true);else{setI(v=>v+1);setChoice(null)}}return <GameFrame title="Human Body Explorer">{done?<section style={finish}><div style={{fontSize:64}}>🫀</div><h1 style={title}>Body Mission Complete</h1><p style={muted}>Score: {score} out of {Q.length}</p><Link href="/" style={home}>Go Home</Link></section>:<main style={wrap}><div style={stats}><span>Question {i+1} of {Q.length}</span><span>Score {score}</span></div><section style={card}><div style={{fontSize:64}}>🧠</div><small style={eye}>HUMAN BODY EXPLORER</small><h1 style={question}>{q[0]}</h1><div style={{display:"grid",gap:10}}>{q[1].map((a,x)=>{const ok=choice!==null&&x===q[2],bad=choice===x&&x!==q[2];return <button key={a} onClick={()=>pick(x)} style={{...answer,background:ok?"#d9ff5b":bad?"#ffb5bf":"#222936",color:ok||bad?"#10131b":"#fff"}}>{a}</button>})}</div>{choice!==null&&<div style={feedback}><strong>{choice===q[2]?"Correct.":"Good try."}</strong><p style={muted}>{q[3]}</p><button onClick={next} style={primary}>{i===Q.length-1?"See results":"Next question"}</button></div>}</section></main>}</GameFrame>}
const wrap:React.CSSProperties={width:"min(820px,100%)",margin:"0 auto"},stats:React.CSSProperties={display:"flex",justifyContent:"space-between",marginBottom:14,color:"#aab1bf",fontWeight:800},card:React.CSSProperties={padding:"clamp(24px,5vw,50px)",borderRadius:30,background:"#181d28",border:"1px solid rgba(255,255,255,.11)",textAlign:"center"},eye:React.CSSProperties={color:"#d9ff5b",fontWeight:950,letterSpacing:2},question:React.CSSProperties={fontSize:"clamp(2rem,6vw,4rem)",lineHeight:1,letterSpacing:"-.055em",margin:"12px 0 26px"},answer:React.CSSProperties={minHeight:64,borderRadius:18,border:"1px solid rgba(255,255,255,.13)",fontSize:18,fontWeight:900,cursor:"pointer"},feedback:React.CSSProperties={marginTop:20,paddingTop:20,borderTop:"1px solid rgba(255,255,255,.11)"},primary:React.CSSProperties={border:0,borderRadius:999,padding:"12px 18px",background:"#d9ff5b",color:"#10131b",fontWeight:950,cursor:"pointer"},muted:React.CSSProperties={color:"#aab1bf",lineHeight:1.55},finish:React.CSSProperties={width:"min(720px,100%)",margin:"0 auto",padding:"clamp(30px,7vw,70px)",borderRadius:30,background:"#181d28",textAlign:"center"},title:React.CSSProperties={fontSize:"clamp(2.6rem,7vw,5rem)",lineHeight:.95,letterSpacing:"-.06em"},home:React.CSSProperties={display:"inline-block",padding:"13px 20px",borderRadius:999,background:"#d9ff5b",color:"#10131b",fontWeight:950,textDecoration:"none"};