"use client";

import GameFrame from "@/components/GameFrame";
import { recordLearningAttempt } from "@/lib/adrian-learning";
import { useFamilyProfiles } from "@/lib/adrian-profiles";
import { useGameSession } from "@/lib/game-session";
import Link from "next/link";
import { useMemo, useState } from "react";

const GAME_SLUG = "mystery-temple";
type Stage = "intro" | "map" | "play" | "vault" | "finish";
type Feedback = "question" | "hint" | "explanation";
type Relic = "lens" | "boots" | "compass";
type Puzzle = { room: string; emoji: string; subject: "Math" | "Reading" | "Science"; standard: string; skillId: string; skillLabel: string; story: string; prompt: string; choices: string[]; answer: string; hint: string; explanation: string; rune: string };

const RELICS = {
  lens: { name: "Oracle Lens", emoji: "🔎", power: "Two free clues", text: "Reveal clues without breaking your streak." },
  boots: { name: "Echo Boots", emoji: "🥾", power: "Trap shield", text: "Ignore the first wrong-answer trap." },
  compass: { name: "Sun Compass", emoji: "🧭", power: "Treasure boost", text: "First-try solves earn an extra gem." },
};

const PUZZLES: Puzzle[] = [
  { room: "Fraction Falls", emoji: "🌊", subject: "Math", standard: "4.NF.A.1", skillId: "math-equivalent-fractions", skillLabel: "Recognize equivalent fractions", story: "A stone bridge shows 3/4 of its tiles glowing.", prompt: "Which fraction is equivalent to 3/4?", choices: ["6/8", "4/7", "3/8", "9/16"], answer: "6/8", hint: "Multiply the numerator and denominator by the same number.", explanation: "3/4 × 2/2 = 6/8, so the fractions are equivalent.", rune: "💧 Water rune" },
  { room: "Hall of Whispers", emoji: "📜", subject: "Reading", standard: "RL.4.1", skillId: "reading-text-evidence", skillLabel: "Use text evidence", story: "Lina packed a torch, rope, and map before entering the dark tunnel.", prompt: "Which detail best shows Lina prepared carefully?", choices: ["She packed a torch, rope, and map", "The tunnel was dark", "Her name was Lina", "She entered the tunnel"], answer: "She packed a torch, rope, and map", hint: "Choose the detail that directly proves preparation.", explanation: "Packing several useful tools is direct evidence that Lina prepared carefully.", rune: "📜 Story rune" },
  { room: "Crystal Quarry", emoji: "💎", subject: "Math", standard: "4.NBT.B.5", skillId: "math-multi-digit-multiplication", skillLabel: "Multiply multi-digit numbers", story: "Six mine carts each carry 24 crystals.", prompt: "How many crystals are carried altogether?", choices: ["124", "134", "144", "164"], answer: "144", hint: "Break 24 into 20 and 4, then multiply both by 6.", explanation: "6 × 20 = 120 and 6 × 4 = 24. Together, 120 + 24 = 144.", rune: "💎 Crystal rune" },
  { room: "Weather Chamber", emoji: "🌧️", subject: "Science", standard: "4-ESS2-2", skillId: "science-weathering-erosion", skillLabel: "Explain erosion", story: "Rainwater repeatedly flows down a bare hillside and carries soil into a stream.", prompt: "Which process is moving the soil?", choices: ["Erosion", "Condensation", "Freezing", "Reflection"], answer: "Erosion", hint: "Look for the process that transports rock or soil.", explanation: "Erosion is the movement of weathered material by water, wind, ice, or gravity.", rune: "🌧️ Storm rune" },
  { room: "Mirror Library", emoji: "🪞", subject: "Reading", standard: "RI.4.5", skillId: "reading-text-structure", skillLabel: "Identify text structure", story: "A passage describes how two temple animals are alike and different.", prompt: "Which text structure is being used?", choices: ["Compare and contrast", "Chronological order", "Cause and effect", "Problem and solution"], answer: "Compare and contrast", hint: "The passage focuses on similarities and differences.", explanation: "Compare-and-contrast structure organizes similarities and differences between subjects.", rune: "🪞 Mirror rune" },
  { room: "Energy Forge", emoji: "⚙️", subject: "Science", standard: "4-PS3-2", skillId: "science-energy-transfer", skillLabel: "Describe energy transfer", story: "A rolling stone strikes a wooden lever, causing the temple door to rise.", prompt: "What happened to the stone's energy?", choices: ["It transferred to the lever", "It disappeared", "It became matter", "It stopped existing"], answer: "It transferred to the lever", hint: "Energy can move from one object to another.", explanation: "The moving stone transferred energy to the lever, which then moved the door.", rune: "⚙️ Forge rune" },
  { room: "Sun Dial Vault", emoji: "☀️", subject: "Math", standard: "4.OA.A.3", skillId: "math-multistep-word-problems", skillLabel: "Solve multistep problems", story: "Explorers find 8 chests with 15 coins each and spend 37 coins repairing their gear.", prompt: "How many coins remain?", choices: ["73", "83", "93", "103"], answer: "83", hint: "Multiply first, then subtract the repair cost.", explanation: "8 × 15 = 120, and 120 − 37 = 83 coins remain.", rune: "☀️ Sun rune" },
];

function tone(on: boolean, correct: boolean) { if (!on || typeof window === "undefined" || !("AudioContext" in window)) return; const c = new AudioContext(); const o = c.createOscillator(); const g = c.createGain(); o.connect(g); g.connect(c.destination); o.frequency.value = correct ? 760 : 160; g.gain.setValueAtTime(.055, c.currentTime); g.gain.exponentialRampToValueAtTime(.001, c.currentTime + .18); o.start(); o.stop(c.currentTime + .19); o.addEventListener("ended", () => void c.close()); }

export default function MysteryTemplePage() {
  const { activeProfile } = useFamilyProfiles();
  const { completeGame, restartGame } = useGameSession(GAME_SLUG);
  const [stage, setStage] = useState<Stage>("intro"); const [relic, setRelic] = useState<Relic>("lens"); const [route, setRoute] = useState<number[]>([]); const [step, setStep] = useState(0); const [feedback, setFeedback] = useState<Feedback>("question"); const [selected, setSelected] = useState<string | null>(null); const [wrong, setWrong] = useState(0); const [hearts, setHearts] = useState(3); const [shield, setShield] = useState(0); const [clues, setClues] = useState(2); const [gems, setGems] = useState(0); const [combo, setCombo] = useState(0); const [bestCombo, setBestCombo] = useState(0); const [runes, setRunes] = useState<string[]>([]); const [sound, setSound] = useState(true);
  const puzzle = PUZZLES[route[step] ?? 0];
  const remainingRooms = useMemo(() => PUZZLES.map((_, i) => i).filter((i) => !route.includes(i)), [route]);

  function begin() { setShield(relic === "boots" ? 1 : 0); setClues(relic === "lens" ? 2 : 0); setStage("map"); }
  function chooseRoom(i: number) { setRoute((v) => [...v, i]); setStage("play"); }
  function save(correct: boolean) { recordLearningAttempt({ gameSlug: GAME_SLUG, subject: puzzle.subject, skillId: puzzle.skillId, skillLabel: puzzle.skillLabel, prompt: `${puzzle.story} ${puzzle.prompt}`, correctAnswer: puzzle.answer, correct, data: { standardCode: puzzle.standard, room: puzzle.room, adaptiveSupport: wrong > 0, chosenRoute: route.join(",") } }, activeProfile.id); }
  function choose(choice: string) { if (feedback === "explanation") return; setSelected(choice); const correct = choice === puzzle.answer; if (!correct && wrong === 0) { save(false); setWrong(1); setFeedback("hint"); setCombo(0); if (shield) setShield(0); else setHearts((v) => Math.max(0, v - 1)); tone(sound, false); return; } if (!correct) { setWrong((v) => v + 1); setFeedback("explanation"); setCombo(0); tone(sound, false); return; } save(true); const first = wrong === 0; const nextCombo = first ? combo + 1 : 0; setCombo(nextCombo); setBestCombo((v) => Math.max(v, nextCombo)); setGems((v) => v + (first ? 2 + (relic === "compass" ? 1 : 0) : 1)); setRunes((v) => [...v, puzzle.rune]); setFeedback("explanation"); tone(sound, true); }
  function clue() { if (feedback !== "question") return; setFeedback("hint"); if (clues) setClues((v) => v - 1); else setCombo(0); }
  function resetQuestion() { setFeedback("question"); setSelected(null); setWrong(0); }
  function advance() { if (route.length === 5) { setStage("vault"); return; } setStep((v) => v + 1); resetQuestion(); setStage("map"); }
  function openVault() { completeGame({ xp: 48 + gems + bestCombo * 3, coins: 12 + gems, score: gems * 120 + bestCombo * 40 + hearts * 25 }); setStage("finish"); }
  function replay() { restartGame(); setStage("intro"); setRoute([]); setStep(0); resetQuestion(); setHearts(3); setGems(0); setCombo(0); setBestCombo(0); setRunes([]); }

  if (stage === "intro") return <GameFrame title="Mystery Temple"><style>{css}</style><main style={page}><section style={hero}><div className="float" style={big}>🗿🏛️</div><span style={eyebrow}>GRADE 4 BRANCHING ADVENTURE</span><h1 style={title}>The Mystery Temple has awakened.</h1><p style={lead}>Choose a relic, chart your own five-room route, solve Grade 4 puzzles, collect runes, and unlock the Sun Dial Vault.</p><div style={grid}>{Object.entries(RELICS).map(([id, item]) => <button key={id} onClick={() => setRelic(id as Relic)} aria-pressed={relic === id} style={{...relicCard,...(relic === id ? activeRelic : {})}}><span style={{fontSize:40}}>{item.emoji}</span><strong>{item.name}</strong><small>{item.power}</small><span>{item.text}</span></button>)}</div><button onClick={begin} style={primary}>Enter the temple →</button><button onClick={() => setSound((v) => !v)} style={secondary}>{sound ? "🔊 Sound on" : "🔇 Sound off"}</button></section></main></GameFrame>;
  if (stage === "map") return <GameFrame title="Mystery Temple"><style>{css}</style><main style={page}><section style={hero}><span style={eyebrow}>CHOOSE YOUR PATH</span><h1 style={title}>Pick the next chamber.</h1><p style={lead}>Your route changes every run. Clear five of seven rooms to reach the vault.</p><div style={grid}>{remainingRooms.map((i) => <button key={i} onClick={() => chooseRoom(i)} style={roomButton}><span style={{fontSize:38}}>{PUZZLES[i].emoji}</span><strong>{PUZZLES[i].room}</strong><small>{PUZZLES[i].subject} · {PUZZLES[i].standard}</small></button>)}</div><div style={runeRow}>{runes.map((r) => <span key={r} style={badge}>{r}</span>)}</div></section></main></GameFrame>;
  if (stage === "vault") return <GameFrame title="Mystery Temple"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>☀️🔐</div><span style={eyebrow}>SUN DIAL VAULT</span><h1 style={title}>Five runes align the ancient lock.</h1><p style={lead}>You chose your own route and proved your strategy. Open the vault to bank your treasure.</p><div style={stats}><strong>💎 {gems}</strong><strong>🔥 {bestCombo}×</strong><strong>🗿 {runes.length}/5</strong></div><button onClick={openVault} style={primary}>Open the vault →</button></section></main></GameFrame>;
  if (stage === "finish") return <GameFrame title="Mystery Temple"><style>{css}</style><main style={page}><section style={hero}><div className="pop" style={big}>🏆☀️💎</div><span style={eyebrow}>VAULT UNLOCKED</span><h1 style={title}>{activeProfile.name} conquered Mystery Temple!</h1><p style={lead}>You used fractions, multiplication, text evidence, text structure, erosion, energy transfer, and multistep reasoning.</p><div style={stats}><strong>💎 {gems}</strong><strong>🔥 {bestCombo}×</strong><strong>❤️ {hearts}</strong></div><button onClick={replay} style={primary}>Choose a new route</button><Link href="/school" style={link}>Return to School Mode</Link></section></main></GameFrame>;

  return <GameFrame title="Mystery Temple"><style>{css}</style><main style={page}><header style={hud}><strong>{RELICS[relic].emoji} {RELICS[relic].name}</strong><div>❤️ {hearts} · 💎 {gems} · 🔥 {combo}× <button onClick={() => setSound((v) => !v)} style={soundButton}>{sound ? "🔊" : "🔇"}</button></div></header><div style={track}><div style={{...fill,width:`${(route.length / 5) * 100}%`}} /></div><section style={card}><div style={top}><span style={chip}>{puzzle.subject}</span><span>Room {route.length}/5 · {puzzle.standard}</span></div><div className="float" style={missionEmoji}>{puzzle.emoji}</div><span style={sector}>{puzzle.room}</span><p style={story}>{puzzle.story}</p><h1 style={question}>{puzzle.prompt}</h1><div style={choices}>{puzzle.choices.map((choice) => { const right = choice === puzzle.answer; const wrongChoice = selected === choice && !right; const reveal = feedback === "explanation" && right; return <button key={choice} data-correct={right ? "true" : "false"} disabled={feedback === "explanation" || wrongChoice} onClick={() => choose(choice)} style={{...choiceButton,...(reveal ? correctStyle : wrongChoice ? wrongStyle : {})}}>{choice}</button>; })}</div><section role="status" style={teaching}><strong>{feedback === "question" ? "TEMPLE CLUE" : feedback === "hint" ? "RELIC HINT" : "RUNE REPORT"}</strong><p>{feedback === "question" ? "Choose the answer that opens this chamber." : feedback === "hint" ? puzzle.hint : selected === puzzle.answer ? puzzle.explanation : `The answer is ${puzzle.answer}. ${puzzle.explanation}`}</p>{feedback === "question" ? <button onClick={clue} style={secondary}>{clues ? `Use free clue (${clues})` : "Reveal a clue"}</button> : feedback === "hint" ? <span>Try again. The temple is still listening.</span> : <button onClick={advance} style={primary}>{route.length === 5 ? "Approach the vault →" : "Claim the rune →"}</button>}</section></section></main></GameFrame>;
}

const css = `@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}@keyframes pop{0%{transform:scale(.72);opacity:0}80%{transform:scale(1.07)}100%{transform:scale(1);opacity:1}}.float{animation:float 2.2s ease-in-out infinite}.pop{animation:pop .5s ease-out both}@media(prefers-reduced-motion:reduce){.float,.pop{animation:none}}`;
const page: React.CSSProperties = { minHeight:"100vh", padding:"20px 14px 70px", background:"radial-gradient(circle at top,#5a3a15,#21170d 58%,#0c0906)", color:"#fff" };
const hero: React.CSSProperties = { maxWidth:920, margin:"0 auto", padding:"clamp(28px,6vw,58px)", borderRadius:34, textAlign:"center", background:"linear-gradient(145deg,rgba(255,207,102,.15),rgba(105,211,160,.09),#21180f)", border:"1px solid rgba(255,207,102,.28)" };
const big: React.CSSProperties = { fontSize:"clamp(5rem,16vw,9rem)" }; const eyebrow: React.CSSProperties = { color:"#ffd166", fontSize:11, fontWeight:950, letterSpacing:".14em" }; const title: React.CSSProperties = { margin:"10px auto", fontSize:"clamp(2.7rem,8vw,5.2rem)", lineHeight:.92, letterSpacing:"-.055em" }; const lead: React.CSSProperties = { maxWidth:720, margin:"0 auto 24px", color:"#e5d8c4", lineHeight:1.55, fontWeight:700 };
const grid: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,210px),1fr))", gap:12, margin:"22px 0" }; const relicCard: React.CSSProperties = { display:"grid", gap:7, padding:18, borderRadius:22, border:"1px solid #554125", background:"#19120c", color:"#fff", textAlign:"left", cursor:"pointer" }; const activeRelic: React.CSSProperties = { borderColor:"#ffd166", boxShadow:"0 0 0 3px rgba(255,209,102,.13)" }; const roomButton: React.CSSProperties = { ...relicCard, textAlign:"center", minHeight:150, justifyItems:"center" };
const primary: React.CSSProperties = { border:0, borderRadius:999, padding:"14px 22px", background:"#ffd166", color:"#1b1207", fontWeight:950, cursor:"pointer", margin:5 }; const secondary: React.CSSProperties = { border:"1px solid #76603c", borderRadius:999, padding:"11px 17px", background:"#17110b", color:"#f7e8cc", fontWeight:900, cursor:"pointer", margin:5 }; const link: React.CSSProperties = { display:"block", marginTop:16, color:"#ffd166", fontWeight:900 };
const hud: React.CSSProperties = { maxWidth:920, margin:"0 auto 12px", display:"flex", justifyContent:"space-between", gap:12, flexWrap:"wrap", padding:"12px 16px", borderRadius:18, background:"rgba(20,14,8,.88)", border:"1px solid #4f3c24" }; const soundButton: React.CSSProperties = { border:0, background:"transparent", cursor:"pointer" }; const track: React.CSSProperties = { maxWidth:920, height:9, margin:"0 auto 16px", borderRadius:999, overflow:"hidden", background:"#302414" }; const fill: React.CSSProperties = { height:"100%", background:"linear-gradient(90deg,#ffd166,#69d3a0)", transition:"width .3s" };
const card: React.CSSProperties = { maxWidth:920, margin:"0 auto", padding:"clamp(22px,5vw,42px)", borderRadius:30, background:"linear-gradient(145deg,#251a10,#17100a)", border:"1px solid #554125" }; const top: React.CSSProperties = { display:"flex", justifyContent:"space-between", gap:10, flexWrap:"wrap", color:"#cdbb9c", fontSize:12, fontWeight:850 }; const chip: React.CSSProperties = { padding:"5px 9px", borderRadius:999, background:"#3d2b15", color:"#ffd166" }; const missionEmoji: React.CSSProperties = { fontSize:"clamp(4rem,12vw,7rem)", textAlign:"center", marginTop:12 }; const sector: React.CSSProperties = { display:"block", textAlign:"center", color:"#69d3a0", fontWeight:950, letterSpacing:".08em" }; const story: React.CSSProperties = { color:"#e8dbc5", lineHeight:1.55, fontWeight:700, textAlign:"center" }; const question: React.CSSProperties = { textAlign:"center", fontSize:"clamp(1.8rem,5vw,3rem)" }; const choices: React.CSSProperties = { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,220px),1fr))", gap:10 }; const choiceButton: React.CSSProperties = { padding:"16px 14px", borderRadius:18, border:"1px solid #5a4528", background:"#21170d", color:"#fff", fontWeight:900, cursor:"pointer" }; const correctStyle: React.CSSProperties = { background:"#173b2c", borderColor:"#69d3a0" }; const wrongStyle: React.CSSProperties = { background:"#4a1f1f", borderColor:"#ff8e8e" }; const teaching: React.CSSProperties = { marginTop:18, padding:18, borderRadius:20, background:"#120d08", border:"1px solid #46351f", textAlign:"center" }; const runeRow: React.CSSProperties = { display:"flex", flexWrap:"wrap", justifyContent:"center", gap:8, marginTop:18 }; const badge: React.CSSProperties = { padding:"7px 10px", borderRadius:999, background:"#17110b", border:"1px solid #5d482b", color:"#ffd166", fontWeight:850 }; const stats: React.CSSProperties = { display:"flex", justifyContent:"center", flexWrap:"wrap", gap:12, margin:"22px 0", fontSize:"1.25rem" };
