export type HairColor = "dark" | "light" | "red" | "gray" | "none";

export type Character = {
  id: string;
  name: string;
  emoji: string;
  background: string;
  glasses: boolean;
  hat: boolean;
  facialHair: boolean;
  child: boolean;
  curlyHair: boolean;
  longHair: boolean;
  hairColor: HairColor;
};

export type Question = {
  id: string;
  label: string;
  matches: (character: Character) => boolean;
};

export const characters: Character[] = [
  {
    id: "adrian",
    name: "Adrian",
    emoji: "🧒🏻",
    background: "#D9FF5B",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "elliot",
    name: "Elliot",
    emoji: "👦🏻",
    background: "#C6B8FF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "maya",
    name: "Maya",
    emoji: "👧🏽",
    background: "#F7B2D9",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: true,
    hairColor: "dark",
  },
  {
    id: "leo",
    name: "Leo",
    emoji: "👦🏼",
    background: "#8FE3CF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: false,
    hairColor: "light",
  },
  {
    id: "zoe",
    name: "Zoe",
    emoji: "👧🏻",
    background: "#FFCF70",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: true,
    hairColor: "dark",
  },
  {
    id: "max",
    name: "Max",
    emoji: "👦🏾",
    background: "#8EC5FF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: true,
    curlyHair: true,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "nina",
    name: "Nina",
    emoji: "👩🏽‍🦱",
    background: "#E392FF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: true,
    longHair: true,
    hairColor: "dark",
  },
  {
    id: "jack",
    name: "Jack",
    emoji: "🧔🏻",
    background: "#FF9B85",
    glasses: false,
    hat: false,
    facialHair: true,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "sam",
    name: "Sam",
    emoji: "👨🏿‍🦲",
    background: "#FFE27A",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "none",
  },
  {
    id: "lily",
    name: "Lily",
    emoji: "👩🏼",
    background: "#B6E388",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "light",
  },
  {
    id: "omar",
    name: "Omar",
    emoji: "👨🏽",
    background: "#72D5D0",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "ava",
    name: "Ava",
    emoji: "👩🏻‍🦰",
    background: "#F4A261",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "red",
  },
  {
    id: "ben",
    name: "Ben",
    emoji: "👨🏼‍🦱",
    background: "#A0C4FF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: true,
    longHair: false,
    hairColor: "light",
  },
  {
    id: "ruby",
    name: "Ruby",
    emoji: "👵🏾",
    background: "#FFC6FF",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: true,
    longHair: false,
    hairColor: "gray",
  },
  {
    id: "theo",
    name: "Theo",
    emoji: "👴🏻",
    background: "#BDE0FE",
    glasses: false,
    hat: false,
    facialHair: true,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "gray",
  },
  {
    id: "mia",
    name: "Mia",
    emoji: "👩🏻‍🦳",
    background: "#E9EDC9",
    glasses: false,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "gray",
  },
  {
    id: "alex",
    name: "Alex",
    emoji: "🤓",
    background: "#FFD6A5",
    glasses: true,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "ivy",
    name: "Ivy",
    emoji: "👩🏿‍🏫",
    background: "#CAFFBF",
    glasses: true,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "dark",
  },
  {
    id: "noah",
    name: "Noah",
    emoji: "👨🏻‍🔬",
    background: "#9BF6FF",
    glasses: true,
    hat: false,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "ella",
    name: "Ella",
    emoji: "👩🏼‍🎨",
    background: "#FDFFB6",
    glasses: false,
    hat: true,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "light",
  },
  {
    id: "kai",
    name: "Kai",
    emoji: "👨🏽‍🚀",
    background: "#A0A6FF",
    glasses: false,
    hat: true,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "rose",
    name: "Rose",
    emoji: "👒",
    background: "#FFADAD",
    glasses: false,
    hat: true,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: true,
    hairColor: "red",
  },
  {
    id: "drew",
    name: "Drew",
    emoji: "🧢",
    background: "#BDB2FF",
    glasses: false,
    hat: true,
    facialHair: false,
    child: true,
    curlyHair: false,
    longHair: false,
    hairColor: "dark",
  },
  {
    id: "finn",
    name: "Finn",
    emoji: "🤠",
    background: "#FAD2A1",
    glasses: false,
    hat: true,
    facialHair: false,
    child: false,
    curlyHair: false,
    longHair: false,
    hairColor: "light",
  },
];

export const questions: Question[] = [
  {
    id: "glasses",
    label: "Do they wear glasses?",
    matches: (character) => character.glasses,
  },
  {
    id: "hat",
    label: "Are they wearing a hat?",
    matches: (character) => character.hat,
  },
  {
    id: "facial-hair",
    label: "Do they have facial hair?",
    matches: (character) => character.facialHair,
  },
  {
    id: "child",
    label: "Are they a child?",
    matches: (character) => character.child,
  },
  {
    id: "curly",
    label: "Do they have curly hair?",
    matches: (character) => character.curlyHair,
  },
  {
    id: "long",
    label: "Do they have long hair?",
    matches: (character) => character.longHair,
  },
  {
    id: "dark-hair",
    label: "Do they have dark hair?",
    matches: (character) => character.hairColor === "dark",
  },
  {
    id: "light-hair",
    label: "Do they have light hair?",
    matches: (character) => character.hairColor === "light",
  },
  {
    id: "red-hair",
    label: "Do they have red hair?",
    matches: (character) => character.hairColor === "red",
  },
  {
    id: "gray-hair",
    label: "Do they have gray hair?",
    matches: (character) => character.hairColor === "gray",
  },
  {
    id: "bald",
    label: "Are they bald?",
    matches: (character) => character.hairColor === "none",
  },
];

export function randomCharacter(excludeId?: string): Character {
  const pool = excludeId
    ? characters.filter((character) => character.id !== excludeId)
    : characters;

  return pool[Math.floor(Math.random() * pool.length)];
}

export function getCharacter(id: string | null): Character | null {
  if (!id) return null;
  return characters.find((character) => character.id === id) ?? null;
}
